begin;
-- 320 phrases (Réception 4 étoiles)
insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('REC_REC_CI_STANDARD_0001', 'REC_CI_STANDARD', 'Bonjour, ravi(e) de vous accueillir.', 'Good afternoon, it''''s a pleasure to welcome you.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_STANDARD_0002', 'REC_CI_STANDARD', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_STANDARD_0003', 'REC_CI_STANDARD', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CI_STANDARD_0004', 'REC_CI_STANDARD', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CI_STANDARD_0005', 'REC_CI_STANDARD', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CI_STANDARD_0006', 'REC_CI_STANDARD', 'Avez-vous une réservation chez nous ?', 'Do you have a reservation with us?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_STANDARD_0007', 'REC_CI_STANDARD', 'Puis-je voir votre passeport ou une pièce d''identité, s''il vous plaît ?', 'Could I see your passport or ID, please?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_STANDARD_0008', 'REC_CI_STANDARD', 'Merci, {guest_name}. Je retrouve votre réservation.', 'Thank you, {guest}. I am locating your reservation.', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_STANDARD_0009', 'REC_CI_STANDARD', 'Vous êtes en chambre {room_number} pour {time} nuits.', 'You are in room {room} for {time} nights.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_STANDARD_0010', 'REC_CI_STANDARD', 'Voici votre carte-clé. L''ascenseur est sur votre droite.', 'Here is your key card. The elevator is to your right.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_STANDARD_0011', 'REC_CI_STANDARD', 'J''ai une réservation au nom de {guest_name}.', 'I have a reservation under the name of {guest_name}.', 'Vérification', 'A2', 'CLIENT', null),
('REC_REC_CI_STANDARD_0012', 'REC_CI_STANDARD', 'Souhaitez-vous que je programme un réveil pour demain matin ?', 'Would you like me to arrange a wake-up call for tomorrow morning?', 'Service', 'B1', 'STAFF', null),
('REC_REC_CI_STANDARD_0013', 'REC_CI_STANDARD', 'Souhaitez-vous une chambre plus calme ou plutôt proche de l''ascenseur ?', 'Would you prefer a quieter room or one closer to the elevator?', 'Information', 'B1', 'STAFF', null),
('REC_REC_CI_STANDARD_0014', 'REC_CI_STANDARD', 'Si vous le souhaitez, je peux vous présenter brièvement les services de l''hôtel.', 'If you wish, I can briefly introduce the hotel services.', 'Information', 'B1', 'STAFF', null),
('REC_REC_CI_STANDARD_0015', 'REC_CI_STANDARD', 'Le petit-déjeuner est-il inclus dans le tarif ?', 'Is breakfast included in the rate?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_CI_STANDARD_0016', 'REC_CI_STANDARD', 'Pouvez-vous m''indiquer comment aller à l''ascenseur ?', 'Could you tell me how to get to the elevator?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_CI_ADMIN_0001', 'REC_CI_ADMIN', 'Bonjour, ravi(e) de vous accueillir.', 'Good afternoon, it''''s a pleasure to welcome you.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_ADMIN_0002', 'REC_CI_ADMIN', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_ADMIN_0003', 'REC_CI_ADMIN', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CI_ADMIN_0004', 'REC_CI_ADMIN', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CI_ADMIN_0005', 'REC_CI_ADMIN', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CI_ADMIN_0006', 'REC_CI_ADMIN', 'Pouvez-vous remplir ce formulaire d''enregistrement, s''il vous plaît ?', 'Could you please complete this registration form?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_ADMIN_0007', 'REC_CI_ADMIN', 'J''ai juste besoin de votre signature ici, s''il vous plaît.', 'I just need your signature here, please.', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_ADMIN_0008', 'REC_CI_ADMIN', 'Puis-je avoir une carte bancaire pour la garantie, s''il vous plaît ?', 'May I have a credit card for the guarantee, please?', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CI_ADMIN_0009', 'REC_CI_ADMIN', 'Nous effectuerons une préautorisation de {amount} {currency}.', 'We will place a pre-authorization of {amount} {currency}.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CI_ADMIN_0010', 'REC_CI_ADMIN', 'Ce montant sera libéré au moment du départ.', 'This amount will be released at check-out.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CI_ADMIN_0011', 'REC_CI_ADMIN', 'La chambre est déjà payée. Pourquoi une garantie ?', 'The room is prepaid. Why do you need a guarantee?', 'Paiement', 'A2', 'CLIENT', null),
('REC_REC_CI_ADMIN_0012', 'REC_CI_ADMIN', 'Il s''agit simplement d''une empreinte pour les extras éventuels, comme le minibar.', 'This is simply a hold for incidental charges, such as the minibar.', 'Paiement', 'B1', 'STAFF', null),
('REC_REC_CI_ADMIN_0013', 'REC_CI_ADMIN', 'Pour des raisons de sécurité, puis-je scanner votre pièce d''identité ?', 'For security purposes, may I scan your identification?', 'Vérification', 'B1', 'STAFF', null),
('REC_REC_CI_ADMIN_0014', 'REC_CI_ADMIN', 'Si vous le souhaitez, je peux confirmer votre email avant validation.', 'If you wish, I can confirm your email address before we proceed.', 'Vérification', 'B1', 'STAFF', null),
('REC_REC_CI_ADMIN_0015', 'REC_CI_ADMIN', 'Quel montant allez-vous bloquer exactement ?', 'How much will you hold exactly?', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CI_ADMIN_0016', 'REC_CI_ADMIN', 'Puis-je utiliser une autre carte pour la garantie ?', 'May I use another card for the guarantee?', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CI_EARLY_0001', 'REC_CI_EARLY', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_EARLY_0002', 'REC_CI_EARLY', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_EARLY_0003', 'REC_CI_EARLY', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CI_EARLY_0004', 'REC_CI_EARLY', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CI_EARLY_0005', 'REC_CI_EARLY', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CI_EARLY_0006', 'REC_CI_EARLY', 'L''heure d''arrivée est normalement à {time}.', 'Check-in time is normally at {time}.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_EARLY_0007', 'REC_CI_EARLY', 'Nous pouvons garder vos bagages en lieu sûr.', 'We can store your luggage securely.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_EARLY_0008', 'REC_CI_EARLY', 'Vous pouvez vous installer au lobby en attendant.', 'You are welcome to relax in the lobby while you wait.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_EARLY_0009', 'REC_CI_EARLY', 'Je vais demander à Housekeeping de prioriser votre chambre.', 'I will ask Housekeeping to prioritize your room.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_EARLY_0010', 'REC_CI_EARLY', 'Nous vous contacterons dès que la chambre sera prête.', 'We will contact you as soon as your room is ready.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_EARLY_0011', 'REC_CI_EARLY', 'Je suis très fatigué(e). Est-ce possible d''avoir une chambre maintenant ?', 'I am very tired. Is it possible to have a room now?', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_CI_EARLY_0012', 'REC_CI_EARLY', 'Je vous tiendrai informé(e) très rapidement.', 'I will keep you updated shortly.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CI_EARLY_0013', 'REC_CI_EARLY', 'Veuillez accepter nos sincères excuses pour ce désagrément.', 'Please accept our sincere apologies for the inconvenience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CI_EARLY_0014', 'REC_CI_EARLY', 'Souhaitez-vous un rafraîchissement offert pendant l''attente ?', 'Would you like a complimentary refreshment while you wait?', 'Service', 'B1', 'STAFF', null),
('REC_REC_CI_EARLY_0015', 'REC_CI_EARLY', 'J''avais demandé un early check-in. Pouvez-vous vérifier ?', 'I requested an early check-in. Could you please check?', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CI_EARLY_0016', 'REC_CI_EARLY', 'Pouvez-vous me donner une estimation de temps ?', 'Could you give me an estimated timing?', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CI_WALKIN_0001', 'REC_CI_WALKIN', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_WALKIN_0002', 'REC_CI_WALKIN', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_WALKIN_0003', 'REC_CI_WALKIN', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CI_WALKIN_0004', 'REC_CI_WALKIN', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CI_WALKIN_0005', 'REC_CI_WALKIN', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CI_WALKIN_0006', 'REC_CI_WALKIN', 'Avez-vous une réservation, ou arrivez-vous sans réservation ?', 'Do you have a reservation, or is this a walk-in?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_WALKIN_0007', 'REC_CI_WALKIN', 'Je vérifie la disponibilité pour ce soir.', 'I am checking availability for tonight.', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_WALKIN_0008', 'REC_CI_WALKIN', 'Le tarif pour ce soir est de {amount} {currency}, hors petit-déjeuner.', 'Tonight''''s rate is {amount} {currency}, excluding breakfast.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CI_WALKIN_0009', 'REC_CI_WALKIN', 'Souhaitez-vous une chambre double ou deux lits ?', 'Would you like a double bed or twin beds?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CI_WALKIN_0010', 'REC_CI_WALKIN', 'Je peux vous proposer une chambre calme côté cour.', 'I can offer you a quiet room facing the courtyard.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_WALKIN_0011', 'REC_CI_WALKIN', 'Je n''ai pas réservé. Avez-vous une chambre disponible ?', 'I do not have a reservation. Do you have a room available?', 'Vérification', 'A2', 'CLIENT', null),
('REC_REC_CI_WALKIN_0012', 'REC_CI_WALKIN', 'Si nous sommes complets, je peux vous proposer une alternative à proximité.', 'If we are fully booked, I can suggest an alternative nearby.', 'Service', 'B1', 'STAFF', null),
('REC_REC_CI_WALKIN_0013', 'REC_CI_WALKIN', 'Souhaitez-vous un tarif flexible ou non remboursable ?', 'Would you prefer a flexible or non-refundable rate?', 'Paiement', 'B1', 'STAFF', null),
('REC_REC_CI_WALKIN_0014', 'REC_CI_WALKIN', 'Je peux finaliser l''enregistrement rapidement, si cela vous convient.', 'I can complete the check-in quickly, if that suits you.', 'Accueil', 'B1', 'STAFF', null),
('REC_REC_CI_WALKIN_0015', 'REC_CI_WALKIN', 'Pouvez-vous inclure le petit-déjeuner dans le prix ?', 'Could you include breakfast in the price?', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CI_WALKIN_0016', 'REC_CI_WALKIN', 'Je resterai peut-être plusieurs nuits. Avez-vous un meilleur tarif ?', 'I may stay several nights. Do you have a better rate?', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CI_UPGRADE_0001', 'REC_CI_UPGRADE', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0002', 'REC_CI_UPGRADE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0003', 'REC_CI_UPGRADE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0004', 'REC_CI_UPGRADE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CI_UPGRADE_0005', 'REC_CI_UPGRADE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CI_UPGRADE_0006', 'REC_CI_UPGRADE', 'Souhaitez-vous un surclassement pour votre séjour ?', 'Would you be interested in an upgrade for your stay?', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_UPGRADE_0007', 'REC_CI_UPGRADE', 'Nous avons une catégorie supérieure disponible aujourd''hui.', 'We have a higher room category available today.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_UPGRADE_0008', 'REC_CI_UPGRADE', 'Le supplément est de {amount} {currency} par nuit.', 'The supplement is {amount} {currency} per night.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CI_UPGRADE_0009', 'REC_CI_UPGRADE', 'La catégorie supérieure offre plus d''espace et une meilleure vue.', 'The higher category offers more space and a better view.', 'Information', 'A2', 'STAFF', null),
('REC_REC_CI_UPGRADE_0010', 'REC_CI_UPGRADE', 'Souhaitez-vous voir la chambre avant de décider ?', 'Would you like to see the room before deciding?', 'Service', 'A2', 'STAFF', null),
('REC_REC_CI_UPGRADE_0011', 'REC_CI_UPGRADE', 'Quelle est la différence avec ma chambre actuelle ?', 'What is the difference compared to my current room?', 'Service', 'A2', 'CLIENT', null),
('REC_REC_CI_UPGRADE_0012', 'REC_CI_UPGRADE', 'Je comprends. La catégorie réservée est déjà très confortable.', 'I understand. Your booked category is already very comfortable.', 'Service', 'B1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0013', 'REC_CI_UPGRADE', 'Je peux vous proposer un tarif préférentiel valable aujourd''hui.', 'I can offer you a preferential rate valid today.', 'Paiement', 'B1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0014', 'REC_CI_UPGRADE', 'Si vous le souhaitez, je vous détaille les avantages en une minute.', 'If you wish, I can outline the benefits in one minute.', 'Service', 'B1', 'STAFF', null),
('REC_REC_CI_UPGRADE_0015', 'REC_CI_UPGRADE', 'C''est un peu cher pour moi.', 'That is a bit expensive for me.', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CI_UPGRADE_0016', 'REC_CI_UPGRADE', 'Je préfère garder la chambre réservée, merci.', 'I''''d rather keep the booked room, thank you.', 'Service', 'B1', 'CLIENT', null),
('REC_REC_INFO_FACILITIES_0001', 'REC_INFO_FACILITIES', 'Bonjour, bienvenue à la réception.', 'Good afternoon, welcome to reception.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0002', 'REC_INFO_FACILITIES', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0003', 'REC_INFO_FACILITIES', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0004', 'REC_INFO_FACILITIES', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_INFO_FACILITIES_0005', 'REC_INFO_FACILITIES', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_INFO_FACILITIES_0006', 'REC_INFO_FACILITIES', 'Le petit-déjeuner est servi de {time} à {time}.', 'Breakfast is served from {time} to {time}.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0007', 'REC_INFO_FACILITIES', 'Le restaurant se trouve au premier étage.', 'The restaurant is located on the first floor.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0008', 'REC_INFO_FACILITIES', 'La salle de sport est accessible avec votre carte-clé.', 'The gym is accessible with your key card.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0009', 'REC_INFO_FACILITIES', 'Le spa est ouvert jusqu''à {time} aujourd''hui.', 'The spa is open until {time} today.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0010', 'REC_INFO_FACILITIES', 'Nous proposons un service en chambre toute la journée.', 'We offer room service throughout the day.', 'Service', 'A2', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0011', 'REC_INFO_FACILITIES', 'Où se trouve le restaurant, s''il vous plaît ?', 'Where is the restaurant, please?', 'Information', 'A2', 'CLIENT', null),
('REC_REC_INFO_FACILITIES_0012', 'REC_INFO_FACILITIES', 'Certains services nécessitent une réservation ; je peux m''en charger pour vous.', 'Some services require a booking; I can arrange that for you.', 'Service', 'B1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0013', 'REC_INFO_FACILITIES', 'Je suis désolé, le bar est actuellement fermé, mais il rouvre à {time}.', 'I''''m sorry, the bar is currently closed, but it reopens at {time}.', 'Information', 'B1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0014', 'REC_INFO_FACILITIES', 'Souhaitez-vous que je vous envoie les horaires par message ?', 'Would you like me to message you the opening hours?', 'Service', 'B1', 'STAFF', null),
('REC_REC_INFO_FACILITIES_0015', 'REC_INFO_FACILITIES', 'Y a-t-il un code vestimentaire au restaurant ?', 'Is there a dress code for the restaurant?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_INFO_FACILITIES_0016', 'REC_INFO_FACILITIES', 'L''accès au spa est-il inclus pour les clients ?', 'Is access to the spa included for guests?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_INFO_DIRECTIONS_0001', 'REC_INFO_DIRECTIONS', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0002', 'REC_INFO_DIRECTIONS', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0003', 'REC_INFO_DIRECTIONS', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0004', 'REC_INFO_DIRECTIONS', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null)
on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('REC_REC_INFO_DIRECTIONS_0005', 'REC_INFO_DIRECTIONS', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_INFO_DIRECTIONS_0006', 'REC_INFO_DIRECTIONS', 'Je peux vous montrer sur la carte.', 'I can show you on the map.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0007', 'REC_INFO_DIRECTIONS', 'C''est à environ {time} minutes à pied.', 'It is about a {time}-minute walk.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0008', 'REC_INFO_DIRECTIONS', 'Tournez à gauche en sortant de l''hôtel.', 'Turn left when you exit the hotel.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0009', 'REC_INFO_DIRECTIONS', 'Souhaitez-vous que j''appelle un taxi ?', 'Would you like me to call a taxi for you?', 'Service', 'A2', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0010', 'REC_INFO_DIRECTIONS', 'Le trajet jusqu''à {location} prend environ {time} minutes en voiture.', 'The drive to {location} takes about {time} minutes.', 'Information', 'A2', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0011', 'REC_INFO_DIRECTIONS', 'Pouvez-vous m''indiquer le chemin, s''il vous plaît ?', 'Could you give me directions, please?', 'Information', 'A2', 'CLIENT', null),
('REC_REC_INFO_DIRECTIONS_0012', 'REC_INFO_DIRECTIONS', 'Le trafic peut être dense ; je vous conseille de prévoir un peu de marge.', 'Traffic can be heavy; I recommend allowing extra time.', 'Information', 'B1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0013', 'REC_INFO_DIRECTIONS', 'Je peux organiser un transfert privé si vous le souhaitez.', 'I can arrange a private transfer if you wish.', 'Service', 'B1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0014', 'REC_INFO_DIRECTIONS', 'Souhaitez-vous que j''imprime l''itinéraire pour vous ?', 'Would you like me to print the directions for you?', 'Service', 'B1', 'STAFF', null),
('REC_REC_INFO_DIRECTIONS_0015', 'REC_INFO_DIRECTIONS', 'Quelle est la meilleure option pour aller à l''aéroport ?', 'What is the best option to get to the airport?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_INFO_DIRECTIONS_0016', 'REC_INFO_DIRECTIONS', 'Est-ce que c''est sûr de rentrer à pied le soir ?', 'Is it safe to walk back in the evening?', 'Information', 'B1', 'CLIENT', null),
('REC_REC_SERV_BOOKING_0001', 'REC_SERV_BOOKING', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0002', 'REC_SERV_BOOKING', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0003', 'REC_SERV_BOOKING', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0004', 'REC_SERV_BOOKING', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_SERV_BOOKING_0005', 'REC_SERV_BOOKING', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_SERV_BOOKING_0006', 'REC_SERV_BOOKING', 'Quel type de restaurant souhaitez-vous ?', 'What type of restaurant would you like?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_BOOKING_0007', 'REC_SERV_BOOKING', 'Pour combien de personnes est la réservation ?', 'For how many people is the reservation?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_BOOKING_0008', 'REC_SERV_BOOKING', 'À quelle heure souhaitez-vous dîner ?', 'What time would you like to dine?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_BOOKING_0009', 'REC_SERV_BOOKING', 'Je contacte l''établissement pour vérifier la disponibilité.', 'I will contact the venue to check availability.', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_BOOKING_0010', 'REC_SERV_BOOKING', 'Je vous confirme dès que c''est validé.', 'I will confirm as soon as it is secured.', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_SERV_BOOKING_0011', 'REC_SERV_BOOKING', 'Pouvez-vous réserver une table pour ce soir ?', 'Could you book a table for tonight?', 'Service', 'A2', 'CLIENT', null),
('REC_REC_SERV_BOOKING_0012', 'REC_SERV_BOOKING', 'Souhaitez-vous une table calme, ou plutôt une ambiance animée ?', 'Would you prefer a quiet table, or a livelier atmosphere?', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0013', 'REC_SERV_BOOKING', 'Je peux aussi organiser le transport, si besoin.', 'I can also arrange transportation, if needed.', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0014', 'REC_SERV_BOOKING', 'Je vous enverrai l''adresse et la confirmation par message.', 'I will message you the address and confirmation.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_SERV_BOOKING_0015', 'REC_SERV_BOOKING', 'Pouvez-vous demander une table près de la fenêtre ?', 'Could you request a table by the window?', 'Service', 'B1', 'CLIENT', null),
('REC_REC_SERV_BOOKING_0016', 'REC_SERV_BOOKING', 'Y a-t-il des options végétariennes ?', 'Are there vegetarian options?', 'Service', 'B1', 'CLIENT', null),
('REC_REC_SERV_WAKEUP_0001', 'REC_SERV_WAKEUP', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0002', 'REC_SERV_WAKEUP', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0003', 'REC_SERV_WAKEUP', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0004', 'REC_SERV_WAKEUP', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_SERV_WAKEUP_0005', 'REC_SERV_WAKEUP', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_SERV_WAKEUP_0006', 'REC_SERV_WAKEUP', 'À quelle heure souhaitez-vous le réveil ?', 'What time would you like the wake-up call?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0007', 'REC_SERV_WAKEUP', 'C''est noté pour {time}.', 'Noted for {time}.', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0008', 'REC_SERV_WAKEUP', 'Souhaitez-vous un deuxième appel de confirmation ?', 'Would you like a backup call as well?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0009', 'REC_SERV_WAKEUP', 'Avez-vous besoin d''un taxi pour demain matin ?', 'Do you need a taxi for tomorrow morning?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0010', 'REC_SERV_WAKEUP', 'Merci, tout est noté.', 'Thank you, everything is noted.', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0011', 'REC_SERV_WAKEUP', 'Pouvez-vous me réveiller à {time} ?', 'Could you wake me up at {time}?', 'Service', 'A2', 'CLIENT', null),
('REC_REC_SERV_WAKEUP_0012', 'REC_SERV_WAKEUP', 'Nous pouvons préparer un petit-déjeuner à emporter si vous partez tôt.', 'We can prepare a takeaway breakfast if you are leaving early.', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0013', 'REC_SERV_WAKEUP', 'Je m''assure que tout soit correctement programmé.', 'I will make sure everything is correctly scheduled.', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0014', 'REC_SERV_WAKEUP', 'Souhaitez-vous que je confirme votre transfert la veille ?', 'Would you like me to confirm your transfer the evening before?', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_WAKEUP_0015', 'REC_SERV_WAKEUP', 'J''ai un vol très tôt, je ne veux pas le manquer.', 'I have an early flight, I don''''t want to miss it.', 'Service', 'B1', 'CLIENT', null),
('REC_REC_SERV_WAKEUP_0016', 'REC_SERV_WAKEUP', 'Finalement, je n''ai plus besoin du réveil.', 'Actually, I no longer need the wake-up call.', 'Service', 'B1', 'CLIENT', null),
('REC_REC_SERV_MAINTENANCE_0001', 'REC_SERV_MAINTENANCE', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0002', 'REC_SERV_MAINTENANCE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0003', 'REC_SERV_MAINTENANCE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0004', 'REC_SERV_MAINTENANCE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_SERV_MAINTENANCE_0005', 'REC_SERV_MAINTENANCE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_SERV_MAINTENANCE_0006', 'REC_SERV_MAINTENANCE', 'Je suis désolé(e) d''apprendre cela.', 'I''''m sorry to hear that.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0007', 'REC_SERV_MAINTENANCE', 'Pouvez-vous me décrire le problème, s''il vous plaît ?', 'Could you describe the issue, please?', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0008', 'REC_SERV_MAINTENANCE', 'Je vais envoyer un technicien immédiatement.', 'I will send a technician immediately.', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0009', 'REC_SERV_MAINTENANCE', 'Puis-je avoir votre numéro de chambre, s''il vous plaît ?', 'May I have your room number, please?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0010', 'REC_SERV_MAINTENANCE', 'May we enter your room, please?', 'May we enter your room, please?', 'Service', 'A2', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0011', 'REC_SERV_MAINTENANCE', 'La climatisation ne fonctionne pas.', 'The air conditioning is not working.', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_SERV_MAINTENANCE_0012', 'REC_SERV_MAINTENANCE', 'Je vous tiendrai informé(e) très rapidement.', 'I will keep you updated shortly.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0013', 'REC_SERV_MAINTENANCE', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0014', 'REC_SERV_MAINTENANCE', 'Si nécessaire, nous pouvons organiser un changement de chambre.', 'If needed, we can arrange a room change.', 'Service', 'B1', 'STAFF', null),
('REC_REC_SERV_MAINTENANCE_0015', 'REC_SERV_MAINTENANCE', 'C''est urgent, j''ai besoin d''une solution tout de suite.', 'It''''s urgent, I need a solution right away.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_SERV_MAINTENANCE_0016', 'REC_SERV_MAINTENANCE', 'Pouvez-vous me proposer une alternative temporaire ?', 'Could you offer a temporary alternative?', 'Service', 'B1', 'CLIENT', null),
('REC_REC_PROB_NOISE_0001', 'REC_PROB_NOISE', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_NOISE_0002', 'REC_PROB_NOISE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_NOISE_0003', 'REC_PROB_NOISE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_PROB_NOISE_0004', 'REC_PROB_NOISE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_PROB_NOISE_0005', 'REC_PROB_NOISE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_PROB_NOISE_0006', 'REC_PROB_NOISE', 'Je suis désolé(e) pour la gêne occasionnée.', 'I''''m sorry for the disturbance.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_NOISE_0007', 'REC_PROB_NOISE', 'Je vais contacter la chambre concernée immédiatement.', 'I will contact the room concerned immediately.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_NOISE_0008', 'REC_PROB_NOISE', 'Je peux envoyer la sécurité à l''étage.', 'I can send security to the floor.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_NOISE_0009', 'REC_PROB_NOISE', 'Nous pouvons vous proposer une chambre plus calme.', 'We can offer you a quieter room.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_NOISE_0010', 'REC_PROB_NOISE', 'Merci, je m''en occupe tout de suite.', 'Thank you, I am taking care of it right away.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_NOISE_0011', 'REC_PROB_NOISE', 'Il y a beaucoup de bruit à côté.', 'There is a lot of noise next door.', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_PROB_NOISE_0012', 'REC_PROB_NOISE', 'Je vous tiendrai informé(e) très rapidement.', 'I will keep you updated shortly.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_NOISE_0013', 'REC_PROB_NOISE', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_NOISE_0014', 'REC_PROB_NOISE', 'Si vous le souhaitez, je peux ajuster votre folio en geste commercial.', 'If you wish, I can adjust your folio as a gesture of goodwill.', 'Paiement', 'B1', 'STAFF', null),
('REC_REC_PROB_NOISE_0015', 'REC_PROB_NOISE', 'Je veux changer de chambre si ça continue.', 'I want to change rooms if it continues.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_NOISE_0016', 'REC_PROB_NOISE', 'Je suis très mécontent(e), c''est inacceptable.', 'I''''m very unhappy, this is unacceptable.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_CLEAN_0001', 'REC_PROB_CLEAN', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0002', 'REC_PROB_CLEAN', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0003', 'REC_PROB_CLEAN', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0004', 'REC_PROB_CLEAN', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_PROB_CLEAN_0005', 'REC_PROB_CLEAN', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_PROB_CLEAN_0006', 'REC_PROB_CLEAN', 'Je suis vraiment désolé(e) d''entendre cela.', 'I''''m truly sorry to hear that.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_CLEAN_0007', 'REC_PROB_CLEAN', 'Ce n''est pas à la hauteur de nos standards.', 'This is not up to our standards.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_CLEAN_0008', 'REC_PROB_CLEAN', 'Je vais envoyer Housekeeping immédiatement.', 'I will send Housekeeping immediately.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_CLEAN_0009', 'REC_PROB_CLEAN', 'Souhaitez-vous attendre au lobby pendant que nous corrigeons ?', 'Would you like to wait in the lobby while we fix this?', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_CLEAN_0010', 'REC_PROB_CLEAN', 'Nous pouvons vous proposer un changement de chambre.', 'We can offer you a room change.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_CLEAN_0011', 'REC_PROB_CLEAN', 'La chambre n''est pas propre.', 'The room is not clean.', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_PROB_CLEAN_0012', 'REC_PROB_CLEAN', 'Je vais résoudre cela dans les {time} minutes.', 'I will have this resolved within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0013', 'REC_PROB_CLEAN', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0014', 'REC_PROB_CLEAN', 'Permettez-nous de vous offrir un rafraîchissement en attendant.', 'Please allow us to offer you a refreshment while you wait.', 'Service', 'B1', 'STAFF', null),
('REC_REC_PROB_CLEAN_0015', 'REC_PROB_CLEAN', 'Je souhaite changer de chambre immédiatement.', 'I would like to change rooms immediately.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_CLEAN_0016', 'REC_PROB_CLEAN', 'C''est inacceptable dans un hôtel comme celui-ci.', 'This is unacceptable in a hotel like this.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_BILL_0001', 'REC_PROB_BILL', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_BILL_0002', 'REC_PROB_BILL', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_BILL_0003', 'REC_PROB_BILL', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_PROB_BILL_0004', 'REC_PROB_BILL', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_PROB_BILL_0005', 'REC_PROB_BILL', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_PROB_BILL_0006', 'REC_PROB_BILL', 'Merci de me montrer la ligne concernée, s''il vous plaît.', 'Could you please show me the line you are disputing?', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_PROB_BILL_0007', 'REC_PROB_BILL', 'Je vais vérifier cela dans le système.', 'I will check this in the system.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_PROB_BILL_0008', 'REC_PROB_BILL', 'Je comprends. Laissez-moi clarifier les charges.', 'I understand. Let me clarify the charges.', 'Paiement', 'A2', 'STAFF', null)
on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('REC_REC_PROB_BILL_0009', 'REC_PROB_BILL', 'Je demande une vérification auprès du service concerné.', 'I will request verification with the relevant department.', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_PROB_BILL_0010', 'REC_PROB_BILL', 'Merci, je reviens vers vous dans un instant.', 'Thank you, I will be right back.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_BILL_0011', 'REC_PROB_BILL', 'Je conteste un montant sur la facture.', 'I dispute an amount on the bill.', 'Paiement', 'A2', 'CLIENT', null),
('REC_REC_PROB_BILL_0012', 'REC_PROB_BILL', 'Je vous tiendrai informé(e) très rapidement.', 'I will keep you updated shortly.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_BILL_0013', 'REC_PROB_BILL', 'Je vais m''en occuper personnellement.', 'I will personally take care of this for you.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_BILL_0014', 'REC_PROB_BILL', 'En geste commercial, nous pouvons retirer les frais de minibar.', 'As a gesture of goodwill, we can remove the minibar charges.', 'Paiement', 'B1', 'STAFF', null),
('REC_REC_PROB_BILL_0015', 'REC_PROB_BILL', 'Je refuse de payer ce que je n''ai pas consommé.', 'I refuse to pay for something I did not consume.', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_PROB_BILL_0016', 'REC_PROB_BILL', 'Je veux parler à un responsable.', 'I want to speak to a manager.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_KEY_0001', 'REC_PROB_KEY', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_KEY_0002', 'REC_PROB_KEY', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_KEY_0003', 'REC_PROB_KEY', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_PROB_KEY_0004', 'REC_PROB_KEY', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_PROB_KEY_0005', 'REC_PROB_KEY', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_PROB_KEY_0006', 'REC_PROB_KEY', 'Je suis désolé(e), votre carte-clé ne fonctionne pas.', 'I''''m sorry, your key card is not working.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_KEY_0007', 'REC_PROB_KEY', 'Elle a peut-être été démagnétisée par un téléphone.', 'It may have been demagnetized by a phone.', 'Information', 'A2', 'STAFF', null),
('REC_REC_PROB_KEY_0008', 'REC_PROB_KEY', 'Puis-je avoir votre nom et votre numéro de chambre ?', 'May I have your name and room number?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_PROB_KEY_0009', 'REC_PROB_KEY', 'Pour votre sécurité, puis-je voir une pièce d''identité ?', 'For your security, may I see an ID?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_PROB_KEY_0010', 'REC_PROB_KEY', 'Je vous refais une carte immédiatement.', 'I will issue a new card immediately.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_KEY_0011', 'REC_PROB_KEY', 'Je suis bloqué(e) devant ma porte.', 'I''''m locked out of my room.', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_PROB_KEY_0012', 'REC_PROB_KEY', 'Je vais résoudre cela dans les {time} minutes.', 'I will have this resolved within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_KEY_0013', 'REC_PROB_KEY', 'Veuillez accepter nos sincères excuses pour ce désagrément.', 'Please accept our sincere apologies for the inconvenience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_KEY_0014', 'REC_PROB_KEY', 'Merci pour votre patience, nous allons régler cela immédiatement.', 'Thank you for your patience, we will resolve this immediately.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_KEY_0015', 'REC_PROB_KEY', 'C''est la troisième fois que ça arrive.', 'This is the third time it happens.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_KEY_0016', 'REC_PROB_KEY', 'Je n''ai pas mon ID sur moi.', 'I don''''t have my ID with me.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_MISSING_0001', 'REC_PROB_MISSING', 'Bonjour, ravi(e) de vous accueillir.', 'Good afternoon, it''''s a pleasure to welcome you.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_MISSING_0002', 'REC_PROB_MISSING', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_PROB_MISSING_0003', 'REC_PROB_MISSING', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_PROB_MISSING_0004', 'REC_PROB_MISSING', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_PROB_MISSING_0005', 'REC_PROB_MISSING', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_PROB_MISSING_0006', 'REC_PROB_MISSING', 'Je suis désolé(e) d''apprendre cela.', 'I''''m sorry to hear that.', 'Conflit', 'A2', 'STAFF', null),
('REC_REC_PROB_MISSING_0007', 'REC_PROB_MISSING', 'Pouvez-vous décrire l''objet, s''il vous plaît ?', 'Could you describe the item, please?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_PROB_MISSING_0008', 'REC_PROB_MISSING', 'Où l''avez-vous vu pour la dernière fois ?', 'Where did you last see it?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_PROB_MISSING_0009', 'REC_PROB_MISSING', 'Je vais alerter la sécurité et Housekeeping.', 'I will alert security and Housekeeping.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_MISSING_0010', 'REC_PROB_MISSING', 'Nous allons lancer la recherche immédiatement.', 'We will start searching immediately.', 'Service', 'A2', 'STAFF', null),
('REC_REC_PROB_MISSING_0011', 'REC_PROB_MISSING', 'J''ai perdu un objet dans l''hôtel.', 'I lost an item in the hotel.', 'Conflit', 'A2', 'CLIENT', null),
('REC_REC_PROB_MISSING_0012', 'REC_PROB_MISSING', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_MISSING_0013', 'REC_PROB_MISSING', 'Je vais résoudre cela dans les {time} minutes.', 'I will have this resolved within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_PROB_MISSING_0014', 'REC_PROB_MISSING', 'Je vous tiendrai informé(e) dès que nous avons une information.', 'I will keep you informed as soon as we have an update.', 'Service', 'B1', 'STAFF', null),
('REC_REC_PROB_MISSING_0015', 'REC_PROB_MISSING', 'Je pense qu''on me l''a volé.', 'I think it was stolen.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_PROB_MISSING_0016', 'REC_PROB_MISSING', 'C''est urgent, j''en ai besoin aujourd''hui.', 'It''''s urgent, I need it today.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_STANDARD_0001', 'REC_CO_STANDARD', 'Bonjour, bienvenue à l''hôtel.', 'Good afternoon, welcome to the hotel.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_STANDARD_0002', 'REC_CO_STANDARD', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_STANDARD_0003', 'REC_CO_STANDARD', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CO_STANDARD_0004', 'REC_CO_STANDARD', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CO_STANDARD_0005', 'REC_CO_STANDARD', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CO_STANDARD_0006', 'REC_CO_STANDARD', 'Bonjour, souhaitez-vous effectuer votre départ ?', 'Good morning, are you checking out?', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_STANDARD_0007', 'REC_CO_STANDARD', 'Comment s''est passé votre séjour ?', 'How was your stay?', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_STANDARD_0008', 'REC_CO_STANDARD', 'Avez-vous consommé quelque chose du minibar ?', 'Did you have anything from the minibar?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_STANDARD_0009', 'REC_CO_STANDARD', 'Le total est de {amount} {currency}.', 'The total is {amount} {currency}.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CO_STANDARD_0010', 'REC_CO_STANDARD', 'Will that be by card or cash?', 'Will that be by card or cash?', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CO_STANDARD_0011', 'REC_CO_STANDARD', 'Je souhaite faire le check-out, s''il vous plaît.', 'I would like to check out, please.', 'Clôture', 'A2', 'CLIENT', null),
('REC_REC_CO_STANDARD_0012', 'REC_CO_STANDARD', 'Je peux vous envoyer la facture par email si vous le souhaitez.', 'I can email your invoice if you wish.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_CO_STANDARD_0013', 'REC_CO_STANDARD', 'Souhaitez-vous de l''aide avec vos bagages ?', 'Would you like help with your luggage?', 'Service', 'B1', 'STAFF', null),
('REC_REC_CO_STANDARD_0014', 'REC_CO_STANDARD', 'Merci beaucoup. Nous espérons vous accueillir de nouveau.', 'Thank you very much. We hope to welcome you back.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_CO_STANDARD_0015', 'REC_CO_STANDARD', 'Pouvez-vous m''envoyer la facture par email ?', 'Could you email me the invoice?', 'Clôture', 'B1', 'CLIENT', null),
('REC_REC_CO_STANDARD_0016', 'REC_CO_STANDARD', 'Je conteste une ligne sur la facture.', 'I dispute a line on the bill.', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CO_INVOICE_0001', 'REC_CO_INVOICE', 'Bonjour, ravi(e) de vous accueillir.', 'Good afternoon, it''''s a pleasure to welcome you.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_INVOICE_0002', 'REC_CO_INVOICE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_INVOICE_0003', 'REC_CO_INVOICE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CO_INVOICE_0004', 'REC_CO_INVOICE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CO_INVOICE_0005', 'REC_CO_INVOICE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CO_INVOICE_0006', 'REC_CO_INVOICE', 'Souhaitez-vous une seule facture ou des factures séparées ?', 'Would you like one invoice or separate invoices?', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CO_INVOICE_0007', 'REC_CO_INVOICE', 'Je peux séparer l''hébergement et les extras.', 'I can separate accommodation and extras.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CO_INVOICE_0008', 'REC_CO_INVOICE', 'Quel nom doit apparaître sur la facture ?', 'What name should appear on the invoice?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_INVOICE_0009', 'REC_CO_INVOICE', 'Pouvez-vous confirmer l''adresse de facturation ?', 'Could you confirm the billing address?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_INVOICE_0010', 'REC_CO_INVOICE', 'Je prépare cela tout de suite.', 'I will prepare that right away.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_INVOICE_0011', 'REC_CO_INVOICE', 'Je veux deux factures séparées, s''il vous plaît.', 'I need two separate invoices, please.', 'Paiement', 'A2', 'CLIENT', null),
('REC_REC_CO_INVOICE_0012', 'REC_CO_INVOICE', 'Je vais m''en occuper personnellement.', 'I will personally take care of this for you.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_INVOICE_0013', 'REC_CO_INVOICE', 'Je vais résoudre cela dans les {time} minutes.', 'I will have this resolved within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_INVOICE_0014', 'REC_CO_INVOICE', 'Je peux envoyer une copie directement à votre service comptable.', 'I can send a copy directly to your accounting team.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_CO_INVOICE_0015', 'REC_CO_INVOICE', 'Chambre sur carte société, extras sur carte personnelle.', 'Room on the company card, extras on my personal card.', 'Paiement', 'B1', 'CLIENT', null),
('REC_REC_CO_INVOICE_0016', 'REC_CO_INVOICE', 'Je suis pressé(e). Pouvez-vous accélérer ?', 'I''''m in a hurry. Could you speed this up?', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_LATE_0001', 'REC_CO_LATE', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_LATE_0002', 'REC_CO_LATE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_LATE_0003', 'REC_CO_LATE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CO_LATE_0004', 'REC_CO_LATE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CO_LATE_0005', 'REC_CO_LATE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CO_LATE_0006', 'REC_CO_LATE', 'Vous souhaitez un départ tardif, c''est bien cela ?', 'You would like a late check-out, is that correct?', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LATE_0007', 'REC_CO_LATE', 'Je vérifie la disponibilité avec Housekeeping.', 'I will check availability with Housekeeping.', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_LATE_0008', 'REC_CO_LATE', 'Nous pouvons prolonger jusqu''à {time}, sous réserve de disponibilité.', 'We can extend until {time}, subject to availability.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LATE_0009', 'REC_CO_LATE', 'Un supplément de {amount} {currency} peut s''appliquer.', 'An additional fee of {amount} {currency} may apply.', 'Paiement', 'A2', 'STAFF', null),
('REC_REC_CO_LATE_0010', 'REC_CO_LATE', 'Je reviens vers vous dans un instant.', 'I will be right back.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LATE_0011', 'REC_CO_LATE', 'Puis-je garder la chambre jusqu''à {time} ?', 'May I keep the room until {time}?', 'Service', 'A2', 'CLIENT', null),
('REC_REC_CO_LATE_0012', 'REC_CO_LATE', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_LATE_0013', 'REC_CO_LATE', 'Je vais résoudre cela dans les {time} minutes.', 'I will have this resolved within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_LATE_0014', 'REC_CO_LATE', 'Si je dois refuser, je le ferai avec une alternative pour votre confort.', 'If I need to decline, I will offer an alternative for your comfort.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_LATE_0015', 'REC_CO_LATE', 'Je suis client fidèle, pouvez-vous faire une exception ?', 'I''''m a loyal guest, could you make an exception?', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_LATE_0016', 'REC_CO_LATE', 'J''ai un rendez-vous tard, c''est important.', 'I have a late appointment, it''''s important.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_LUGGAGE_0001', 'REC_CO_LUGGAGE', 'Bonjour, ravi(e) de vous accueillir.', 'Good afternoon, it''''s a pleasure to welcome you.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0002', 'REC_CO_LUGGAGE', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0003', 'REC_CO_LUGGAGE', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0004', 'REC_CO_LUGGAGE', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CO_LUGGAGE_0005', 'REC_CO_LUGGAGE', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CO_LUGGAGE_0006', 'REC_CO_LUGGAGE', 'Souhaitez-vous laisser vos bagages avec nous ?', 'Would you like to leave your luggage with us?', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0007', 'REC_CO_LUGGAGE', 'Combien de pièces avez-vous ?', 'How many pieces do you have?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0008', 'REC_CO_LUGGAGE', 'Voici votre ticket de bagagerie.', 'Here is your luggage claim tag.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0009', 'REC_CO_LUGGAGE', 'Vos bagages seront gardés en lieu sûr.', 'Your luggage will be stored securely.', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0010', 'REC_CO_LUGGAGE', 'À quelle heure reviendrez-vous les récupérer ?', 'What time will you come back to collect them?', 'Vérification', 'A2', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0011', 'REC_CO_LUGGAGE', 'Puis-je laisser mes bagages jusqu''à ce soir ?', 'Can I leave my luggage until this evening?', 'Service', 'A2', 'CLIENT', null),
('REC_REC_CO_LUGGAGE_0012', 'REC_CO_LUGGAGE', 'Si vous avez des objets de valeur, je vous conseille de les garder avec vous.', 'If you have valuables, I recommend keeping them with you.', 'Information', 'B1', 'STAFF', null)
on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('REC_REC_CO_LUGGAGE_0013', 'REC_CO_LUGGAGE', 'Je peux organiser un porteur pour vous aider plus tard.', 'I can arrange a bellman to assist you later.', 'Service', 'B1', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0014', 'REC_CO_LUGGAGE', 'Merci. Conservez bien ce ticket, s''il vous plaît.', 'Thank you. Please keep this tag safe.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_CO_LUGGAGE_0015', 'REC_CO_LUGGAGE', 'C''est sûr ? J''ai un ordinateur dans ce sac.', 'Is it safe? I have a laptop in this bag.', 'Information', 'B1', 'CLIENT', null),
('REC_REC_CO_LUGGAGE_0016', 'REC_CO_LUGGAGE', 'J''ai perdu mon ticket. Comment puis-je récupérer mes bagages ?', 'I lost my tag. How can I retrieve my luggage?', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_FEEDBACK_0001', 'REC_CO_FEEDBACK', 'Bonjour, je vous souhaite la bienvenue.', 'Good afternoon, welcome.', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0002', 'REC_CO_FEEDBACK', 'May I have your name, please?', 'May I have your name, please?', 'Accueil', 'A1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0003', 'REC_CO_FEEDBACK', 'One moment, please.', 'One moment, please.', 'Vérification', 'A1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0004', 'REC_CO_FEEDBACK', 'Bonjour, s''il vous plaît.', 'Hello, please.', 'Accueil', 'A1', 'CLIENT', null),
('REC_REC_CO_FEEDBACK_0005', 'REC_CO_FEEDBACK', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('REC_REC_CO_FEEDBACK_0006', 'REC_CO_FEEDBACK', 'Avez-vous passé un bon séjour parmi nous ?', 'Did you have a pleasant stay with us?', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0007', 'REC_CO_FEEDBACK', 'Y a-t-il quelque chose que nous aurions pu améliorer ?', 'Is there anything we could have improved?', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0008', 'REC_CO_FEEDBACK', 'Merci pour votre retour, c''est très utile.', 'Thank you for your feedback, it''''s very helpful.', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0009', 'REC_CO_FEEDBACK', 'Souhaitez-vous que je note votre remarque ?', 'Would you like me to note your comment?', 'Service', 'A2', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0010', 'REC_CO_FEEDBACK', 'Nous espérons vous revoir bientôt.', 'We hope to see you again soon.', 'Clôture', 'A2', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0011', 'REC_CO_FEEDBACK', 'Globalement, c''était bien.', 'Overall, it was good.', 'Clôture', 'A2', 'CLIENT', null),
('REC_REC_CO_FEEDBACK_0012', 'REC_CO_FEEDBACK', 'Je suis désolé(e) d''apprendre cela. Je vais transmettre immédiatement à la direction.', 'I''''m sorry to hear that. I will report this to management immediately.', 'Conflit', 'B1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0013', 'REC_CO_FEEDBACK', 'Merci de nous aider à améliorer notre service.', 'Thank you for helping us improve our service.', 'Clôture', 'B1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0014', 'REC_CO_FEEDBACK', 'Si vous le souhaitez, je peux organiser un suivi par email.', 'If you wish, I can arrange a follow-up by email.', 'Service', 'B1', 'STAFF', null),
('REC_REC_CO_FEEDBACK_0015', 'REC_CO_FEEDBACK', 'J''ai eu un problème de bruit cette nuit.', 'I had a noise issue last night.', 'Conflit', 'B1', 'CLIENT', null),
('REC_REC_CO_FEEDBACK_0016', 'REC_CO_FEEDBACK', 'Je laisserai un avis si vous m''envoyez le lien.', 'I will leave a review if you send me the link.', 'Service', 'B1', 'CLIENT', null)
on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

commit;