import { POSITIONING_SECTION_ORDER } from '@/lib/positioning/config'
import { PositioningProductionPrompt, PositioningQuestion } from '@/lib/positioning/types'

const QUESTION_BANK: PositioningQuestion[] = [
  // ========== READING — 8 items (A1x2, A2x2, B1x2, B2x2) ==========
  {
    id: 'reading-1',
    section: 'reading',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'repondre_demande'],
    prompt: 'A guest note says: "Need two towels in room 214." What should you do?',
    options: [
      { id: 'A', text: 'Send two towels to room 214.' },
      { id: 'B', text: 'Prepare breakfast for room 214.' },
      { id: 'C', text: 'Call airport transport.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-2',
    section: 'reading',
    level: 'A1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'utiliser_vocabulaire_metier'],
    prompt: 'On a breakfast voucher you read: "Continental breakfast, 7:00 to 10:00." What does it mean?',
    options: [
      { id: 'A', text: 'Breakfast is served between 7 AM and 10 AM.' },
      { id: 'B', text: 'Breakfast costs 7 to 10 euros.' },
      { id: 'C', text: 'Breakfast lasts 7 to 10 minutes.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-3',
    section: 'reading',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'verifier_information'],
    prompt: 'Read the message: "Please hold my reservation. My flight lands at 11:30 PM." What does the guest need?',
    options: [
      { id: 'A', text: 'Late check-in support.' },
      { id: 'B', text: 'An early breakfast.' },
      { id: 'C', text: 'A room cancellation.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-4',
    section: 'reading',
    level: 'A2',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'donner_information'],
    prompt: 'A door tag reads: "Do not disturb until 2 PM." What should the floor team do?',
    options: [
      { id: 'A', text: 'Skip the room and come back after 2 PM.' },
      { id: 'B', text: 'Knock and clean immediately.' },
      { id: 'C', text: 'Cancel the cleaning for the day.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-5',
    section: 'reading',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'proposer_solution'],
    prompt: 'An internal memo says: "VIP arrival moved to 14:30. Suite inspection must be completed before briefing." What is the priority?',
    options: [
      { id: 'A', text: 'Inspect the suite before the briefing.' },
      { id: 'B', text: 'Delay the VIP arrival.' },
      { id: 'C', text: 'Move the briefing to another hotel.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-6',
    section: 'reading',
    level: 'B1',
    type: 'mcq',
    metier: 'security',
    competences: ['comprendre_demande', 'gerer_situation_difficile'],
    prompt: 'A staff alert reads: "Suspicious bag left near the lobby couch since 18:40. Inform security and keep guests away." What is the first action?',
    options: [
      { id: 'A', text: 'Notify security and keep guests at a distance.' },
      { id: 'B', text: 'Open the bag to check what is inside.' },
      { id: 'C', text: 'Move the bag to lost and found.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-7',
    section: 'reading',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'A guest email says: "I appreciate the upgrade, but I still need a quiet room because I have an early meeting." What is the main concern?',
    options: [
      { id: 'A', text: 'The guest wants a quieter room.' },
      { id: 'B', text: 'The guest refuses the upgrade.' },
      { id: 'C', text: 'The guest wants late checkout.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-8',
    section: 'reading',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'verifier_information', 'gerer_reclamation'],
    prompt: 'A guest review states: "The food was excellent but service was slow during peak hours, especially with no follow-up after we placed the order." What should the restaurant prioritize improving?',
    options: [
      { id: 'A', text: 'Service responsiveness and order follow-up during busy periods.' },
      { id: 'B', text: 'The quality of the food.' },
      { id: 'C', text: 'The opening hours of the restaurant.' },
    ],
    correctOptionId: 'A',
  },

  // ========== LISTENING — 8 items (incl. 2 phone calls) ==========
  {
    id: 'listening-1',
    section: 'listening',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'orienter_client', 'accueillir_client'],
    prompt: 'Ecoutez et choisissez la meilleure reponse a faire au client.',
    promptAudio: 'Excuse me, where is the breakfast room, please?',
    options: [
      { id: 'A', text: 'It is on the first floor, next to reception.' },
      { id: 'B', text: 'Your room is ready now.' },
      { id: 'C', text: 'I work in housekeeping.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-2',
    section: 'listening',
    level: 'A1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'repondre_demande'],
    prompt: 'Ecoutez et choisissez la bonne action.',
    promptAudio: 'Hello, I would like an extra pillow in room 508, please.',
    options: [
      { id: 'A', text: 'Bring one extra pillow to room 508.' },
      { id: 'B', text: 'Book a taxi to the airport.' },
      { id: 'C', text: 'Prepare the bill immediately.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-3',
    section: 'listening',
    level: 'A2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'donner_information', 'utiliser_vocabulaire_metier'],
    prompt: 'Ecoutez la demande du client et choisissez la meilleure reponse.',
    promptAudio: 'Is it possible to have a table for two near the window for dinner tonight?',
    options: [
      { id: 'A', text: 'Yes of course, what time would you like to come?' },
      { id: 'B', text: 'The pool closes at ten.' },
      { id: 'C', text: 'Sorry, breakfast is finished.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-4',
    section: 'listening',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_appel', 'comprendre_demande', 'verifier_information'],
    prompt: 'Vous etes au telephone. Ecoutez l\'appel et choisissez la meilleure reponse.',
    promptAudio: 'Hello, I am calling to confirm my reservation for tomorrow night under the name Brown.',
    options: [
      { id: 'A', text: 'Of course Mr. Brown, let me check your reservation right now.' },
      { id: 'B', text: 'Reception is closed, please call back later.' },
      { id: 'C', text: 'I do not handle reservations.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-5',
    section: 'listening',
    level: 'B1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'gerer_reclamation', 'proposer_solution'],
    prompt: 'Ecoutez la reclamation du client et choisissez la meilleure reponse.',
    promptAudio: 'My air conditioning is not working and the room is too hot to sleep.',
    options: [
      { id: 'A', text: 'I am sorry. I will send maintenance right away or arrange another room.' },
      { id: 'B', text: 'Breakfast starts at six.' },
      { id: 'C', text: 'The pool is closed this evening.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-6',
    section: 'listening',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_appel', 'reformuler_confirmer', 'maintenir_echange_fluide'],
    prompt: 'Vous etes au telephone avec un client. Ecoutez et choisissez la meilleure reponse.',
    promptAudio: 'Yes hello, I would like to extend my stay by two more nights, until Sunday morning.',
    options: [
      { id: 'A', text: 'So you would like to stay two extra nights, until Sunday. Let me check availability.' },
      { id: 'B', text: 'You want to leave now.' },
      { id: 'C', text: 'We do not have any rooms.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-7',
    section: 'listening',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'gerer_situation_difficile', 'proposer_solution'],
    prompt: 'Ecoutez le client et choisissez la meilleure reponse.',
    promptAudio: 'We have an important client arriving early. Can you make sure the welcome amenities are already in the room?',
    options: [
      { id: 'A', text: 'Of course, I will coordinate with housekeeping so the room is ready before arrival.' },
      { id: 'B', text: 'Please tell the guest to come back later.' },
      { id: 'C', text: 'We cannot prepare the room.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-8',
    section: 'listening',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['gerer_situation_difficile', 'dire_non_professionnellement', 'gerer_appel'],
    prompt: 'Ecoutez l\'appel du client et choisissez la meilleure reponse professionnelle.',
    promptAudio: 'I lost my key card and I want you to give me a new one without showing any ID. I am in a hurry.',
    options: [
      { id: 'A', text: 'I understand the urgency, but for your own safety I must verify your identity before issuing a new key.' },
      { id: 'B', text: 'Sure, no problem, I will give it to you right away.' },
      { id: 'C', text: 'Please call the police.' },
    ],
    correctOptionId: 'A',
  },

  // ========== VOCABULARY — 8 items ==========
  {
    id: 'vocabulary-1',
    section: 'vocabulary',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['utiliser_vocabulaire_metier'],
    prompt: 'A guest asks for the "bill". What do they want?',
    options: [
      { id: 'A', text: 'The invoice to pay.' },
      { id: 'B', text: 'A room key.' },
      { id: 'C', text: 'A city map.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-2',
    section: 'vocabulary',
    level: 'A1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['utiliser_vocabulaire_metier', 'accueillir_client'],
    prompt: 'Which sentence welcomes a guest correctly at the restaurant?',
    options: [
      { id: 'A', text: 'Good evening, do you have a reservation?' },
      { id: 'B', text: 'Sit anywhere you want.' },
      { id: 'C', text: 'Hurry up please.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-3',
    section: 'vocabulary',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['reformuler_confirmer', 'verifier_information'],
    prompt: 'Which phrase is best to confirm understanding with a guest?',
    options: [
      { id: 'A', text: 'Just to confirm, you need a taxi for 7 AM tomorrow.' },
      { id: 'B', text: 'I do not know.' },
      { id: 'C', text: 'Wait there.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-4',
    section: 'vocabulary',
    level: 'A2',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['utiliser_vocabulaire_metier', 'donner_information'],
    prompt: 'A guest asks where to leave used towels. What is the most natural reply?',
    options: [
      { id: 'A', text: 'You can leave them on the bathroom floor and we will replace them.' },
      { id: 'B', text: 'Throw them in the corridor.' },
      { id: 'C', text: 'Please bring them to the lobby.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-5',
    section: 'vocabulary',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution'],
    prompt: 'A guest says their room is "not ready yet". What is the most professional reply?',
    options: [
      { id: 'A', text: 'I apologize for the delay. We are finishing the room now.' },
      { id: 'B', text: 'That is not my problem.' },
      { id: 'C', text: 'Please clean it yourself.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-6',
    section: 'vocabulary',
    level: 'B1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['conclure_interaction', 'utiliser_vocabulaire_metier'],
    prompt: 'How do you politely close an interaction with a guest leaving the restaurant?',
    options: [
      { id: 'A', text: 'Thank you for dining with us, have a lovely evening.' },
      { id: 'B', text: 'Bye.' },
      { id: 'C', text: 'Next.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-7',
    section: 'vocabulary',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'Which answer best handles a complaint about noise during the night?',
    options: [
      { id: 'A', text: 'I am very sorry. I will contact security and follow up with you immediately.' },
      { id: 'B', text: 'Noise is normal in hotels.' },
      { id: 'C', text: 'Please call tomorrow.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-8',
    section: 'vocabulary',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['dire_non_professionnellement', 'gerer_situation_difficile'],
    prompt: 'A guest insists on entering a restricted staff area. Which reply is the most professional?',
    options: [
      { id: 'A', text: 'I am sorry, this area is reserved for staff only. Let me guide you back to the lobby.' },
      { id: 'B', text: 'You cannot go there, it is forbidden.' },
      { id: 'C', text: 'OK, go ahead.' },
    ],
    correctOptionId: 'A',
  },

  // ========== SITUATIONS — 8 items (mini-cas) ==========
  {
    id: 'situations-1',
    section: 'situations',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['accueillir_client', 'orienter_client'],
    prompt: 'A guest enters the lobby with luggage. What is the most appropriate first sentence?',
    options: [
      { id: 'A', text: 'Good morning, welcome. Are you checking in?' },
      { id: 'B', text: 'Wait there please.' },
      { id: 'C', text: 'What do you want?' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-2',
    section: 'situations',
    level: 'A2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['verifier_information', 'reformuler_confirmer'],
    prompt: 'A guest orders "the fish without sauce, and a sparkling water". You want to confirm. What do you say?',
    options: [
      { id: 'A', text: 'So that is one fish without sauce and one sparkling water, correct?' },
      { id: 'B', text: 'OK got it.' },
      { id: 'C', text: 'We do not serve fish.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-3',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['gerer_reclamation', 'proposer_solution'],
    prompt: 'A guest complains the bathroom was not properly cleaned. What do you do first?',
    options: [
      { id: 'A', text: 'Apologize and offer to send housekeeping back to fix it immediately.' },
      { id: 'B', text: 'Tell the guest to wait until tomorrow.' },
      { id: 'C', text: 'Ask the guest to clean it himself.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-4',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['dire_non_professionnellement', 'proposer_solution'],
    prompt: 'A guest asks for an early check-in at 9 AM but the room is not ready. What is the best reply?',
    options: [
      { id: 'A', text: 'I am sorry, the room will be ready at 2 PM. Would you like to leave your luggage with us?' },
      { id: 'B', text: 'No, you cannot.' },
      { id: 'C', text: 'Just go to your room anyway.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-5',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['gerer_situation_difficile', 'maintenir_echange_fluide'],
    prompt: 'A guest does not understand the menu in English. What do you do?',
    options: [
      { id: 'A', text: 'Stay calm, point at the dish, and explain it slowly with simple words.' },
      { id: 'B', text: 'Tell the guest to come back another day.' },
      { id: 'C', text: 'Ignore the guest and serve someone else.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-6',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['gerer_situation_difficile', 'dire_non_professionnellement', 'gerer_appel'],
    prompt: 'A late guest at the lobby is shouting and disturbing other clients. What is the most professional approach?',
    options: [
      { id: 'A', text: 'Approach calmly, listen, lower the tone, and offer a private space to discuss the issue.' },
      { id: 'B', text: 'Shout back to make him stop.' },
      { id: 'C', text: 'Ignore and walk away.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-7',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['conclure_interaction', 'maintenir_echange_fluide'],
    prompt: 'A guest is checking out. After settling the bill, what is the best closing line?',
    options: [
      { id: 'A', text: 'Thank you for staying with us, Mr. Khan. Have a safe trip and we hope to see you again soon.' },
      { id: 'B', text: 'OK bye.' },
      { id: 'C', text: 'Please leave the key.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-8',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['gerer_reclamation', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'A guest at the restaurant says the steak is overcooked. What is the best response?',
    options: [
      { id: 'A', text: 'I am very sorry, may I take it back to the kitchen and bring you another one cooked to your liking?' },
      { id: 'B', text: 'That is how we cook it here.' },
      { id: 'C', text: 'You should have asked differently.' },
    ],
    correctOptionId: 'A',
  },
]

const PRODUCTION_BANK: PositioningProductionPrompt[] = [
  {
    id: 'writing-1',
    kind: 'writing',
    level: 'A2',
    metier: 'reception',
    competences: ['repondre_demande', 'donner_information', 'utiliser_vocabulaire_metier'],
    context: 'A guest sends you a short message at the reception desk:',
    task: 'Reply in English (3 to 5 sentences) to this guest message: "Hi, I arrive tomorrow at 10 PM. Can I still check in? Will dinner be available?"',
    guidance: 'Be polite, confirm the late check-in, and give clear information about dinner.',
  },
  {
    id: 'writing-2',
    kind: 'writing',
    level: 'B1',
    metier: 'housekeeping',
    competences: ['gerer_reclamation', 'proposer_solution', 'reformuler_confirmer'],
    context: 'A guest leaves a note about a problem in the room:',
    task: 'Write a short professional reply in English (4 to 6 sentences) to this note: "There was no hot water this morning and the room felt cold. I had to take a cold shower before my meeting."',
    guidance: 'Apologize, propose a concrete solution, and reassure the guest about the next steps.',
  },
  {
    id: 'speaking-1',
    kind: 'speaking',
    level: 'A2',
    metier: 'restaurant',
    competences: ['accueillir_client', 'utiliser_vocabulaire_metier', 'maintenir_echange_fluide'],
    context: 'You are at the restaurant. A couple arrives for dinner.',
    task: 'Speak in English for 30 to 45 seconds to welcome them, ask if they have a reservation, and propose a table.',
    guidance: 'Stay friendly, use simple sentences, and finish with a polite closing line.',
  },
  {
    id: 'speaking-2',
    kind: 'speaking',
    level: 'B1',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution', 'gerer_appel', 'conclure_interaction'],
    context: 'You answer a phone call. A guest is upset because the Wi-Fi has not been working for an hour.',
    task: 'Speak in English for 45 to 60 seconds to answer the call, apologize, propose at least one concrete solution, and close the call professionally.',
    guidance: 'Stay calm, acknowledge the problem, take ownership, and finish with a clear next step.',
  },
]

export function getPositioningQuestions() {
  return POSITIONING_SECTION_ORDER.flatMap((section) =>
    QUESTION_BANK.filter((question) => question.section === section),
  )
}

export function getPositioningQuestionById(questionId: string) {
  return QUESTION_BANK.find((question) => question.id === questionId) ?? null
}

export function getPositioningProductions() {
  return PRODUCTION_BANK
}

export function getPositioningProductionById(promptId: string) {
  return PRODUCTION_BANK.find((prompt) => prompt.id === promptId) ?? null
}
