import { POSITIONING_SECTION_ORDER } from '@/lib/positioning/config'
import { PositioningProductionPrompt, PositioningQuestion } from '@/lib/positioning/types'

const QUESTION_BANK: PositioningQuestion[] = [
  // ========== READING — 8 items (A1x2, A2x2, B1x2, B2x2) ==========
  {
    id: 'reading-1',
    section: 'reading',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'repondre_demande'],
    prompt: 'A guest note says: "Need two towels in room 214." What should you do?',
    options: [
      { id: 'A', text: 'Send two towels to room 214.' },
      { id: 'B', text: 'Send one towel to room 214 and wait for confirmation.' },
      { id: 'C', text: 'Bring two pillows to room 214.' },
      { id: 'D', text: 'Deliver two towels to room 412.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-2',
    section: 'reading',
    level: 'A1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'utiliser_vocabulaire_metier'],
    prompt: 'On a breakfast voucher you read: "Continental breakfast, 7:00 to 10:00." What does it mean?',
    options: [
      { id: 'A', text: 'Breakfast is served between 7 AM and 10 AM.' },
      { id: 'B', text: 'Breakfast is served from 7 PM to 10 PM.' },
      { id: 'C', text: 'Breakfast costs between 7 and 10 euros.' },
      { id: 'D', text: 'Breakfast lasts a maximum of 10 minutes.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-3',
    section: 'reading',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'verifier_information'],
    prompt: 'Read the message: "Please hold my reservation. My flight lands at 11:30 PM." What does the guest need?',
    options: [
      { id: 'A', text: 'A guaranteed late check-in around 11:30 PM.' },
      { id: 'B', text: 'A wake-up call before the flight.' },
      { id: 'C', text: 'An early breakfast at 11:30 PM.' },
      { id: 'D', text: 'A free room upgrade for arriving late.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-4',
    section: 'reading',
    level: 'A2',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'donner_information'],
    prompt: 'A door tag reads: "Do not disturb until 2 PM." What should the floor team do?',
    options: [
      { id: 'A', text: 'Skip the room and come back after 2 PM.' },
      { id: 'B', text: 'Knock gently and ask if cleaning is wanted.' },
      { id: 'C', text: 'Slide a note under the door to confirm.' },
      { id: 'D', text: 'Cancel the cleaning of this room for today.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-5',
    section: 'reading',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'proposer_solution'],
    prompt: 'An internal memo says: "VIP arrival moved to 14:30. Suite inspection must be completed before briefing." What is the priority?',
    options: [
      { id: 'A', text: 'Inspect the suite before the staff briefing.' },
      { id: 'B', text: 'Schedule the briefing at the same time as the inspection.' },
      { id: 'C', text: 'Welcome the VIP first, then inspect afterwards.' },
      { id: 'D', text: 'Postpone the suite inspection until after check-in.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-6',
    section: 'reading',
    level: 'B1',
    type: 'mcq',
    metier: 'security',
    competences: ['comprendre_demande', 'gerer_situation_difficile'],
    prompt: 'A staff alert reads: "Suspicious bag left near the lobby couch since 18:40. Inform security and keep guests away." What is the first action?',
    options: [
      { id: 'A', text: 'Notify security immediately and keep guests at a distance.' },
      { id: 'B', text: 'Open the bag carefully to identify the owner.' },
      { id: 'C', text: 'Move the bag to the lost and found area.' },
      { id: 'D', text: 'Wait a few minutes to see if the owner comes back.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-7',
    section: 'reading',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'A guest email says: "I appreciate the upgrade, but I still need a quiet room because I have an early meeting." What is the main concern?',
    options: [
      { id: 'A', text: 'The guest values quietness more than the upgrade.' },
      { id: 'B', text: 'The guest wants to refuse the upgrade entirely.' },
      { id: 'C', text: 'The guest wants a late checkout after the meeting.' },
      { id: 'D', text: 'The guest is asking for a free meeting room.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'reading-8',
    section: 'reading',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'verifier_information', 'gerer_reclamation'],
    prompt: 'A guest review states: "The food was excellent but service was slow during peak hours, especially with no follow-up after we placed the order." What should the restaurant prioritize improving?',
    options: [
      { id: 'A', text: 'Service responsiveness and order follow-up at peak times.' },
      { id: 'B', text: 'Reviewing the recipes and the quality of the dishes.' },
      { id: 'C', text: 'Extending the opening hours of the restaurant.' },
      { id: 'D', text: 'Reducing the size of the menu to speed up cooking.' },
    ],
    correctOptionId: 'A',
  },

  // ========== LISTENING — 8 items (incl. 2 phone calls) ==========
  {
    id: 'listening-1',
    section: 'listening',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['comprendre_demande', 'orienter_client', 'accueillir_client'],
    prompt: 'Ecoutez et choisissez la meilleure reponse a faire au client.',
    promptAudio: 'Excuse me, where is the breakfast room, please?',
    options: [
      { id: 'A', text: 'It is on the first floor, next to the reception desk.' },
      { id: 'B', text: 'Breakfast is included in your room rate.' },
      { id: 'C', text: 'The restaurant takes reservations online only.' },
      { id: 'D', text: 'Sorry, I am not in charge of breakfast.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-2',
    section: 'listening',
    level: 'A1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'repondre_demande'],
    prompt: 'Ecoutez et choisissez la bonne action.',
    promptAudio: 'Hello, I would like an extra pillow in room 508, please.',
    options: [
      { id: 'A', text: 'Bring one extra pillow to room 508.' },
      { id: 'B', text: 'Bring a new blanket to room 508.' },
      { id: 'C', text: 'Replace all the pillows in room 508.' },
      { id: 'D', text: 'Send the extra pillow to room 805.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-3',
    section: 'listening',
    level: 'A2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'donner_information', 'utiliser_vocabulaire_metier'],
    prompt: 'Ecoutez la demande du client et choisissez la meilleure reponse.',
    promptAudio: 'Is it possible to have a table for two near the window for dinner tonight?',
    options: [
      { id: 'A', text: 'Of course, what time would you like to come?' },
      { id: 'B', text: 'The window tables are only for breakfast service.' },
      { id: 'C', text: 'You can sit anywhere when you arrive.' },
      { id: 'D', text: 'Sorry, dinner is fully booked for the next month.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-4',
    section: 'listening',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_appel', 'comprendre_demande', 'verifier_information'],
    prompt: 'Vous etes au telephone. Ecoutez l\'appel et choisissez la meilleure reponse.',
    promptAudio: 'Hello, I am calling to confirm my reservation for tomorrow night under the name Brown.',
    options: [
      { id: 'A', text: 'Of course Mr. Brown, let me check your reservation right now.' },
      { id: 'B', text: 'I can confirm but I cannot give any details.' },
      { id: 'C', text: 'Please call back during office hours to confirm.' },
      { id: 'D', text: 'Reservations are only confirmed by email, not by phone.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-5',
    section: 'listening',
    level: 'B1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['comprendre_demande', 'gerer_reclamation', 'proposer_solution'],
    prompt: 'Ecoutez la reclamation du client et choisissez la meilleure reponse.',
    promptAudio: 'My air conditioning is not working and the room is too hot to sleep.',
    options: [
      { id: 'A', text: 'I am sorry. I will send maintenance now or arrange another room.' },
      { id: 'B', text: 'You can open the window to get some fresh air tonight.' },
      { id: 'C', text: 'Maintenance will check the unit tomorrow morning.' },
      { id: 'D', text: 'The air conditioning is centrally controlled, nothing to do.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-6',
    section: 'listening',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_appel', 'reformuler_confirmer', 'maintenir_echange_fluide'],
    prompt: 'Vous etes au telephone avec un client. Ecoutez et choisissez la meilleure reponse.',
    promptAudio: 'Yes hello, I would like to extend my stay by two more nights, until Sunday morning.',
    options: [
      { id: 'A', text: 'So two extra nights until Sunday. Let me check availability.' },
      { id: 'B', text: 'Yes of course, I will extend it for one more night.' },
      { id: 'C', text: 'You will need to fill in a new reservation form.' },
      { id: 'D', text: 'Extensions are decided by the manager, please wait.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-7',
    section: 'listening',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['comprendre_demande', 'gerer_situation_difficile', 'proposer_solution'],
    prompt: 'Ecoutez le client et choisissez la meilleure reponse.',
    promptAudio: 'We have an important client arriving early. Can you make sure the welcome amenities are already in the room?',
    options: [
      { id: 'A', text: 'Of course, I will coordinate with housekeeping so the room is ready.' },
      { id: 'B', text: 'Welcome amenities are usually placed during the afternoon shift.' },
      { id: 'C', text: 'I can give the amenities to your client at the reception.' },
      { id: 'D', text: 'I will note the request and pass it on tomorrow morning.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'listening-8',
    section: 'listening',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['gerer_situation_difficile', 'dire_non_professionnellement', 'gerer_appel'],
    prompt: 'Ecoutez l\'appel du client et choisissez la meilleure reponse professionnelle.',
    promptAudio: 'I lost my key card and I want you to give me a new one without showing any ID. I am in a hurry.',
    options: [
      { id: 'A', text: 'I understand the urgency, but I must verify your identity first.' },
      { id: 'B', text: 'No problem, I will issue a new card right away to save time.' },
      { id: 'C', text: 'Please come back later when a manager is available.' },
      { id: 'D', text: 'You will need to pay a fee before I can help you.' },
    ],
    correctOptionId: 'A',
  },

  // ========== VOCABULARY — 8 items ==========
  {
    id: 'vocabulary-1',
    section: 'vocabulary',
    level: 'A1',
    type: 'mcq',
    metier: 'reception',
    competences: ['utiliser_vocabulaire_metier'],
    prompt: 'A guest asks for the "bill". What do they want?',
    options: [
      { id: 'A', text: 'The invoice they have to pay.' },
      { id: 'B', text: 'A receipt from a previous stay.' },
      { id: 'C', text: 'The price list of the rooms.' },
      { id: 'D', text: 'A small note with the room number.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-2',
    section: 'vocabulary',
    level: 'A1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['utiliser_vocabulaire_metier', 'accueillir_client'],
    prompt: 'Which sentence welcomes a guest correctly at the restaurant?',
    options: [
      { id: 'A', text: 'Good evening, do you have a reservation with us?' },
      { id: 'B', text: 'Hi, just sit at any free table you like.' },
      { id: 'C', text: 'Hello, the menu is on the table, take a look.' },
      { id: 'D', text: 'Welcome, please wait there, I will come back.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-3',
    section: 'vocabulary',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['reformuler_confirmer', 'verifier_information'],
    prompt: 'Which phrase is best to confirm understanding with a guest?',
    options: [
      { id: 'A', text: 'Just to confirm, you need a taxi for 7 AM tomorrow.' },
      { id: 'B', text: 'OK, I will try to organise a taxi for you.' },
      { id: 'C', text: 'A taxi tomorrow, no problem at all.' },
      { id: 'D', text: 'I think I understand, leave it with me.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-4',
    section: 'vocabulary',
    level: 'A2',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['utiliser_vocabulaire_metier', 'donner_information'],
    prompt: 'A guest asks where to leave used towels. What is the most natural reply?',
    options: [
      { id: 'A', text: 'You can leave them on the bathroom floor and we will replace them.' },
      { id: 'B', text: 'Just leave them on the bed, we will collect them later.' },
      { id: 'C', text: 'Please hang them back on the rack after use.' },
      { id: 'D', text: 'You can drop them at reception when you go out.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-5',
    section: 'vocabulary',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution'],
    prompt: 'A guest says their room is "not ready yet". What is the most professional reply?',
    options: [
      { id: 'A', text: 'I apologize for the delay. We are finishing the room now.' },
      { id: 'B', text: 'The room is being cleaned, you have to wait a bit.' },
      { id: 'C', text: 'Check-in is at 2 PM, please come back later.' },
      { id: 'D', text: 'Housekeeping is slow today, I cannot do anything.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-6',
    section: 'vocabulary',
    level: 'B1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['conclure_interaction', 'utiliser_vocabulaire_metier'],
    prompt: 'How do you politely close an interaction with a guest leaving the restaurant?',
    options: [
      { id: 'A', text: 'Thank you for dining with us, have a lovely evening.' },
      { id: 'B', text: 'Thanks, see you next time at the restaurant.' },
      { id: 'C', text: 'Goodbye, do not forget your belongings.' },
      { id: 'D', text: 'OK, the bill has been paid, you can go.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-7',
    section: 'vocabulary',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'Which answer best handles a complaint about noise during the night?',
    options: [
      { id: 'A', text: 'I am sorry. I will contact security and follow up with you.' },
      { id: 'B', text: 'I will note the complaint and a manager will call back tomorrow.' },
      { id: 'C', text: 'Some noise is unfortunately normal in a city hotel.' },
      { id: 'D', text: 'I can offer you ear plugs if it helps you sleep.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'vocabulary-8',
    section: 'vocabulary',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['dire_non_professionnellement', 'gerer_situation_difficile'],
    prompt: 'A guest insists on entering a restricted staff area. Which reply is the most professional?',
    options: [
      { id: 'A', text: 'I am sorry, this area is staff only. Let me guide you back.' },
      { id: 'B', text: 'You really cannot go there, it is forbidden for guests.' },
      { id: 'C', text: 'OK, but please be quick, I should not let you in.' },
      { id: 'D', text: 'I will ask my manager whether you can have access.' },
    ],
    correctOptionId: 'A',
  },

  // ========== SITUATIONS — 8 items (mini-cas) ==========
  {
    id: 'situations-1',
    section: 'situations',
    level: 'A2',
    type: 'mcq',
    metier: 'reception',
    competences: ['accueillir_client', 'orienter_client'],
    prompt: 'A guest enters the lobby with luggage. What is the most appropriate first sentence?',
    options: [
      { id: 'A', text: 'Good morning, welcome. Are you checking in with us today?' },
      { id: 'B', text: 'Hello, do you have your reservation number ready?' },
      { id: 'C', text: 'Hi, please leave your bags here and wait a moment.' },
      { id: 'D', text: 'Good morning, the bellboy will be with you shortly.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-2',
    section: 'situations',
    level: 'A2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['verifier_information', 'reformuler_confirmer'],
    prompt: 'A guest orders "the fish without sauce, and a sparkling water". You want to confirm. What do you say?',
    options: [
      { id: 'A', text: 'So that is one fish without sauce and one sparkling water, correct?' },
      { id: 'B', text: 'Got it, one fish and one water, I will be back.' },
      { id: 'C', text: 'No problem, I write that on the order now.' },
      { id: 'D', text: 'Fine, would you like still water instead of sparkling?' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-3',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'housekeeping',
    competences: ['gerer_reclamation', 'proposer_solution'],
    prompt: 'A guest complains the bathroom was not properly cleaned. What do you do first?',
    options: [
      { id: 'A', text: 'Apologize and send housekeeping back to fix it immediately.' },
      { id: 'B', text: 'Apologize and offer a discount on the bill at checkout.' },
      { id: 'C', text: 'Note the complaint and send a supervisor to inspect later.' },
      { id: 'D', text: 'Suggest the guest moves to another room while we clean.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-4',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'reception',
    competences: ['dire_non_professionnellement', 'proposer_solution'],
    prompt: 'A guest asks for an early check-in at 9 AM but the room is not ready. What is the best reply?',
    options: [
      { id: 'A', text: 'I am sorry, the room is ready at 2 PM. May I keep your luggage?' },
      { id: 'B', text: 'Sorry, early check-in is not allowed under any condition.' },
      { id: 'C', text: 'I will try, but I cannot promise anything before noon.' },
      { id: 'D', text: 'You can wait in the lobby until your room is ready.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-5',
    section: 'situations',
    level: 'B1',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['gerer_situation_difficile', 'maintenir_echange_fluide'],
    prompt: 'A guest does not understand the menu in English. What do you do?',
    options: [
      { id: 'A', text: 'Stay calm, point at each dish and explain it slowly.' },
      { id: 'B', text: 'Bring a translated paper menu and let the guest read alone.' },
      { id: 'C', text: 'Recommend the chef\'s special so the guest does not have to choose.' },
      { id: 'D', text: 'Ask another guest at the next table to translate.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-6',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'security',
    competences: ['gerer_situation_difficile', 'dire_non_professionnellement', 'gerer_appel'],
    prompt: 'A late guest at the lobby is shouting and disturbing other clients. What is the most professional approach?',
    options: [
      { id: 'A', text: 'Approach calmly, lower the tone, offer a private space to talk.' },
      { id: 'B', text: 'Politely but firmly ask the guest to lower their voice.' },
      { id: 'C', text: 'Call security straight away to handle the situation.' },
      { id: 'D', text: 'Apologize to the other guests and offer them a free drink.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-7',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'reception',
    competences: ['conclure_interaction', 'maintenir_echange_fluide'],
    prompt: 'A guest is checking out. After settling the bill, what is the best closing line?',
    options: [
      { id: 'A', text: 'Thank you for staying with us. Have a safe trip and see you soon.' },
      { id: 'B', text: 'Thank you, here is your invoice, have a good day.' },
      { id: 'C', text: 'All settled, please leave the key card on the desk.' },
      { id: 'D', text: 'Goodbye, do not forget to leave a review online.' },
    ],
    correctOptionId: 'A',
  },
  {
    id: 'situations-8',
    section: 'situations',
    level: 'B2',
    type: 'mcq',
    metier: 'restaurant',
    competences: ['gerer_reclamation', 'proposer_solution', 'maintenir_echange_fluide'],
    prompt: 'A guest at the restaurant says the steak is overcooked. What is the best response?',
    options: [
      { id: 'A', text: 'I am very sorry, may I bring you another one cooked to your liking?' },
      { id: 'B', text: 'I am sorry, would you like a different dish from the menu?' },
      { id: 'C', text: 'I will tell the chef, he will be more careful next time.' },
      { id: 'D', text: 'I can offer you a free dessert to make up for it.' },
    ],
    correctOptionId: 'A',
  },
]

const PRODUCTION_BANK: PositioningProductionPrompt[] = [
  {
    id: 'writing-1',
    kind: 'writing',
    level: 'A2',
    metier: 'reception',
    competences: ['repondre_demande', 'donner_information', 'utiliser_vocabulaire_metier'],
    context: 'A guest sends you a short message at the reception desk:',
    task: 'Reply in English (3 to 5 sentences) to this guest message: "Hi, I arrive tomorrow at 10 PM. Can I still check in? Will dinner be available?"',
    guidance: 'Be polite, confirm the late check-in, and give clear information about dinner.',
  },
  {
    id: 'writing-2',
    kind: 'writing',
    level: 'B1',
    metier: 'housekeeping',
    competences: ['gerer_reclamation', 'proposer_solution', 'reformuler_confirmer'],
    context: 'A guest leaves a note about a problem in the room:',
    task: 'Write a short professional reply in English (4 to 6 sentences) to this note: "There was no hot water this morning and the room felt cold. I had to take a cold shower before my meeting."',
    guidance: 'Apologize, propose a concrete solution, and reassure the guest about the next steps.',
  },
  {
    id: 'writing-3',
    kind: 'writing',
    level: 'A2',
    metier: 'reception',
    competences: ['orienter_client', 'donner_information', 'utiliser_vocabulaire_metier'],
    context: 'A guest at the reception asks you how to reach the airport and what time breakfast and check-out are.',
    task: 'Write a short professional reply in English (3 to 5 sentences) giving clear directions to the airport (taxi or shuttle), the breakfast hours, and the check-out time.',
    guidance: 'Give a clear orientation. Use simple, structured English. Be precise on times.',
  },
  {
    id: 'writing-4',
    kind: 'writing',
    level: 'B1',
    metier: 'reception',
    competences: ['dire_non_professionnellement', 'proposer_solution', 'maintenir_echange_fluide'],
    context: 'A guest asks for something you cannot provide:',
    task: 'Write a polite professional reply in English (4 to 6 sentences) to this request: "Can I keep my room until 6 PM today for free? My flight is late."',
    guidance: 'Refuse politely, explain the policy, and propose a realistic alternative (paid late check-out, luggage storage, day-use lounge).',
  },
  {
    id: 'speaking-1',
    kind: 'speaking',
    level: 'A2',
    metier: 'restaurant',
    competences: ['accueillir_client', 'utiliser_vocabulaire_metier', 'maintenir_echange_fluide'],
    context: 'You are at the restaurant. A couple arrives for dinner.',
    task: 'Speak in English for 30 to 45 seconds to welcome them, ask if they have a reservation, and propose a table.',
    guidance: 'Stay friendly, use simple sentences, and finish with a polite closing line.',
  },
  {
    id: 'speaking-2',
    kind: 'speaking',
    level: 'B1',
    metier: 'reception',
    competences: ['gerer_reclamation', 'proposer_solution', 'gerer_appel', 'conclure_interaction'],
    context: 'You answer a phone call. A guest is upset because the Wi-Fi has not been working for an hour.',
    task: 'Speak in English for 45 to 60 seconds to answer the call, apologize, propose at least one concrete solution, and close the call professionally.',
    guidance: 'Stay calm, acknowledge the problem, take ownership, and finish with a clear next step.',
  },
]

export function getPositioningQuestions() {
  return POSITIONING_SECTION_ORDER.flatMap((section) =>
    QUESTION_BANK.filter((question) => question.section === section),
  )
}

export function getPositioningQuestionById(questionId: string) {
  return QUESTION_BANK.find((question) => question.id === questionId) ?? null
}

export function getPositioningProductions() {
  return PRODUCTION_BANK
}

export function getPositioningProductionById(promptId: string) {
  return PRODUCTION_BANK.find((prompt) => prompt.id === promptId) ?? null
}
