// ═══════════════════════════════════════════════════════════════
// DONNÉES - Version compacte
// ═══════════════════════════════════════════════════════════════

import { Phrase, Skill, Scenario, TestQuestion, Role } from './types';
type TestType = 'INITIAL' | 'FINAL' | 'BOTH';

// ─────────────────────────────────────────────────────────────────
// SKILLS (15 par métier = 60 total)
// ─────────────────────────────────────────────────────────────────

const skillsDef: [string, Role, string, string, string, number][] = [
  // RECEPTION
  ['REC_SKILL_01', 'RECEPTION', 'Accueillir un client', 'Saluer et accueillir', 'INTERACTION', 1],
  ['REC_SKILL_02', 'RECEPTION', 'Vérifier réservation', 'Confirmer les détails', 'COMPREHENSION', 2],
  ['REC_SKILL_03', 'RECEPTION', 'Gérer check-in', 'Processus complet', 'INTERACTION', 3],
  ['REC_SKILL_04', 'RECEPTION', 'Informations pratiques', 'Wi-Fi, petit-déjeuner', 'PRODUCTION', 4],
  ['REC_SKILL_05', 'RECEPTION', 'Comprendre demande orale', 'Écoute client', 'COMPREHENSION', 5],
  ['REC_SKILL_06', 'RECEPTION', 'Répondre poliment', 'Formulations pro', 'PRODUCTION', 6],
  ['REC_SKILL_07', 'RECEPTION', 'Plainte simple', 'Première réponse', 'CONFLICT', 7],
  ['REC_SKILL_08', 'RECEPTION', 'Plainte tendue', 'Client frustré', 'CONFLICT', 8],
  ['REC_SKILL_09', 'RECEPTION', 'Proposer solution', 'Alternatives', 'INTERACTION', 9],
  ['REC_SKILL_10', 'RECEPTION', 'Escalader', 'Appeler manager', 'CONFLICT', 10],
  ['REC_SKILL_11', 'RECEPTION', 'Expliquer facture', 'Détailler charges', 'PRODUCTION', 11],
  ['REC_SKILL_12', 'RECEPTION', 'Gérer check-out', 'Processus départ', 'INTERACTION', 12],
  ['REC_SKILL_13', 'RECEPTION', 'Comprendre accent', 'Adaptation', 'COMPREHENSION', 13],
  ['REC_SKILL_14', 'RECEPTION', 'Expression orale', 'Clarté', 'PRODUCTION', 14],
  ['REC_SKILL_15', 'RECEPTION', 'Calme sous pression', 'Professionnalisme', 'CONFLICT', 15],
  // HOUSEKEEPING
  ['HK_SKILL_01', 'HOUSEKEEPING', 'S\'annoncer', 'Frapper et présenter', 'INTERACTION', 1],
  ['HK_SKILL_02', 'HOUSEKEEPING', 'Demander permission', 'Entrer poliment', 'PRODUCTION', 2],
  ['HK_SKILL_03', 'HOUSEKEEPING', 'Expliquer travail', 'Tâches nettoyage', 'PRODUCTION', 3],
  ['HK_SKILL_04', 'HOUSEKEEPING', 'Comprendre report', 'Come back later', 'COMPREHENSION', 4],
  ['HK_SKILL_05', 'HOUSEKEEPING', 'Proposer horaire', 'Alternative', 'INTERACTION', 5],
  ['HK_SKILL_06', 'HOUSEKEEPING', 'Demande simple', 'Serviettes etc', 'INTERACTION', 6],
  ['HK_SKILL_07', 'HOUSEKEEPING', 'Expliquer manque', 'Non disponible', 'PRODUCTION', 7],
  ['HK_SKILL_08', 'HOUSEKEEPING', 'Signaler panne', 'Reporter problème', 'PRODUCTION', 8],
  ['HK_SKILL_09', 'HOUSEKEEPING', 'Comprendre plainte', 'Écouter', 'COMPREHENSION', 9],
  ['HK_SKILL_10', 'HOUSEKEEPING', 'S\'excuser', 'Excuses pro', 'INTERACTION', 10],
  ['HK_SKILL_11', 'HOUSEKEEPING', 'Contacter réception', 'Communication', 'PRODUCTION', 11],
  ['HK_SKILL_12', 'HOUSEKEEPING', 'Client mécontent', 'Calmer', 'CONFLICT', 12],
  ['HK_SKILL_13', 'HOUSEKEEPING', 'Expliquer retard', 'Justifier', 'PRODUCTION', 13],
  ['HK_SKILL_14', 'HOUSEKEEPING', 'Comprendre instructions', 'De réception', 'COMPREHENSION', 14],
  ['HK_SKILL_15', 'HOUSEKEEPING', 'Garder calme', 'Face impolitesse', 'CONFLICT', 15],
  // RESTAURANT
  ['REST_SKILL_01', 'RESTAURANT', 'Accueillir', 'Saluer entrée', 'INTERACTION', 1],
  ['REST_SKILL_02', 'RESTAURANT', 'Placer client', 'Attribuer table', 'PRODUCTION', 2],
  ['REST_SKILL_03', 'RESTAURANT', 'Présenter menu', 'Expliquer options', 'PRODUCTION', 3],
  ['REST_SKILL_04', 'RESTAURANT', 'Comprendre commande', 'Écouter noter', 'COMPREHENSION', 4],
  ['REST_SKILL_05', 'RESTAURANT', 'Confirmer commande', 'Répéter validation', 'INTERACTION', 5],
  ['REST_SKILL_06', 'RESTAURANT', 'Gérer allergies', 'Précautions', 'INTERACTION', 6],
  ['REST_SKILL_07', 'RESTAURANT', 'Servir plat', 'Présentation', 'PRODUCTION', 7],
  ['REST_SKILL_08', 'RESTAURANT', 'Vérifier satisfaction', 'Tout va bien', 'INTERACTION', 8],
  ['REST_SKILL_09', 'RESTAURANT', 'Plat incorrect', 'Erreur commande', 'CONFLICT', 9],
  ['REST_SKILL_10', 'RESTAURANT', 'Client pressé', 'Service rapide', 'CONFLICT', 10],
  ['REST_SKILL_11', 'RESTAURANT', 'Présenter addition', 'Note', 'PRODUCTION', 11],
  ['REST_SKILL_12', 'RESTAURANT', 'Gérer paiement', 'Encaissement', 'INTERACTION', 12],
  ['REST_SKILL_13', 'RESTAURANT', 'Comprendre accent', 'International', 'COMPREHENSION', 13],
  ['REST_SKILL_14', 'RESTAURANT', 'Conseiller plat', 'Recommandations', 'PRODUCTION', 14],
  ['REST_SKILL_15', 'RESTAURANT', 'Client mécontent', 'Réclamation', 'CONFLICT', 15],
  // SECURITY
  ['SEC_SKILL_01', 'SECURITY', 'Identifier client', 'Identification', 'INTERACTION', 1],
  ['SEC_SKILL_02', 'SECURITY', 'Demander pièce', 'Vérification', 'PRODUCTION', 2],
  ['SEC_SKILL_03', 'SECURITY', 'Expliquer procédure', 'Justifier contrôle', 'PRODUCTION', 3],
  ['SEC_SKILL_04', 'SECURITY', 'Indiquer direction', 'Orienter', 'PRODUCTION', 4],
  ['SEC_SKILL_05', 'SECURITY', 'Comprendre question', 'Écouter demandes', 'COMPREHENSION', 5],
  ['SEC_SKILL_06', 'SECURITY', 'Refuser poliment', 'Courtoisie', 'INTERACTION', 6],
  ['SEC_SKILL_07', 'SECURITY', 'Expliquer règle', 'Règlement', 'PRODUCTION', 7],
  ['SEC_SKILL_08', 'SECURITY', 'Proposer alternative', 'Contournement', 'INTERACTION', 8],
  ['SEC_SKILL_09', 'SECURITY', 'Intervenir calmement', 'Première intervention', 'CONFLICT', 9],
  ['SEC_SKILL_10', 'SECURITY', 'Désamorcer tension', 'Calmer', 'CONFLICT', 10],
  ['SEC_SKILL_11', 'SECURITY', 'Client agressif', 'Confrontation', 'CONFLICT', 11],
  ['SEC_SKILL_12', 'SECURITY', 'Appeler renforts', 'Demander aide', 'PRODUCTION', 12],
  ['SEC_SKILL_13', 'SECURITY', 'Comprendre plainte', 'Écouter', 'COMPREHENSION', 13],
  ['SEC_SKILL_14', 'SECURITY', 'Calme sous pression', 'Sang-froid', 'CONFLICT', 14],
  ['SEC_SKILL_15', 'SECURITY', 'Accompagner réception', 'Escorter', 'INTERACTION', 15],
];

export const SKILLS: Skill[] = skillsDef.map(([id, role, name, desc, dim, order]) => ({
  id, role, name, description: desc, dimension: dim as any, order
}));

// ─────────────────────────────────────────────────────────────────
// PHRASES (80 par métier minimum)
// Format: [id, role, actionId, fr, en, phase, level, skillId, wordCount]
// ─────────────────────────────────────────────────────────────────

const phrasesDef: [string, Role, string, string, string, string, string, string, number][] = [
  // RECEPTION - 80 phrases
  ['REC_01', 'RECEPTION', 'REC_CHECKIN', 'Bonjour, bienvenue à l\'hôtel.', 'Good morning, welcome to the hotel.', 'Accueil', 'A1', 'REC_SKILL_01', 6],
  ['REC_02', 'RECEPTION', 'REC_CHECKIN', 'Bonsoir, bienvenue.', 'Good evening, welcome.', 'Accueil', 'A1', 'REC_SKILL_01', 3],
  ['REC_03', 'RECEPTION', 'REC_CHECKIN', 'Comment puis-je vous aider ?', 'How can I help you?', 'Accueil', 'A1', 'REC_SKILL_01', 5],
  ['REC_04', 'RECEPTION', 'REC_CHECKIN', 'Avez-vous une réservation ?', 'Do you have a reservation?', 'Verification', 'A1', 'REC_SKILL_02', 5],
  ['REC_05', 'RECEPTION', 'REC_CHECKIN', 'À quel nom est la réservation ?', 'What name is the reservation under?', 'Verification', 'A1', 'REC_SKILL_02', 6],
  ['REC_06', 'RECEPTION', 'REC_CHECKIN', 'Pouvez-vous épeler votre nom ?', 'Can you spell your name?', 'Verification', 'A1', 'REC_SKILL_02', 5],
  ['REC_07', 'RECEPTION', 'REC_CHECKIN', 'Laissez-moi vérifier.', 'Let me check.', 'Verification', 'A1', 'REC_SKILL_02', 3],
  ['REC_08', 'RECEPTION', 'REC_CHECKIN', 'Votre passeport, s\'il vous plaît.', 'Your passport, please.', 'Identification', 'A1', 'REC_SKILL_03', 3],
  ['REC_09', 'RECEPTION', 'REC_CHECKIN', 'Puis-je voir une pièce d\'identité ?', 'May I see some ID?', 'Identification', 'A1', 'REC_SKILL_03', 5],
  ['REC_10', 'RECEPTION', 'REC_CHECKIN', 'Voici votre clé. Chambre 302.', 'Here is your key. Room 302.', 'Attribution', 'A1', 'REC_SKILL_03', 6],
  ['REC_11', 'RECEPTION', 'REC_CHECKIN', 'Votre chambre est au troisième étage.', 'Your room is on the third floor.', 'Attribution', 'A1', 'REC_SKILL_03', 7],
  ['REC_12', 'RECEPTION', 'REC_CHECKIN', 'L\'ascenseur est sur votre droite.', 'The elevator is on your right.', 'Info', 'A1', 'REC_SKILL_04', 6],
  ['REC_13', 'RECEPTION', 'REC_CHECKIN', 'Bon séjour !', 'Enjoy your stay!', 'Cloture', 'A1', 'REC_SKILL_06', 3],
  ['REC_14', 'RECEPTION', 'REC_CHECKIN', 'N\'hésitez pas à nous appeler.', 'Please don\'t hesitate to call us.', 'Cloture', 'A2', 'REC_SKILL_06', 6],
  ['REC_15', 'RECEPTION', 'REC_CHECKIN', 'Je ne trouve pas votre réservation.', 'I can\'t find your reservation.', 'Conflit', 'A2', 'REC_SKILL_07', 5],
  ['REC_16', 'RECEPTION', 'REC_CHECKIN', 'Avez-vous un email de confirmation ?', 'Do you have a confirmation email?', 'Conflit', 'A2', 'REC_SKILL_07', 6],
  ['REC_17', 'RECEPTION', 'REC_CHECKIN', 'Je suis désolé pour ce problème.', 'I\'m sorry for this problem.', 'Conflit', 'A2', 'REC_SKILL_07', 5],
  ['REC_18', 'RECEPTION', 'REC_CHECKIN', 'Je comprends votre frustration.', 'I understand your frustration.', 'Conflit', 'A2', 'REC_SKILL_08', 4],
  ['REC_19', 'RECEPTION', 'REC_CHECKIN', 'Laissez-moi trouver une solution.', 'Let me find a solution.', 'Conflit', 'A2', 'REC_SKILL_09', 5],
  ['REC_20', 'RECEPTION', 'REC_CHECKIN', 'Je peux vous proposer une autre chambre.', 'I can offer you another room.', 'Conflit', 'A2', 'REC_SKILL_09', 7],
  ['REC_21', 'RECEPTION', 'REC_INFO', 'Le petit-déjeuner est de 7h à 10h.', 'Breakfast is from 7 to 10.', 'Info', 'A1', 'REC_SKILL_04', 6],
  ['REC_22', 'RECEPTION', 'REC_INFO', 'Le restaurant est au rez-de-chaussée.', 'The restaurant is on the ground floor.', 'Info', 'A1', 'REC_SKILL_04', 7],
  ['REC_23', 'RECEPTION', 'REC_INFO', 'Le mot de passe Wi-Fi est sur la carte.', 'The Wi-Fi password is on the card.', 'Info', 'A1', 'REC_SKILL_04', 8],
  ['REC_24', 'RECEPTION', 'REC_INFO', 'La piscine ferme à 22h.', 'The pool closes at 10 PM.', 'Info', 'A1', 'REC_SKILL_04', 6],
  ['REC_25', 'RECEPTION', 'REC_INFO', 'Le check-out est à 11h.', 'Check-out is at 11 AM.', 'Info', 'A1', 'REC_SKILL_04', 5],
  ['REC_26', 'RECEPTION', 'REC_INFO', 'Nous avons un service de blanchisserie.', 'We have a laundry service.', 'Info', 'A2', 'REC_SKILL_04', 5],
  ['REC_27', 'RECEPTION', 'REC_INFO', 'Le parking est au sous-sol.', 'The parking is in the basement.', 'Info', 'A1', 'REC_SKILL_04', 6],
  ['REC_28', 'RECEPTION', 'REC_INFO', 'Je peux vous appeler un taxi.', 'I can call you a taxi.', 'Service', 'A2', 'REC_SKILL_06', 6],
  ['REC_29', 'RECEPTION', 'REC_INFO', 'Le centre-ville est à 10 minutes.', 'The city center is 10 minutes away.', 'Info', 'A2', 'REC_SKILL_04', 7],
  ['REC_30', 'RECEPTION', 'REC_INFO', 'Avez-vous besoin d\'autre chose ?', 'Do you need anything else?', 'Service', 'A1', 'REC_SKILL_06', 5],
  ['REC_31', 'RECEPTION', 'REC_COMPLAINT', 'Je suis vraiment désolé.', 'I\'m really sorry.', 'Empathie', 'A1', 'REC_SKILL_07', 3],
  ['REC_32', 'RECEPTION', 'REC_COMPLAINT', 'Je comprends parfaitement.', 'I completely understand.', 'Empathie', 'A2', 'REC_SKILL_08', 3],
  ['REC_33', 'RECEPTION', 'REC_COMPLAINT', 'Vous avez tout à fait raison.', 'You\'re absolutely right.', 'Empathie', 'A2', 'REC_SKILL_08', 3],
  ['REC_34', 'RECEPTION', 'REC_COMPLAINT', 'Je vais m\'en occuper immédiatement.', 'I\'ll take care of it immediately.', 'Action', 'A2', 'REC_SKILL_09', 7],
  ['REC_35', 'RECEPTION', 'REC_COMPLAINT', 'Je vais résoudre ce problème.', 'I\'ll solve this problem.', 'Action', 'A2', 'REC_SKILL_09', 4],
  ['REC_36', 'RECEPTION', 'REC_COMPLAINT', 'Que puis-je faire pour vous aider ?', 'What can I do to help you?', 'Solution', 'A2', 'REC_SKILL_09', 7],
  ['REC_37', 'RECEPTION', 'REC_COMPLAINT', 'Je peux vous offrir une compensation.', 'I can offer you compensation.', 'Compensation', 'B1', 'REC_SKILL_09', 5],
  ['REC_38', 'RECEPTION', 'REC_COMPLAINT', 'Je vais appeler mon responsable.', 'I\'ll call my manager.', 'Escalade', 'A2', 'REC_SKILL_10', 4],
  ['REC_39', 'RECEPTION', 'REC_COMPLAINT', 'Le directeur va vous recevoir.', 'The manager will see you.', 'Escalade', 'A2', 'REC_SKILL_10', 5],
  ['REC_40', 'RECEPTION', 'REC_COMPLAINT', 'Un instant, s\'il vous plaît.', 'One moment, please.', 'Escalade', 'A1', 'REC_SKILL_10', 3],
  ['REC_41', 'RECEPTION', 'REC_CHECKOUT', 'Vous souhaitez faire le check-out ?', 'Would you like to check out?', 'Ouverture', 'A1', 'REC_SKILL_12', 6],
  ['REC_42', 'RECEPTION', 'REC_CHECKOUT', 'Quel était votre numéro de chambre ?', 'What was your room number?', 'Verification', 'A1', 'REC_SKILL_12', 5],
  ['REC_43', 'RECEPTION', 'REC_CHECKOUT', 'Comment s\'est passé votre séjour ?', 'How was your stay?', 'Satisfaction', 'A1', 'REC_SKILL_05', 4],
  ['REC_44', 'RECEPTION', 'REC_CHECKOUT', 'Avez-vous utilisé le minibar ?', 'Did you use the minibar?', 'Facturation', 'A1', 'REC_SKILL_11', 5],
  ['REC_45', 'RECEPTION', 'REC_CHECKOUT', 'Voici votre facture.', 'Here is your bill.', 'Facturation', 'A1', 'REC_SKILL_11', 4],
  ['REC_46', 'RECEPTION', 'REC_CHECKOUT', 'Le total est de 250 euros.', 'The total is 250 euros.', 'Facturation', 'A1', 'REC_SKILL_11', 5],
  ['REC_47', 'RECEPTION', 'REC_CHECKOUT', 'Comment souhaitez-vous payer ?', 'How would you like to pay?', 'Paiement', 'A1', 'REC_SKILL_12', 6],
  ['REC_48', 'RECEPTION', 'REC_CHECKOUT', 'Carte ou espèces ?', 'Card or cash?', 'Paiement', 'A1', 'REC_SKILL_12', 3],
  ['REC_49', 'RECEPTION', 'REC_CHECKOUT', 'Merci, au revoir et bon voyage !', 'Thank you, goodbye and safe travels!', 'Cloture', 'A1', 'REC_SKILL_06', 6],
  ['REC_50', 'RECEPTION', 'REC_CHECKOUT', 'Nous espérons vous revoir bientôt.', 'We hope to see you again soon.', 'Cloture', 'A2', 'REC_SKILL_06', 7],
  // Additional RECEPTION phrases to reach 80
  ['REC_51', 'RECEPTION', 'REC_INFO', 'Je vais contacter le service technique.', 'I\'ll contact technical support.', 'Support', 'A2', 'REC_SKILL_09', 4],
  ['REC_52', 'RECEPTION', 'REC_INFO', 'Un technicien va venir rapidement.', 'A technician will come quickly.', 'Support', 'A2', 'REC_SKILL_09', 5],
  ['REC_53', 'RECEPTION', 'REC_CHECKIN', 'Je vérifie les disponibilités.', 'I\'ll check availability.', 'Action', 'A2', 'REC_SKILL_09', 3],
  ['REC_54', 'RECEPTION', 'REC_CHECKIN', 'J\'ai une chambre plus calme.', 'I have a quieter room.', 'Proposition', 'A2', 'REC_SKILL_09', 5],
  ['REC_55', 'RECEPTION', 'REC_CHECKIN', 'Cette chambre a une meilleure vue.', 'This room has a better view.', 'Proposition', 'A2', 'REC_SKILL_09', 6],
  ['REC_56', 'RECEPTION', 'REC_COMPLAINT', 'Je m\'excuse pour le désagrément.', 'I apologize for the inconvenience.', 'Excuse', 'A2', 'REC_SKILL_07', 5],
  ['REC_57', 'RECEPTION', 'REC_COMPLAINT', 'Merci pour votre patience.', 'Thank you for your patience.', 'Cloture', 'A2', 'REC_SKILL_06', 5],
  ['REC_58', 'RECEPTION', 'REC_COMPLAINT', 'Est-ce que cela vous convient ?', 'Does that work for you?', 'Validation', 'A2', 'REC_SKILL_09', 5],
  ['REC_59', 'RECEPTION', 'REC_CHECKOUT', 'Ce montant est incorrect.', 'This amount is incorrect.', 'Conflit', 'A2', 'REC_SKILL_07', 4],
  ['REC_60', 'RECEPTION', 'REC_CHECKOUT', 'Je vais vérifier immédiatement.', 'I\'ll check immediately.', 'Action', 'A2', 'REC_SKILL_09', 3],
  ['REC_61', 'RECEPTION', 'REC_CHECKOUT', 'Vous avez raison, c\'est une erreur.', 'You\'re right, it\'s a mistake.', 'Excuse', 'A2', 'REC_SKILL_08', 5],
  ['REC_62', 'RECEPTION', 'REC_CHECKOUT', 'Je corrige cela tout de suite.', 'I\'ll fix that right away.', 'Action', 'A2', 'REC_SKILL_09', 5],
  ['REC_63', 'RECEPTION', 'REC_CHECKOUT', 'Voici la facture corrigée.', 'Here is the corrected bill.', 'Solution', 'A2', 'REC_SKILL_11', 5],
  ['REC_64', 'RECEPTION', 'REC_INFO', 'Puis-je vous offrir un café ?', 'Can I offer you a coffee?', 'Service', 'A2', 'REC_SKILL_06', 6],
  ['REC_65', 'RECEPTION', 'REC_INFO', 'Y a-t-il autre chose ?', 'Is there anything else?', 'Service', 'A2', 'REC_SKILL_06', 4],
  ['REC_66', 'RECEPTION', 'REC_COMPLAINT', 'Nous allons améliorer cela.', 'We\'ll improve on this.', 'Engagement', 'B1', 'REC_SKILL_15', 4],
  ['REC_67', 'RECEPTION', 'REC_COMPLAINT', 'Nous apprécions vos commentaires.', 'We appreciate your feedback.', 'Cloture', 'B1', 'REC_SKILL_06', 4],
  ['REC_68', 'RECEPTION', 'REC_CHECKIN', 'La climatisation ne fonctionne pas.', 'The air conditioning isn\'t working.', 'Probleme', 'A2', 'REC_SKILL_07', 5],
  ['REC_69', 'RECEPTION', 'REC_CHECKIN', 'La chambre est trop bruyante.', 'The room is too noisy.', 'Probleme', 'A2', 'REC_SKILL_07', 5],
  ['REC_70', 'RECEPTION', 'REC_CHECKIN', 'Il y a un problème avec la salle de bain.', 'There\'s a problem with the bathroom.', 'Probleme', 'A2', 'REC_SKILL_07', 6],
  ['REC_71', 'RECEPTION', 'REC_COMPLAINT', 'Je comprends, c\'est inacceptable.', 'I understand, it\'s unacceptable.', 'Empathie', 'B1', 'REC_SKILL_08', 4],
  ['REC_72', 'RECEPTION', 'REC_CHECKIN', 'Je peux vous surclasser gratuitement.', 'I can upgrade you for free.', 'Compensation', 'B1', 'REC_SKILL_09', 6],
  ['REC_73', 'RECEPTION', 'REC_CHECKIN', 'Le porteur va vous aider.', 'The porter will help you.', 'Service', 'A2', 'REC_SKILL_06', 5],
  ['REC_74', 'RECEPTION', 'REC_CHECKIN', 'Votre nouvelle chambre est la 405.', 'Your new room is 405.', 'Attribution', 'A1', 'REC_SKILL_03', 5],
  ['REC_75', 'RECEPTION', 'REC_CHECKIN', 'Voici votre nouvelle clé.', 'Here is your new key.', 'Attribution', 'A1', 'REC_SKILL_03', 5],
  ['REC_76', 'RECEPTION', 'REC_COMPLAINT', 'Encore désolé pour le désagrément.', 'Again, sorry for the inconvenience.', 'Excuse', 'A2', 'REC_SKILL_07', 5],
  ['REC_77', 'RECEPTION', 'REC_INFO', 'Le Wi-Fi ne fonctionne pas ?', 'The Wi-Fi isn\'t working?', 'Probleme', 'A2', 'REC_SKILL_07', 4],
  ['REC_78', 'RECEPTION', 'REC_COMPLAINT', 'N\'hésitez pas si vous avez d\'autres demandes.', 'Don\'t hesitate if you have other requests.', 'Cloture', 'A2', 'REC_SKILL_06', 7],
  ['REC_79', 'RECEPTION', 'REC_INFO', 'Je vous tiens informé.', 'I\'ll keep you informed.', 'Suivi', 'A2', 'REC_SKILL_09', 4],
  ['REC_80', 'RECEPTION', 'REC_COMPLAINT', 'Le problème est résolu.', 'The problem is fixed.', 'Solution', 'A1', 'REC_SKILL_09', 4],

  // HOUSEKEEPING - 80 phrases
  ['HK_01', 'HOUSEKEEPING', 'HK_ENTRY', 'Service d\'étage !', 'Housekeeping!', 'Annonce', 'A1', 'HK_SKILL_01', 1],
  ['HK_02', 'HOUSEKEEPING', 'HK_ENTRY', 'Bonjour, service de chambre.', 'Hello, room service.', 'Annonce', 'A1', 'HK_SKILL_01', 3],
  ['HK_03', 'HOUSEKEEPING', 'HK_ENTRY', 'Puis-je entrer ?', 'May I come in?', 'Permission', 'A1', 'HK_SKILL_02', 4],
  ['HK_04', 'HOUSEKEEPING', 'HK_ENTRY', 'Je viens nettoyer la chambre.', 'I\'m here to clean the room.', 'Explication', 'A1', 'HK_SKILL_03', 6],
  ['HK_05', 'HOUSEKEEPING', 'HK_ENTRY', 'Voulez-vous que je nettoie maintenant ?', 'Would you like me to clean now?', 'Permission', 'A2', 'HK_SKILL_02', 7],
  ['HK_06', 'HOUSEKEEPING', 'HK_ENTRY', 'D\'accord, je comprends.', 'Okay, I understand.', 'Acceptation', 'A1', 'HK_SKILL_04', 3],
  ['HK_07', 'HOUSEKEEPING', 'HK_ENTRY', 'Je repasserai plus tard.', 'I\'ll come back later.', 'Alternative', 'A1', 'HK_SKILL_05', 4],
  ['HK_08', 'HOUSEKEEPING', 'HK_ENTRY', 'À quelle heure préférez-vous ?', 'What time would you prefer?', 'Alternative', 'A2', 'HK_SKILL_05', 5],
  ['HK_09', 'HOUSEKEEPING', 'HK_ENTRY', 'Je reviendrai à 14h.', 'I\'ll return at 2 PM.', 'Alternative', 'A1', 'HK_SKILL_05', 5],
  ['HK_10', 'HOUSEKEEPING', 'HK_ENTRY', 'Excusez-moi de vous déranger.', 'Sorry to disturb you.', 'Excuse', 'A1', 'HK_SKILL_10', 4],
  ['HK_11', 'HOUSEKEEPING', 'HK_CLEAN', 'Je nettoie la salle de bain.', 'I\'m cleaning the bathroom.', 'Action', 'A1', 'HK_SKILL_03', 4],
  ['HK_12', 'HOUSEKEEPING', 'HK_CLEAN', 'Je fais le lit.', 'I\'m making the bed.', 'Action', 'A1', 'HK_SKILL_03', 4],
  ['HK_13', 'HOUSEKEEPING', 'HK_CLEAN', 'Je passe l\'aspirateur.', 'I\'m vacuuming.', 'Action', 'A1', 'HK_SKILL_03', 2],
  ['HK_14', 'HOUSEKEEPING', 'HK_CLEAN', 'Cela prendra environ 20 minutes.', 'This will take about 20 minutes.', 'Duree', 'A1', 'HK_SKILL_03', 6],
  ['HK_15', 'HOUSEKEEPING', 'HK_CLEAN', 'J\'ai presque fini.', 'I\'m almost done.', 'Duree', 'A1', 'HK_SKILL_03', 3],
  ['HK_16', 'HOUSEKEEPING', 'HK_CLEAN', 'J\'ai changé les serviettes.', 'I\'ve changed the towels.', 'Info', 'A1', 'HK_SKILL_03', 4],
  ['HK_17', 'HOUSEKEEPING', 'HK_CLEAN', 'J\'ai rempli le minibar.', 'I\'ve restocked the minibar.', 'Info', 'A2', 'HK_SKILL_03', 4],
  ['HK_18', 'HOUSEKEEPING', 'HK_CLEAN', 'Voulez-vous des oreillers supplémentaires ?', 'Would you like extra pillows?', 'Proposition', 'A2', 'HK_SKILL_06', 5],
  ['HK_19', 'HOUSEKEEPING', 'HK_CLEAN', 'La chambre est prête.', 'The room is ready.', 'Info', 'A1', 'HK_SKILL_03', 4],
  ['HK_20', 'HOUSEKEEPING', 'HK_CLEAN', 'Y a-t-il autre chose dont vous avez besoin ?', 'Is there anything else you need?', 'Service', 'A2', 'HK_SKILL_06', 6],
  ['HK_21', 'HOUSEKEEPING', 'HK_REQUEST', 'Combien de serviettes voulez-vous ?', 'How many towels would you like?', 'Precision', 'A1', 'HK_SKILL_06', 6],
  ['HK_22', 'HOUSEKEEPING', 'HK_REQUEST', 'Je vous apporte ça tout de suite.', 'I\'ll bring that right away.', 'Service', 'A1', 'HK_SKILL_06', 5],
  ['HK_23', 'HOUSEKEEPING', 'HK_REQUEST', 'Voici vos serviettes supplémentaires.', 'Here are your extra towels.', 'Service', 'A1', 'HK_SKILL_06', 5],
  ['HK_24', 'HOUSEKEEPING', 'HK_REQUEST', 'Je vais chercher une couverture.', 'I\'ll get a blanket.', 'Service', 'A1', 'HK_SKILL_06', 4],
  ['HK_25', 'HOUSEKEEPING', 'HK_REQUEST', 'Un moment, s\'il vous plaît.', 'One moment, please.', 'Confirmation', 'A1', 'HK_SKILL_06', 3],
  ['HK_26', 'HOUSEKEEPING', 'HK_REQUEST', 'Je suis désolé, nous n\'en avons plus.', 'I\'m sorry, we\'re out of those.', 'Refus', 'A2', 'HK_SKILL_07', 6],
  ['HK_27', 'HOUSEKEEPING', 'HK_REQUEST', 'Je peux vous proposer autre chose.', 'I can offer you something else.', 'Alternative', 'A2', 'HK_SKILL_05', 6],
  ['HK_28', 'HOUSEKEEPING', 'HK_REQUEST', 'Je dois vérifier avec la réception.', 'I need to check with reception.', 'Verification', 'A2', 'HK_SKILL_11', 5],
  ['HK_29', 'HOUSEKEEPING', 'HK_REQUEST', 'Cela devrait arriver dans 10 minutes.', 'It should arrive in 10 minutes.', 'Info', 'A2', 'HK_SKILL_03', 6],
  ['HK_30', 'HOUSEKEEPING', 'HK_REQUEST', 'Avez-vous besoin d\'autre chose ?', 'Do you need anything else?', 'Service', 'A1', 'HK_SKILL_06', 5],
  ['HK_31', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je suis vraiment désolé pour cela.', 'I\'m really sorry about that.', 'Excuse', 'A1', 'HK_SKILL_10', 5],
  ['HK_32', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je comprends votre mécontentement.', 'I understand your dissatisfaction.', 'Empathie', 'A2', 'HK_SKILL_09', 4],
  ['HK_33', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je vais corriger cela immédiatement.', 'I\'ll fix that immediately.', 'Action', 'A2', 'HK_SKILL_12', 4],
  ['HK_34', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je reviens nettoyer tout de suite.', 'I\'ll come back to clean right away.', 'Action', 'A2', 'HK_SKILL_12', 7],
  ['HK_35', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Ce n\'est pas acceptable, je suis d\'accord.', 'That\'s not acceptable, I agree.', 'Empathie', 'A2', 'HK_SKILL_09', 5],
  ['HK_36', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je vais prévenir la réception.', 'I\'ll notify the reception.', 'Escalade', 'A2', 'HK_SKILL_11', 4],
  ['HK_37', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Quelqu\'un va venir vous aider.', 'Someone will come to help you.', 'Escalade', 'A2', 'HK_SKILL_11', 6],
  ['HK_38', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je fais de mon mieux.', 'I\'m doing my best.', 'Assurance', 'A2', 'HK_SKILL_15', 4],
  ['HK_39', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Merci de votre patience.', 'Thank you for your patience.', 'Cloture', 'A2', 'HK_SKILL_10', 5],
  ['HK_40', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je m\'excuse pour le retard.', 'I apologize for the delay.', 'Excuse', 'A2', 'HK_SKILL_13', 5],
  ['HK_41', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je vois le problème.', 'I see the problem.', 'Verification', 'A1', 'HK_SKILL_08', 4],
  ['HK_42', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je vais vérifier.', 'I\'ll check.', 'Verification', 'A1', 'HK_SKILL_08', 2],
  ['HK_43', 'HOUSEKEEPING', 'HK_PROBLEM', 'Oui, il y a un problème.', 'Yes, there\'s a problem.', 'Confirmation', 'A1', 'HK_SKILL_08', 4],
  ['HK_44', 'HOUSEKEEPING', 'HK_PROBLEM', 'J\'appelle la maintenance.', 'I\'ll call maintenance.', 'Action', 'A1', 'HK_SKILL_08', 3],
  ['HK_45', 'HOUSEKEEPING', 'HK_PROBLEM', 'Un technicien va venir.', 'A technician will come.', 'Info', 'A1', 'HK_SKILL_08', 4],
  ['HK_46', 'HOUSEKEEPING', 'HK_PROBLEM', 'La climatisation ne fonctionne pas.', 'The air conditioning isn\'t working.', 'Probleme', 'A2', 'HK_SKILL_08', 5],
  ['HK_47', 'HOUSEKEEPING', 'HK_PROBLEM', 'L\'ampoule est grillée.', 'The light bulb is burned out.', 'Probleme', 'A2', 'HK_SKILL_08', 6],
  ['HK_48', 'HOUSEKEEPING', 'HK_PROBLEM', 'L\'eau chaude ne fonctionne pas.', 'The hot water isn\'t working.', 'Probleme', 'A2', 'HK_SKILL_08', 5],
  ['HK_49', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je signale le problème.', 'I\'ll report the problem.', 'Action', 'A2', 'HK_SKILL_08', 4],
  ['HK_50', 'HOUSEKEEPING', 'HK_PROBLEM', 'On va réparer ça rapidement.', 'We\'ll fix that quickly.', 'Solution', 'A2', 'HK_SKILL_08', 4],
  ['HK_51', 'HOUSEKEEPING', 'HK_PROBLEM', 'Pouvez-vous attendre quelques minutes ?', 'Can you wait a few minutes?', 'Attente', 'A2', 'HK_SKILL_05', 6],
  ['HK_52', 'HOUSEKEEPING', 'HK_PROBLEM', 'Le problème est résolu.', 'The problem is fixed.', 'Solution', 'A1', 'HK_SKILL_08', 4],
  ['HK_53', 'HOUSEKEEPING', 'HK_PROBLEM', 'Est-ce que ça fonctionne maintenant ?', 'Is it working now?', 'Suivi', 'A2', 'HK_SKILL_08', 4],
  ['HK_54', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je vous tiens informé.', 'I\'ll keep you informed.', 'Suivi', 'A2', 'HK_SKILL_11', 4],
  ['HK_55', 'HOUSEKEEPING', 'HK_PROBLEM', 'C\'est en cours de réparation.', 'It\'s being repaired.', 'Info', 'A2', 'HK_SKILL_08', 3],
  ['HK_56', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je suis désolé pour ce désagrément.', 'I\'m sorry for this inconvenience.', 'Excuse', 'A2', 'HK_SKILL_10', 5],
  ['HK_57', 'HOUSEKEEPING', 'HK_PROBLEM', 'On vous change de chambre si vous voulez.', 'We can move you to another room if you want.', 'Alternative', 'A2', 'HK_SKILL_12', 10],
  ['HK_58', 'HOUSEKEEPING', 'HK_PROBLEM', 'C\'est temporaire.', 'It\'s temporary.', 'Info', 'A1', 'HK_SKILL_08', 2],
  ['HK_59', 'HOUSEKEEPING', 'HK_PROBLEM', 'Je comprends, c\'est frustrant.', 'I understand, it\'s frustrating.', 'Empathie', 'A2', 'HK_SKILL_09', 4],
  ['HK_60', 'HOUSEKEEPING', 'HK_PROBLEM', 'Laissez-moi appeler mon superviseur.', 'Let me call my supervisor.', 'Escalade', 'A2', 'HK_SKILL_11', 5],
  ['HK_61', 'HOUSEKEEPING', 'HK_ENTRY', 'Avez-vous besoin de serviettes ?', 'Do you need towels?', 'Service', 'A1', 'HK_SKILL_06', 4],
  ['HK_62', 'HOUSEKEEPING', 'HK_ENTRY', 'Puis-je changer les draps ?', 'May I change the sheets?', 'Service', 'A1', 'HK_SKILL_03', 5],
  ['HK_63', 'HOUSEKEEPING', 'HK_ENTRY', 'Je ne serai pas long.', 'I won\'t be long.', 'Info', 'A1', 'HK_SKILL_03', 4],
  ['HK_64', 'HOUSEKEEPING', 'HK_ENTRY', 'Merci, bonne journée.', 'Thank you, have a good day.', 'Cloture', 'A1', 'HK_SKILL_10', 5],
  ['HK_65', 'HOUSEKEEPING', 'HK_ENTRY', 'Appelez la réception si vous avez besoin.', 'Call reception if you need anything.', 'Info', 'A2', 'HK_SKILL_11', 6],
  ['HK_66', 'HOUSEKEEPING', 'HK_CLEAN', 'Je vais vider la poubelle.', 'I\'ll empty the trash.', 'Action', 'A1', 'HK_SKILL_03', 4],
  ['HK_67', 'HOUSEKEEPING', 'HK_CLEAN', 'J\'ai nettoyé le bureau.', 'I\'ve cleaned the desk.', 'Info', 'A1', 'HK_SKILL_03', 4],
  ['HK_68', 'HOUSEKEEPING', 'HK_CLEAN', 'Les produits de toilette sont remplacés.', 'The toiletries have been replaced.', 'Info', 'A2', 'HK_SKILL_03', 5],
  ['HK_69', 'HOUSEKEEPING', 'HK_CLEAN', 'J\'ai laissé de l\'eau fraîche.', 'I\'ve left fresh water.', 'Info', 'A1', 'HK_SKILL_03', 4],
  ['HK_70', 'HOUSEKEEPING', 'HK_CLEAN', 'Je peux revenir plus tard si vous préférez.', 'I can come back later if you prefer.', 'Alternative', 'A2', 'HK_SKILL_05', 8],
  ['HK_71', 'HOUSEKEEPING', 'HK_REQUEST', 'Je note votre demande.', 'I\'ll note your request.', 'Confirmation', 'A2', 'HK_SKILL_06', 4],
  ['HK_72', 'HOUSEKEEPING', 'HK_REQUEST', 'Le fer à repasser est dans le placard.', 'The iron is in the closet.', 'Info', 'A2', 'HK_SKILL_03', 6],
  ['HK_73', 'HOUSEKEEPING', 'HK_REQUEST', 'Je vous montre comment ça fonctionne.', 'I\'ll show you how it works.', 'Service', 'A2', 'HK_SKILL_03', 6],
  ['HK_74', 'HOUSEKEEPING', 'HK_REQUEST', 'Le sèche-cheveux est dans la salle de bain.', 'The hairdryer is in the bathroom.', 'Info', 'A1', 'HK_SKILL_03', 6],
  ['HK_75', 'HOUSEKEEPING', 'HK_REQUEST', 'Bien sûr, je m\'en occupe.', 'Of course, I\'ll take care of it.', 'Confirmation', 'A2', 'HK_SKILL_06', 6],
  ['HK_76', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Nous avons eu beaucoup de demandes.', 'We\'ve had many requests.', 'Explication', 'A2', 'HK_SKILL_13', 4],
  ['HK_77', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je m\'occupe de votre chambre en priorité.', 'I\'ll prioritize your room.', 'Action', 'A2', 'HK_SKILL_12', 4],
  ['HK_78', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Cela ne se reproduira pas.', 'This won\'t happen again.', 'Assurance', 'A2', 'HK_SKILL_15', 4],
  ['HK_79', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Puis-je faire quelque chose d\'autre ?', 'Can I do anything else?', 'Service', 'A2', 'HK_SKILL_06', 5],
  ['HK_80', 'HOUSEKEEPING', 'HK_COMPLAINT', 'Je transmets votre commentaire.', 'I\'ll pass on your feedback.', 'Escalade', 'A2', 'HK_SKILL_11', 5],

  // RESTAURANT - 50 phrases (subset for brevity, same structure)
  ['REST_01', 'RESTAURANT', 'REST_WELCOME', 'Bonjour, bienvenue au restaurant.', 'Good morning, welcome to the restaurant.', 'Accueil', 'A1', 'REST_SKILL_01', 6],
  ['REST_02', 'RESTAURANT', 'REST_WELCOME', 'Avez-vous une réservation ?', 'Do you have a reservation?', 'Verification', 'A1', 'REST_SKILL_01', 5],
  ['REST_03', 'RESTAURANT', 'REST_WELCOME', 'Combien de personnes ?', 'How many people?', 'Verification', 'A1', 'REST_SKILL_01', 3],
  ['REST_04', 'RESTAURANT', 'REST_WELCOME', 'Suivez-moi, s\'il vous plaît.', 'Follow me, please.', 'Service', 'A1', 'REST_SKILL_02', 3],
  ['REST_05', 'RESTAURANT', 'REST_WELCOME', 'Cette table vous convient ?', 'Is this table okay?', 'Proposition', 'A1', 'REST_SKILL_02', 4],
  ['REST_06', 'RESTAURANT', 'REST_WELCOME', 'Voici le menu.', 'Here is the menu.', 'Service', 'A1', 'REST_SKILL_03', 4],
  ['REST_07', 'RESTAURANT', 'REST_ORDER', 'Êtes-vous prêts à commander ?', 'Are you ready to order?', 'Ouverture', 'A1', 'REST_SKILL_04', 5],
  ['REST_08', 'RESTAURANT', 'REST_ORDER', 'Que désirez-vous comme entrée ?', 'What would you like as a starter?', 'Commande', 'A2', 'REST_SKILL_04', 7],
  ['REST_09', 'RESTAURANT', 'REST_ORDER', 'Et comme plat principal ?', 'And for the main course?', 'Commande', 'A2', 'REST_SKILL_04', 5],
  ['REST_10', 'RESTAURANT', 'REST_ORDER', 'Comment voulez-vous votre viande ?', 'How would you like your meat?', 'Precision', 'A2', 'REST_SKILL_04', 6],
  ['REST_11', 'RESTAURANT', 'REST_ORDER', 'Avez-vous des allergies ?', 'Do you have any allergies?', 'Securite', 'A2', 'REST_SKILL_06', 5],
  ['REST_12', 'RESTAURANT', 'REST_ORDER', 'Ce plat contient des noix.', 'This dish contains nuts.', 'Securite', 'A2', 'REST_SKILL_06', 4],
  ['REST_13', 'RESTAURANT', 'REST_ORDER', 'Je vous répète la commande.', 'Let me repeat the order.', 'Confirmation', 'A2', 'REST_SKILL_05', 5],
  ['REST_14', 'RESTAURANT', 'REST_ORDER', 'C\'est noté.', 'Got it.', 'Confirmation', 'A1', 'REST_SKILL_05', 2],
  ['REST_15', 'RESTAURANT', 'REST_SERVE', 'Voici votre entrée.', 'Here is your starter.', 'Service', 'A1', 'REST_SKILL_07', 4],
  ['REST_16', 'RESTAURANT', 'REST_SERVE', 'Voici votre plat principal.', 'Here is your main course.', 'Service', 'A1', 'REST_SKILL_07', 5],
  ['REST_17', 'RESTAURANT', 'REST_SERVE', 'Bon appétit !', 'Enjoy your meal!', 'Service', 'A1', 'REST_SKILL_07', 3],
  ['REST_18', 'RESTAURANT', 'REST_SERVE', 'Tout se passe bien ?', 'Is everything okay?', 'Verification', 'A1', 'REST_SKILL_08', 3],
  ['REST_19', 'RESTAURANT', 'REST_SERVE', 'Avez-vous besoin d\'autre chose ?', 'Do you need anything else?', 'Service', 'A1', 'REST_SKILL_08', 5],
  ['REST_20', 'RESTAURANT', 'REST_COMPLAINT', 'Ce n\'est pas ce que j\'ai commandé.', 'This isn\'t what I ordered.', 'Probleme', 'A2', 'REST_SKILL_09', 5],
  ['REST_21', 'RESTAURANT', 'REST_COMPLAINT', 'Je suis désolé, je corrige ça.', 'I\'m sorry, I\'ll fix that.', 'Correction', 'A2', 'REST_SKILL_09', 5],
  ['REST_22', 'RESTAURANT', 'REST_COMPLAINT', 'Je vous apporte le bon plat.', 'I\'ll bring you the correct dish.', 'Correction', 'A2', 'REST_SKILL_09', 6],
  ['REST_23', 'RESTAURANT', 'REST_SERVE', 'Désirez-vous un dessert ?', 'Would you like dessert?', 'Service', 'A1', 'REST_SKILL_04', 4],
  ['REST_24', 'RESTAURANT', 'REST_BILL', 'Voulez-vous l\'addition ?', 'Would you like the bill?', 'Facturation', 'A1', 'REST_SKILL_11', 5],
  ['REST_25', 'RESTAURANT', 'REST_BILL', 'Voici votre addition.', 'Here is your bill.', 'Facturation', 'A1', 'REST_SKILL_11', 4],
  ['REST_26', 'RESTAURANT', 'REST_BILL', 'Payez-vous ensemble ou séparément ?', 'Are you paying together or separately?', 'Paiement', 'A2', 'REST_SKILL_12', 6],
  ['REST_27', 'RESTAURANT', 'REST_BILL', 'Carte ou espèces ?', 'Card or cash?', 'Paiement', 'A1', 'REST_SKILL_12', 3],
  ['REST_28', 'RESTAURANT', 'REST_BILL', 'Voici votre reçu.', 'Here is your receipt.', 'Cloture', 'A1', 'REST_SKILL_12', 4],
  ['REST_29', 'RESTAURANT', 'REST_BILL', 'Merci, à bientôt !', 'Thank you, see you soon!', 'Cloture', 'A1', 'REST_SKILL_01', 5],
  ['REST_30', 'RESTAURANT', 'REST_COMPLAINT', 'Je comprends votre frustration.', 'I understand your frustration.', 'Empathie', 'A2', 'REST_SKILL_15', 4],
  ['REST_31', 'RESTAURANT', 'REST_ORDER', 'Que souhaitez-vous boire ?', 'What would you like to drink?', 'Service', 'A1', 'REST_SKILL_04', 6],
  ['REST_32', 'RESTAURANT', 'REST_ORDER', 'Je vous recommande le poisson.', 'I recommend the fish.', 'Conseil', 'A2', 'REST_SKILL_14', 4],
  ['REST_33', 'RESTAURANT', 'REST_ORDER', 'C\'est notre spécialité.', 'It\'s our specialty.', 'Conseil', 'A2', 'REST_SKILL_14', 3],
  ['REST_34', 'RESTAURANT', 'REST_SERVE', 'Attention, c\'est chaud.', 'Careful, it\'s hot.', 'Service', 'A1', 'REST_SKILL_07', 3],
  ['REST_35', 'RESTAURANT', 'REST_BILL', 'Le service est inclus.', 'Service is included.', 'Info', 'A2', 'REST_SKILL_11', 3],
  ['REST_36', 'RESTAURANT', 'REST_COMPLAINT', 'Je vais parler au chef.', 'I\'ll speak to the chef.', 'Escalade', 'A2', 'REST_SKILL_15', 5],
  ['REST_37', 'RESTAURANT', 'REST_COMPLAINT', 'Nous vous offrons le dessert.', 'We\'ll offer you dessert on the house.', 'Compensation', 'B1', 'REST_SKILL_15', 8],
  ['REST_38', 'RESTAURANT', 'REST_ORDER', 'Ce plat n\'est plus disponible.', 'This dish is no longer available.', 'Probleme', 'A2', 'REST_SKILL_09', 6],
  ['REST_39', 'RESTAURANT', 'REST_ORDER', 'Puis-je vous suggérer autre chose ?', 'May I suggest something else?', 'Alternative', 'A2', 'REST_SKILL_14', 5],
  ['REST_40', 'RESTAURANT', 'REST_WELCOME', 'Je vous laisse choisir.', 'I\'ll let you choose.', 'Service', 'A1', 'REST_SKILL_03', 4],
  ['REST_41', 'RESTAURANT', 'REST_SERVE', 'Je vais vérifier en cuisine.', 'I\'ll check with the kitchen.', 'Action', 'A2', 'REST_SKILL_09', 5],
  ['REST_42', 'RESTAURANT', 'REST_SERVE', 'Votre plat arrive bientôt.', 'Your dish is coming soon.', 'Info', 'A1', 'REST_SKILL_10', 5],
  ['REST_43', 'RESTAURANT', 'REST_COMPLAINT', 'Je suis désolé pour l\'attente.', 'I\'m sorry for the wait.', 'Excuse', 'A2', 'REST_SKILL_10', 5],
  ['REST_44', 'RESTAURANT', 'REST_COMPLAINT', 'Le service est trop lent !', 'The service is too slow!', 'Probleme', 'A2', 'REST_SKILL_10', 5],
  ['REST_45', 'RESTAURANT', 'REST_COMPLAINT', 'Je vais appeler le manager.', 'I\'ll call the manager.', 'Escalade', 'A2', 'REST_SKILL_15', 4],
  ['REST_46', 'RESTAURANT', 'REST_SERVE', 'Voici la carte des desserts.', 'Here is the dessert menu.', 'Service', 'A1', 'REST_SKILL_03', 5],
  ['REST_47', 'RESTAURANT', 'REST_WELCOME', 'Préférez-vous une table en terrasse ?', 'Would you prefer a table on the terrace?', 'Proposition', 'A2', 'REST_SKILL_02', 8],
  ['REST_48', 'RESTAURANT', 'REST_WELCOME', 'Je suis désolé, nous sommes complets.', 'I\'m sorry, we\'re fully booked.', 'Refus', 'A2', 'REST_SKILL_09', 5],
  ['REST_49', 'RESTAURANT', 'REST_INFO', 'Le restaurant ferme dans 30 minutes.', 'The restaurant closes in 30 minutes.', 'Info', 'A2', 'REST_SKILL_01', 6],
  ['REST_50', 'RESTAURANT', 'REST_BILL', 'Nous espérons vous revoir bientôt.', 'We hope to see you again soon.', 'Cloture', 'A2', 'REST_SKILL_01', 7],

  // SECURITY - 50 phrases (subset for brevity)
  ['SEC_01', 'SECURITY', 'SEC_CONTROL', 'Bonjour, sécurité de l\'hôtel.', 'Hello, hotel security.', 'Identification', 'A1', 'SEC_SKILL_01', 3],
  ['SEC_02', 'SECURITY', 'SEC_CONTROL', 'Puis-je voir votre clé de chambre ?', 'May I see your room key?', 'Demande', 'A1', 'SEC_SKILL_02', 6],
  ['SEC_03', 'SECURITY', 'SEC_CONTROL', 'Êtes-vous un client de l\'hôtel ?', 'Are you a hotel guest?', 'Verification', 'A1', 'SEC_SKILL_01', 5],
  ['SEC_04', 'SECURITY', 'SEC_CONTROL', 'C\'est pour la sécurité de tous.', 'It\'s for everyone\'s safety.', 'Explication', 'A2', 'SEC_SKILL_03', 4],
  ['SEC_05', 'SECURITY', 'SEC_CONTROL', 'Merci de votre compréhension.', 'Thank you for understanding.', 'Cloture', 'A1', 'SEC_SKILL_01', 4],
  ['SEC_06', 'SECURITY', 'SEC_DIRECT', 'Comment puis-je vous aider ?', 'How can I help you?', 'Ouverture', 'A1', 'SEC_SKILL_05', 5],
  ['SEC_07', 'SECURITY', 'SEC_DIRECT', 'La réception est par là.', 'Reception is that way.', 'Direction', 'A1', 'SEC_SKILL_04', 4],
  ['SEC_08', 'SECURITY', 'SEC_DIRECT', 'Les toilettes sont à droite.', 'The restrooms are on the right.', 'Direction', 'A1', 'SEC_SKILL_04', 6],
  ['SEC_09', 'SECURITY', 'SEC_DIRECT', 'Je peux vous accompagner.', 'I can escort you.', 'Service', 'A2', 'SEC_SKILL_15', 4],
  ['SEC_10', 'SECURITY', 'SEC_DIRECT', 'Suivez-moi, s\'il vous plaît.', 'Follow me, please.', 'Service', 'A1', 'SEC_SKILL_15', 3],
  ['SEC_11', 'SECURITY', 'SEC_RULE', 'Cette zone est réservée aux clients.', 'This area is for guests only.', 'Interdiction', 'A2', 'SEC_SKILL_07', 6],
  ['SEC_12', 'SECURITY', 'SEC_RULE', 'Les visiteurs doivent s\'enregistrer.', 'Visitors must check in.', 'Regle', 'A2', 'SEC_SKILL_07', 4],
  ['SEC_13', 'SECURITY', 'SEC_RULE', 'Je suis désolé, c\'est interdit.', 'I\'m sorry, that\'s not allowed.', 'Refus', 'A2', 'SEC_SKILL_06', 5],
  ['SEC_14', 'SECURITY', 'SEC_RULE', 'Vous pouvez attendre dans le lobby.', 'You can wait in the lobby.', 'Alternative', 'A2', 'SEC_SKILL_08', 7],
  ['SEC_15', 'SECURITY', 'SEC_RULE', 'Je vais appeler la réception pour vous.', 'I\'ll call reception for you.', 'Service', 'A2', 'SEC_SKILL_08', 5],
  ['SEC_16', 'SECURITY', 'SEC_CONFLICT', 'Calmez-vous, s\'il vous plaît.', 'Please calm down.', 'Intervention', 'A2', 'SEC_SKILL_09', 3],
  ['SEC_17', 'SECURITY', 'SEC_CONFLICT', 'Je suis là pour vous aider.', 'I\'m here to help you.', 'Desescalade', 'A2', 'SEC_SKILL_10', 5],
  ['SEC_18', 'SECURITY', 'SEC_CONFLICT', 'Parlons calmement.', 'Let\'s talk calmly.', 'Desescalade', 'A2', 'SEC_SKILL_10', 3],
  ['SEC_19', 'SECURITY', 'SEC_CONFLICT', 'Je comprends que vous êtes frustré.', 'I understand you\'re frustrated.', 'Empathie', 'A2', 'SEC_SKILL_10', 4],
  ['SEC_20', 'SECURITY', 'SEC_CONFLICT', 'Laissez-moi trouver une solution.', 'Let me find a solution.', 'Solution', 'A2', 'SEC_SKILL_10', 5],
  ['SEC_21', 'SECURITY', 'SEC_CONFLICT', 'Je dois appeler mon superviseur.', 'I need to call my supervisor.', 'Escalade', 'A2', 'SEC_SKILL_12', 5],
  ['SEC_22', 'SECURITY', 'SEC_CONFLICT', 'Veuillez baisser la voix.', 'Please lower your voice.', 'Intervention', 'A2', 'SEC_SKILL_09', 4],
  ['SEC_23', 'SECURITY', 'SEC_CONFLICT', 'C\'est ma dernière demande.', 'This is my final request.', 'Avertissement', 'B1', 'SEC_SKILL_11', 4],
  ['SEC_24', 'SECURITY', 'SEC_CONFLICT', 'Je vais devoir appeler la police.', 'I\'ll have to call the police.', 'Avertissement', 'B1', 'SEC_SKILL_11', 6],
  ['SEC_25', 'SECURITY', 'SEC_CONFLICT', 'Veuillez quitter les lieux.', 'Please leave the premises.', 'Ordre', 'B1', 'SEC_SKILL_11', 4],
  ['SEC_26', 'SECURITY', 'SEC_INCIDENT', 'Y a-t-il un problème ?', 'Is there a problem?', 'Verification', 'A1', 'SEC_SKILL_13', 4],
  ['SEC_27', 'SECURITY', 'SEC_INCIDENT', 'Que s\'est-il passé ?', 'What happened?', 'Enquete', 'A1', 'SEC_SKILL_13', 2],
  ['SEC_28', 'SECURITY', 'SEC_INCIDENT', 'Êtes-vous blessé ?', 'Are you hurt?', 'Assistance', 'A1', 'SEC_SKILL_14', 3],
  ['SEC_29', 'SECURITY', 'SEC_INCIDENT', 'Je vais chercher de l\'aide.', 'I\'ll get help.', 'Action', 'A1', 'SEC_SKILL_12', 3],
  ['SEC_30', 'SECURITY', 'SEC_INCIDENT', 'Restez calme, j\'arrive.', 'Stay calm, I\'m coming.', 'Reassurance', 'A1', 'SEC_SKILL_14', 4],
  ['SEC_31', 'SECURITY', 'SEC_CONTROL', 'Votre nom, s\'il vous plaît.', 'Your name, please.', 'Identification', 'A1', 'SEC_SKILL_02', 3],
  ['SEC_32', 'SECURITY', 'SEC_CONTROL', 'Quel est le numéro de votre chambre ?', 'What is your room number?', 'Verification', 'A1', 'SEC_SKILL_01', 5],
  ['SEC_33', 'SECURITY', 'SEC_DIRECT', 'Le parking est au sous-sol.', 'The parking is in the basement.', 'Direction', 'A1', 'SEC_SKILL_04', 6],
  ['SEC_34', 'SECURITY', 'SEC_DIRECT', 'L\'ascenseur est devant vous.', 'The elevator is in front of you.', 'Direction', 'A1', 'SEC_SKILL_04', 7],
  ['SEC_35', 'SECURITY', 'SEC_RULE', 'Il est interdit de fumer ici.', 'Smoking is not allowed here.', 'Interdiction', 'A2', 'SEC_SKILL_07', 5],
  ['SEC_36', 'SECURITY', 'SEC_RULE', 'La piscine ferme à 22h.', 'The pool closes at 10 PM.', 'Regle', 'A1', 'SEC_SKILL_07', 6],
  ['SEC_37', 'SECURITY', 'SEC_CONFLICT', 'Je comprends votre situation.', 'I understand your situation.', 'Empathie', 'A2', 'SEC_SKILL_10', 4],
  ['SEC_38', 'SECURITY', 'SEC_CONFLICT', 'Trouvons une solution ensemble.', 'Let\'s find a solution together.', 'Desescalade', 'A2', 'SEC_SKILL_10', 5],
  ['SEC_39', 'SECURITY', 'SEC_INCIDENT', 'Je note l\'incident.', 'I\'m noting the incident.', 'Documentation', 'A2', 'SEC_SKILL_13', 4],
  ['SEC_40', 'SECURITY', 'SEC_INCIDENT', 'Des renforts arrivent.', 'Backup is coming.', 'Info', 'A2', 'SEC_SKILL_12', 3],
  ['SEC_41', 'SECURITY', 'SEC_CONTROL', 'Veuillez patienter un instant.', 'Please wait a moment.', 'Attente', 'A1', 'SEC_SKILL_05', 4],
  ['SEC_42', 'SECURITY', 'SEC_DIRECT', 'La sortie de secours est là.', 'The emergency exit is there.', 'Direction', 'A2', 'SEC_SKILL_04', 5],
  ['SEC_43', 'SECURITY', 'SEC_RULE', 'Les animaux ne sont pas admis.', 'Pets are not allowed.', 'Regle', 'A2', 'SEC_SKILL_06', 4],
  ['SEC_44', 'SECURITY', 'SEC_CONFLICT', 'Je fais mon travail.', 'I\'m doing my job.', 'Justification', 'A2', 'SEC_SKILL_14', 4],
  ['SEC_45', 'SECURITY', 'SEC_INCIDENT', 'Avez-vous vu quelque chose ?', 'Did you see anything?', 'Enquete', 'A2', 'SEC_SKILL_13', 4],
  ['SEC_46', 'SECURITY', 'SEC_CONTROL', 'Tout est en ordre.', 'Everything is in order.', 'Confirmation', 'A1', 'SEC_SKILL_01', 4],
  ['SEC_47', 'SECURITY', 'SEC_DIRECT', 'Je vous montre le chemin.', 'I\'ll show you the way.', 'Service', 'A2', 'SEC_SKILL_15', 5],
  ['SEC_48', 'SECURITY', 'SEC_RULE', 'C\'est pour votre sécurité.', 'It\'s for your safety.', 'Explication', 'A2', 'SEC_SKILL_03', 4],
  ['SEC_49', 'SECURITY', 'SEC_CONFLICT', 'Nous pouvons résoudre cela.', 'We can resolve this.', 'Desescalade', 'A2', 'SEC_SKILL_10', 4],
  ['SEC_50', 'SECURITY', 'SEC_INCIDENT', 'L\'ambulance est en route.', 'The ambulance is on the way.', 'Info', 'A2', 'SEC_SKILL_12', 6],
];

export const PHRASES: Phrase[] = phrasesDef.map(([id, role, actionId, fr, en, phase, level, skillId, wc]) => ({
  id, role, actionId, phraseFr: fr, phraseEn: en, phase, level: level as any, skillId, wordCount: wc
}));

// ─────────────────────────────────────────────────────────────────
// SCENARIOS (simplified structure)
// ─────────────────────────────────────────────────────────────────

export const SCENARIOS: Scenario[] = [
  {
    id: 'REC_SCENARIO_01', role: 'RECEPTION', actionId: 'REC_CHECKIN', title: 'Check-in Standard',
    type: 'NORMAL', level: 'A1', context: 'Client arrive à 15h pour s\'enregistrer.',
    skillIds: ['REC_SKILL_01', 'REC_SKILL_02', 'REC_SKILL_03'],
    steps: [
      { id: 's1', situation: 'Client entre', options: [
        { id: 'a', text: 'Good morning', correct: false, feedback: 'Il est 15h' },
        { id: 'b', text: 'Good afternoon, welcome', correct: true, feedback: 'Correct' },
        { id: 'c', text: 'Hello what?', correct: false, feedback: 'Impoli' }
      ], nextStep: 's2' },
      { id: 's2', situation: 'Client: I have a reservation', clientSays: 'I have a reservation', options: [
        { id: 'a', text: 'What name please?', correct: true, feedback: 'Correct' },
        { id: 'b', text: 'Passport!', correct: false, feedback: 'Brusque' },
        { id: 'c', text: 'Room number?', correct: false, feedback: 'Pas encore attribué' }
      ], nextStep: null }
    ]
  },
  {
    id: 'REC_SCENARIO_02', role: 'RECEPTION', actionId: 'REC_COMPLAINT', title: 'Réservation Introuvable',
    type: 'CONFLICT', level: 'A2', context: 'Réservation non trouvée dans le système.',
    skillIds: ['REC_SKILL_07', 'REC_SKILL_08', 'REC_SKILL_09'],
    steps: [
      { id: 's1', situation: 'Client énervé', options: [
        { id: 'a', text: 'Let me check... Sorry, not found', correct: true, feedback: 'Bon' },
        { id: 'b', text: 'No reservation', correct: false, feedback: 'Trop direct' },
        { id: 'c', text: 'Calm down', correct: false, feedback: 'Énervant' }
      ], nextStep: null }
    ]
  },
  {
    id: 'HK_SCENARIO_01', role: 'HOUSEKEEPING', actionId: 'HK_ENTRY', title: 'Entrée Chambre',
    type: 'NORMAL', level: 'A1', context: 'Nettoyage chambre 205.',
    skillIds: ['HK_SKILL_01', 'HK_SKILL_02', 'HK_SKILL_04'],
    steps: [
      { id: 's1', situation: 'Frapper à la porte', options: [
        { id: 'a', text: 'Housekeeping!', correct: true, feedback: 'Correct' },
        { id: 'b', text: '(entrer direct)', correct: false, feedback: 'Toujours frapper' },
        { id: 'c', text: 'Hello?', correct: false, feedback: 'Pas clair' }
      ], nextStep: null }
    ]
  },
  {
    id: 'REST_SCENARIO_01', role: 'RESTAURANT', actionId: 'REST_WELCOME', title: 'Service Standard',
    type: 'NORMAL', level: 'A1', context: 'Couple arrive pour dîner.',
    skillIds: ['REST_SKILL_01', 'REST_SKILL_02', 'REST_SKILL_04'],
    steps: [
      { id: 's1', situation: 'Clients entrent', options: [
        { id: 'a', text: 'Good evening, do you have a reservation?', correct: true, feedback: 'Parfait' },
        { id: 'b', text: 'Table?', correct: false, feedback: 'Trop direct' },
        { id: 'c', text: '(ignorer)', correct: false, feedback: 'Toujours accueillir' }
      ], nextStep: null }
    ]
  },
  {
    id: 'SEC_SCENARIO_01', role: 'SECURITY', actionId: 'SEC_CONTROL', title: 'Contrôle Accès',
    type: 'NORMAL', level: 'A1', context: 'Personne sans badge.',
    skillIds: ['SEC_SKILL_01', 'SEC_SKILL_02', 'SEC_SKILL_03'],
    steps: [
      { id: 's1', situation: 'Personne vers ascenseurs', options: [
        { id: 'a', text: 'Hotel security. May I see your room key?', correct: true, feedback: 'Correct' },
        { id: 'b', text: 'Stop!', correct: false, feedback: 'Agressif' },
        { id: 'c', text: '(laisser passer)', correct: false, feedback: 'Vérifier' }
      ], nextStep: null }
    ]
  },
];

// ─────────────────────────────────────────────────────────────────
// TEST QUESTIONS
// ─────────────────────────────────────────────────────────────────

export const TEST_QUESTIONS: TestQuestion[] = [
  // COMPREHENSION INITIAL
  { id: 'TQ_COMP_I1', dimension: 'COMPREHENSION', level: 'A1', type: 'QCM',
    question: 'Que signifie "I have a reservation"?',
    options: [{ id: 'a', text: 'Je veux réserver' }, { id: 'b', text: 'J\'ai une réservation' }, { id: 'c', text: 'Où est ma chambre' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_02', HOUSEKEEPING: 'HK_SKILL_04', RESTAURANT: 'REST_SKILL_04', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_COMP_I2', dimension: 'COMPREHENSION', level: 'A1', type: 'QCM',
    question: 'Que signifie "How can I help you?"?',
    options: [{ id: 'a', text: 'Comment allez-vous' }, { id: 'b', text: 'Comment puis-je vous aider' }, { id: 'c', text: 'Où allez-vous' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_05', HOUSEKEEPING: 'HK_SKILL_04', RESTAURANT: 'REST_SKILL_04', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_COMP_I3', dimension: 'COMPREHENSION', level: 'A2', type: 'QCM',
    question: 'Que signifie "I\'m not satisfied"?',
    options: [{ id: 'a', text: 'Je suis satisfait' }, { id: 'b', text: 'Je ne suis pas satisfait' }, { id: 'c', text: 'Je suis content' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_07', HOUSEKEEPING: 'HK_SKILL_09', RESTAURANT: 'REST_SKILL_08', SECURITY: 'SEC_SKILL_13' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_COMP_I4', dimension: 'COMPREHENSION', level: 'A2', type: 'QCM',
    question: 'Que signifie "Come back later"?',
    options: [{ id: 'a', text: 'Revenez plus tard' }, { id: 'b', text: 'Partez maintenant' }, { id: 'c', text: 'Aidez-moi' }],
    correctAnswer: 'a', skillMapping: { RECEPTION: 'REC_SKILL_05', HOUSEKEEPING: 'HK_SKILL_04', RESTAURANT: 'REST_SKILL_04', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'INITIAL' },
  // COMPREHENSION FINAL
  { id: 'TQ_COMP_F1', dimension: 'COMPREHENSION', level: 'A1', type: 'QCM',
    question: 'Que signifie "I booked a room"?',
    options: [{ id: 'a', text: 'Je cherche une chambre' }, { id: 'b', text: 'J\'ai réservé une chambre' }, { id: 'c', text: 'La chambre est prête' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_02', HOUSEKEEPING: 'HK_SKILL_04', RESTAURANT: 'REST_SKILL_04', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_COMP_F2', dimension: 'COMPREHENSION', level: 'A1', type: 'QCM',
    question: 'Que signifie "What can I do for you?"?',
    options: [{ id: 'a', text: 'Que puis-je faire pour vous' }, { id: 'b', text: 'Qu\'est-ce que vous faites' }, { id: 'c', text: 'Que voulez-vous' }],
    correctAnswer: 'a', skillMapping: { RECEPTION: 'REC_SKILL_05', HOUSEKEEPING: 'HK_SKILL_04', RESTAURANT: 'REST_SKILL_04', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_COMP_F3', dimension: 'COMPREHENSION', level: 'A2', type: 'QCM',
    question: 'Que signifie "This is unacceptable"?',
    options: [{ id: 'a', text: 'C\'est acceptable' }, { id: 'b', text: 'C\'est inacceptable' }, { id: 'c', text: 'C\'est agréable' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_08', HOUSEKEEPING: 'HK_SKILL_09', RESTAURANT: 'REST_SKILL_15', SECURITY: 'SEC_SKILL_13' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_COMP_F4', dimension: 'COMPREHENSION', level: 'A2', type: 'QCM',
    question: 'Que signifie "I\'ll be right back"?',
    options: [{ id: 'a', text: 'Je reviens tout de suite' }, { id: 'b', text: 'Je ne reviens pas' }, { id: 'c', text: 'Allez-y' }],
    correctAnswer: 'a', skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_05', RESTAURANT: 'REST_SKILL_07', SECURITY: 'SEC_SKILL_08' },
    points: 1, testSet: 'FINAL' },
  // PRODUCTION
  { id: 'TQ_PROD_I1', dimension: 'PRODUCTION', level: 'A1', type: 'TEXT',
    question: 'Écrivez "Bienvenue" en anglais', correctAnswer: 'welcome', acceptableAnswers: ['welcome'],
    skillMapping: { RECEPTION: 'REC_SKILL_01', HOUSEKEEPING: 'HK_SKILL_01', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_01' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_PROD_I2', dimension: 'PRODUCTION', level: 'A1', type: 'TEXT',
    question: 'Écrivez "Merci" en anglais', correctAnswer: 'thank you', acceptableAnswers: ['thank you', 'thanks'],
    skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_10', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_01' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_PROD_I3', dimension: 'PRODUCTION', level: 'A2', type: 'TEXT',
    question: 'Écrivez "Je suis désolé" en anglais', correctAnswer: 'i am sorry', acceptableAnswers: ['i am sorry', 'i\'m sorry', 'sorry'],
    skillMapping: { RECEPTION: 'REC_SKILL_07', HOUSEKEEPING: 'HK_SKILL_10', RESTAURANT: 'REST_SKILL_09', SECURITY: 'SEC_SKILL_06' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_PROD_I4', dimension: 'PRODUCTION', level: 'A2', type: 'TEXT',
    question: 'Écrivez "Comment puis-je vous aider" en anglais', correctAnswer: 'how can i help you', acceptableAnswers: ['how can i help you', 'how may i help you'],
    skillMapping: { RECEPTION: 'REC_SKILL_01', HOUSEKEEPING: 'HK_SKILL_06', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_PROD_F1', dimension: 'PRODUCTION', level: 'A1', type: 'TEXT',
    question: 'Écrivez "Bon séjour" en anglais', correctAnswer: 'enjoy your stay', acceptableAnswers: ['enjoy your stay', 'have a nice stay'],
    skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_01', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_01' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_PROD_F2', dimension: 'PRODUCTION', level: 'A1', type: 'TEXT',
    question: 'Écrivez "S\'il vous plaît" en anglais', correctAnswer: 'please', acceptableAnswers: ['please'],
    skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_02', RESTAURANT: 'REST_SKILL_07', SECURITY: 'SEC_SKILL_06' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_PROD_F3', dimension: 'PRODUCTION', level: 'A2', type: 'TEXT',
    question: 'Écrivez "Un moment s\'il vous plaît" en anglais', correctAnswer: 'one moment please', acceptableAnswers: ['one moment please', 'just a moment please'],
    skillMapping: { RECEPTION: 'REC_SKILL_10', HOUSEKEEPING: 'HK_SKILL_06', RESTAURANT: 'REST_SKILL_07', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_PROD_F4', dimension: 'PRODUCTION', level: 'A2', type: 'TEXT',
    question: 'Écrivez "Je vais vérifier" en anglais', correctAnswer: 'let me check', acceptableAnswers: ['let me check', 'i will check', 'i\'ll check'],
    skillMapping: { RECEPTION: 'REC_SKILL_02', HOUSEKEEPING: 'HK_SKILL_08', RESTAURANT: 'REST_SKILL_09', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'FINAL' },
  // INTERACTION
  { id: 'TQ_SIT_I1', dimension: 'INTERACTION', level: 'A1', type: 'QCM',
    question: 'Un client arrive. Que dites-vous?',
    options: [{ id: 'a', text: 'What do you want?' }, { id: 'b', text: 'Good morning, welcome!' }, { id: 'c', text: 'Passport!' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_01', HOUSEKEEPING: 'HK_SKILL_01', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_01' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_SIT_I2', dimension: 'INTERACTION', level: 'A2', type: 'QCM',
    question: 'Client demande info inconnue. Que dites-vous?',
    options: [{ id: 'a', text: 'I don\'t know' }, { id: 'b', text: 'Let me check for you' }, { id: 'c', text: 'Ask someone else' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_09', HOUSEKEEPING: 'HK_SKILL_11', RESTAURANT: 'REST_SKILL_14', SECURITY: 'SEC_SKILL_08' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_SIT_I3', dimension: 'INTERACTION', level: 'A2', type: 'QCM',
    question: 'Client vous remercie. Que répondez-vous?',
    options: [{ id: 'a', text: 'OK' }, { id: 'b', text: 'You\'re welcome!' }, { id: 'c', text: 'Bye' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_10', RESTAURANT: 'REST_SKILL_08', SECURITY: 'SEC_SKILL_15' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_SIT_I4', dimension: 'INTERACTION', level: 'B1', type: 'QCM',
    question: 'Client insatisfait. Première réponse?',
    options: [{ id: 'a', text: 'Not my fault' }, { id: 'b', text: 'I understand. How can I help?' }, { id: 'c', text: 'Not possible' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_07', HOUSEKEEPING: 'HK_SKILL_09', RESTAURANT: 'REST_SKILL_09', SECURITY: 'SEC_SKILL_13' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_SIT_F1', dimension: 'INTERACTION', level: 'A1', type: 'QCM',
    question: 'Comment terminer interaction positive?',
    options: [{ id: 'a', text: 'OK' }, { id: 'b', text: 'Have a nice day!' }, { id: 'c', text: 'Next!' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_06', HOUSEKEEPING: 'HK_SKILL_10', RESTAURANT: 'REST_SKILL_01', SECURITY: 'SEC_SKILL_15' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_SIT_F2', dimension: 'INTERACTION', level: 'A2', type: 'QCM',
    question: 'Client doit attendre. Que dites-vous?',
    options: [{ id: 'a', text: 'Wait!' }, { id: 'b', text: 'One moment please' }, { id: 'c', text: 'I\'m busy' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_10', HOUSEKEEPING: 'HK_SKILL_05', RESTAURANT: 'REST_SKILL_10', SECURITY: 'SEC_SKILL_05' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_SIT_F3', dimension: 'INTERACTION', level: 'A2', type: 'QCM',
    question: 'Vous avez fait erreur. Que dites-vous?',
    options: [{ id: 'a', text: 'I apologize, let me fix that' }, { id: 'b', text: 'Your problem' }, { id: 'c', text: 'Not my fault' }],
    correctAnswer: 'a', skillMapping: { RECEPTION: 'REC_SKILL_07', HOUSEKEEPING: 'HK_SKILL_10', RESTAURANT: 'REST_SKILL_09', SECURITY: 'SEC_SKILL_10' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_SIT_F4', dimension: 'INTERACTION', level: 'B1', type: 'QCM',
    question: 'Demande impossible. Réponse?',
    options: [{ id: 'a', text: 'No' }, { id: 'b', text: 'Unfortunately not possible, but I can offer...' }, { id: 'c', text: 'Ask manager' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_09', HOUSEKEEPING: 'HK_SKILL_05', RESTAURANT: 'REST_SKILL_14', SECURITY: 'SEC_SKILL_08' },
    points: 1, testSet: 'FINAL' },
  // CONFLICT
  { id: 'TQ_CONF_I1', dimension: 'CONFLICT', level: 'A2', type: 'QCM',
    question: 'Client en colère crie. Que faites-vous?',
    options: [{ id: 'a', text: 'Crier aussi' }, { id: 'b', text: 'Rester calme et écouter' }, { id: 'c', text: 'Partir' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_15', HOUSEKEEPING: 'HK_SKILL_15', RESTAURANT: 'REST_SKILL_15', SECURITY: 'SEC_SKILL_14' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_CONF_I2', dimension: 'CONFLICT', level: 'B1', type: 'QCM',
    question: 'Client veut voir manager. Réponse?',
    options: [{ id: 'a', text: 'Manager is busy' }, { id: 'b', text: 'Of course, may I offer coffee?' }, { id: 'c', text: 'Why?' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_10', HOUSEKEEPING: 'HK_SKILL_11', RESTAURANT: 'REST_SKILL_15', SECURITY: 'SEC_SKILL_12' },
    points: 1, testSet: 'INITIAL' },
  { id: 'TQ_CONF_F1', dimension: 'CONFLICT', level: 'A2', type: 'QCM',
    question: 'Plainte forte. Comment montrer empathie?',
    options: [{ id: 'a', text: 'I don\'t care' }, { id: 'b', text: 'I completely understand' }, { id: 'c', text: 'That\'s normal' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_08', HOUSEKEEPING: 'HK_SKILL_09', RESTAURANT: 'REST_SKILL_15', SECURITY: 'SEC_SKILL_10' },
    points: 1, testSet: 'FINAL' },
  { id: 'TQ_CONF_F2', dimension: 'CONFLICT', level: 'B1', type: 'QCM',
    question: 'Après résolution problème?',
    options: [{ id: 'a', text: 'Rien' }, { id: 'b', text: 'Vérifier satisfaction et s\'excuser' }, { id: 'c', text: 'Demander pourboire' }],
    correctAnswer: 'b', skillMapping: { RECEPTION: 'REC_SKILL_09', HOUSEKEEPING: 'HK_SKILL_12', RESTAURANT: 'REST_SKILL_08', SECURITY: 'SEC_SKILL_10' },
    points: 1, testSet: 'FINAL' },
];

// ─────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────

export function getSkillsByRole(role: Role): Skill[] {
  return SKILLS.filter(s => s.role === role).sort((a, b) => a.order - b.order);
}

export function getPhrasesByRole(role: Role): Phrase[] {
  return PHRASES.filter(p => p.role === role);
}

export function getScenariosByRole(role: Role): Scenario[] {
  return SCENARIOS.filter(s => s.role === role);
}

export function getTestQuestions(testType: TestType): TestQuestion[] {
  return TEST_QUESTIONS.filter(q => q.testSet === testType || q.testSet === 'BOTH');
}
