begin;
-- Restaurant (Hôtel urbain) — 320 phrases (20 actions × 16)

insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('RST_FB_GREET_GUEST_0001', 'FB_GREET_GUEST', 'Bonjour, bienvenue au restaurant.', 'Good evening, welcome to the restaurant.', 'Accueil', 'A1', 'STAFF', null),
('RST_FB_GREET_GUEST_0002', 'FB_GREET_GUEST', 'Avez-vous une réservation ?', 'Do you have a reservation?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_GREET_GUEST_0003', 'FB_GREET_GUEST', 'Pour combien de personnes, s’il vous plaît ?', 'For how many people, please?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_GREET_GUEST_0004', 'FB_GREET_GUEST', 'Suivez-moi, s’il vous plaît.', 'Please follow me.', 'Service', 'A1', 'STAFF', null),
('RST_FB_GREET_GUEST_0005', 'FB_GREET_GUEST', 'Voici votre table.', 'Here is your table.', 'Service', 'A1', 'STAFF', null),
('RST_FB_GREET_GUEST_0006', 'FB_GREET_GUEST', 'Bonsoir.', 'Good evening.', 'Accueil', 'A1', 'CLIENT', null),
('RST_FB_GREET_GUEST_0007', 'FB_GREET_GUEST', 'Oui, au nom de {guest_name}.', 'Yes, under the name {guest_name}.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_GREET_GUEST_0008', 'FB_GREET_GUEST', 'Nous sommes {time} personnes.', 'We are {time} people.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_GREET_GUEST_0009', 'FB_GREET_GUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_GREET_GUEST_0010', 'FB_GREET_GUEST', 'Pouvons-nous avoir une table au calme ?', 'Could we have a quieter table?', 'Service', 'A2', 'CLIENT', null),
('RST_FB_GREET_GUEST_0011', 'FB_GREET_GUEST', 'Bien sûr. Je vais voir la meilleure option disponible.', 'Of course. I will check the best available option available.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GREET_GUEST_0012', 'FB_GREET_GUEST', 'Je peux vous proposer une table près de la fenêtre, si vous le souhaitez.', 'I can offer you a table by the window, if you wish.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GREET_GUEST_0013', 'FB_GREET_GUEST', 'Si vous préférez, nous pouvons vous installer sur la terrasse.', 'If you prefer, we can seat you on the terrace.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GREET_GUEST_0014', 'FB_GREET_GUEST', 'Nous avons une réservation tardive. Est-ce possible d’attendre au bar ?', 'Our reservation is later. Can we wait at the bar?', 'Service', 'B1', 'CLIENT', null),
('RST_FB_GREET_GUEST_0015', 'FB_GREET_GUEST', 'Absolument. Je vous y accompagne et je reviens vers vous dès qu’une table se libère.', 'Absolutely. I will take you there and come back as soon as a table is available.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GREET_GUEST_0016', 'FB_GREET_GUEST', 'Merci, nous apprécions.', 'Thank you, we appreciate it.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0001', 'FB_SEATING_GUEST', 'Puis-je vous aider avec vos manteaux ?', 'May I help you with your coats?', 'Service', 'A2', 'STAFF', null),
('RST_FB_SEATING_GUEST_0002', 'FB_SEATING_GUEST', 'Préférez-vous une banquette ou des chaises ?', 'Would you prefer a booth or chairs?', 'Service', 'A2', 'STAFF', null),
('RST_FB_SEATING_GUEST_0003', 'FB_SEATING_GUEST', 'Je vous apporte une carte tout de suite.', 'I will bring you a menu right away.', 'Service', 'A1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0004', 'FB_SEATING_GUEST', 'Voici la carte.', 'Here is the menu.', 'Service', 'A1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0005', 'FB_SEATING_GUEST', 'Souhaitez-vous de l’eau plate ou gazeuse ?', 'Would you like still or sparkling water?', 'Service', 'A2', 'STAFF', null),
('RST_FB_SEATING_GUEST_0006', 'FB_SEATING_GUEST', 'Une banquette, s’il vous plaît.', 'A booth, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0007', 'FB_SEATING_GUEST', 'Des chaises, merci.', 'Chairs, thank you.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0008', 'FB_SEATING_GUEST', 'De l’eau gazeuse, s’il vous plaît.', 'Sparkling water, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0009', 'FB_SEATING_GUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0010', 'FB_SEATING_GUEST', 'Pouvons-nous avoir une chaise bébé ?', 'Could we have a high chair?', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0011', 'FB_SEATING_GUEST', 'Bien sûr, je vous l’apporte immédiatement.', 'Of course, I will bring it immediately.', 'Service', 'B1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0012', 'FB_SEATING_GUEST', 'Je peux ajuster la table pour plus d’espace, si vous le souhaitez.', 'I can adjust the table for more space, if you wish.', 'Service', 'B1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0013', 'FB_SEATING_GUEST', 'Souhaitez-vous un coin plus discret pour un échange professionnel ?', 'Would you like a more discreet area for a business conversation?', 'Service', 'B1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0014', 'FB_SEATING_GUEST', 'Oui, si possible.', 'Yes, if possible.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_SEATING_GUEST_0015', 'FB_SEATING_GUEST', 'Je vous installe de ce côté, c’est plus calme.', 'I will seat you on this side, it is quieter.', 'Service', 'B1', 'STAFF', null),
('RST_FB_SEATING_GUEST_0016', 'FB_SEATING_GUEST', 'Parfait, merci beaucoup.', 'Perfect, thank you very much.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0001', 'FB_PRESENT_MENU', 'Voici notre menu du jour.', 'Here is our daily menu.', 'Information', 'A2', 'STAFF', null),
('RST_FB_PRESENT_MENU_0002', 'FB_PRESENT_MENU', 'Nos suggestions sont indiquées ici.', 'Our chef’s specials are listed here.', 'Information', 'A2', 'STAFF', null),
('RST_FB_PRESENT_MENU_0003', 'FB_PRESENT_MENU', 'Le plat du jour est {dish}.', 'Today’s special is {dish}.', 'Information', 'A2', 'STAFF', null),
('RST_FB_PRESENT_MENU_0004', 'FB_PRESENT_MENU', 'Avez-vous des questions sur la carte ?', 'Do you have any questions about the menu?', 'Information', 'A2', 'STAFF', null),
('RST_FB_PRESENT_MENU_0005', 'FB_PRESENT_MENU', 'Je reviens dans un instant pour la commande.', 'I will be back shortly to take your order.', 'Service', 'A2', 'STAFF', null),
('RST_FB_PRESENT_MENU_0006', 'FB_PRESENT_MENU', 'Qu’est-ce que vous recommandez ?', 'What do you recommend?', 'Information', 'A2', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0007', 'FB_PRESENT_MENU', 'Le plat du jour, s’il vous plaît.', 'The daily special, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0008', 'FB_PRESENT_MENU', 'Y a-t-il une option végétarienne ?', 'Is there a vegetarian option?', 'Information', 'A2', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0009', 'FB_PRESENT_MENU', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0010', 'FB_PRESENT_MENU', 'Nous aimerions quelque chose de rapide.', 'We would like something quick.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0011', 'FB_PRESENT_MENU', 'Bien sûr. Je peux vous orienter vers des plats qui sortent en moins de {time} minutes.', 'Of course. I can guide you to dishes that are ready in under {time} minutes.', 'Service', 'B1', 'STAFF', null),
('RST_FB_PRESENT_MENU_0012', 'FB_PRESENT_MENU', 'Si vous avez un timing serré, je vous conseille {dish} et {dish}.', 'If you are on a tight schedule, I recommend {dish} and {dish}.', 'Service', 'B1', 'STAFF', null),
('RST_FB_PRESENT_MENU_0013', 'FB_PRESENT_MENU', 'Souhaitez-vous que je vous explique nos portions et accompagnements ?', 'Would you like me to explain portions and side options?', 'Information', 'B1', 'STAFF', null),
('RST_FB_PRESENT_MENU_0014', 'FB_PRESENT_MENU', 'Oui, rapidement s’il vous plaît.', 'Yes, quickly please.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_PRESENT_MENU_0015', 'FB_PRESENT_MENU', 'Très bien. Les portions sont généreuses, et vous pouvez choisir deux garnitures.', 'Certainly. Portions are generous, and you can choose two sides.', 'Information', 'B1', 'STAFF', null),
('RST_FB_PRESENT_MENU_0016', 'FB_PRESENT_MENU', 'Parfait, on prend ça.', 'Perfect, we will take that.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0001', 'FB_TAKE_ORDER', 'Êtes-vous prêt(e) à commander ?', 'Are you ready to order?', 'Service', 'A2', 'STAFF', null),
('RST_FB_TAKE_ORDER_0002', 'FB_TAKE_ORDER', 'Que puis-je vous servir ?', 'What can I get for you?', 'Service', 'A2', 'STAFF', null),
('RST_FB_TAKE_ORDER_0003', 'FB_TAKE_ORDER', 'Et pour vous ?', 'And for you?', 'Service', 'A1', 'STAFF', null),
('RST_FB_TAKE_ORDER_0004', 'FB_TAKE_ORDER', 'Souhaitez-vous une entrée ?', 'Would you like a starter?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_TAKE_ORDER_0005', 'FB_TAKE_ORDER', 'Très bien, je note.', 'Very well, I am taking note.', 'Service', 'A2', 'STAFF', null),
('RST_FB_TAKE_ORDER_0006', 'FB_TAKE_ORDER', 'Je prendrai {dish}, s’il vous plaît.', 'I will have {dish}, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0007', 'FB_TAKE_ORDER', 'Pour moi, {dish}.', 'For me, {dish}.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0008', 'FB_TAKE_ORDER', 'Sans oignons, s’il vous plaît.', 'No onions, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0009', 'FB_TAKE_ORDER', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0010', 'FB_TAKE_ORDER', 'Est-ce que c’est épicé ?', 'Is it spicy?', 'Information', 'A2', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0011', 'FB_TAKE_ORDER', 'Je peux vous conseiller selon vos préférences : plutôt épicé, doux, ou équilibré ?', 'I can advise based on your preference: spicy, mild, or balanced?', 'Information', 'B1', 'STAFF', null),
('RST_FB_TAKE_ORDER_0012', 'FB_TAKE_ORDER', 'Si vous le souhaitez, je peux proposer une entrée à partager.', 'If you wish, I can suggest a starter to share.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_TAKE_ORDER_0013', 'FB_TAKE_ORDER', 'Souhaitez-vous que nous servions les plats en même temps ?', 'Would you like all mains served at the same time?', 'Service', 'B1', 'STAFF', null),
('RST_FB_TAKE_ORDER_0014', 'FB_TAKE_ORDER', 'Oui, s’il vous plaît.', 'Yes, please.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_TAKE_ORDER_0015', 'FB_TAKE_ORDER', 'Très bien. Je transmets la commande immédiatement en cuisine.', 'Great. I will send the order to the kitchen immediately.', 'Service', 'B1', 'STAFF', null),
('RST_FB_TAKE_ORDER_0016', 'FB_TAKE_ORDER', 'Merci, c’est parfait.', 'Thank you, that’s perfect.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0001', 'FB_CONFIRM_ORDER', 'Je récapitule votre commande.', 'Let me confirm your order.', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0002', 'FB_CONFIRM_ORDER', 'Vous avez choisi {dish} et {dish}, c’est bien cela ?', 'You chose {dish} and {dish}, is that correct?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0003', 'FB_CONFIRM_ORDER', 'Avec {side} en accompagnement ?', 'With {side} as a side?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0004', 'FB_CONFIRM_ORDER', 'Et une eau {type}, s’il vous plaît ?', 'And a {type} water, please?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0005', 'FB_CONFIRM_ORDER', 'Parfait, merci.', 'Perfect, thank you.', 'Clôture', 'A1', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0006', 'FB_CONFIRM_ORDER', 'Oui, c’est ça.', 'Yes, that’s correct.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0007', 'FB_CONFIRM_ORDER', 'Non, sans sauce, s’il vous plaît.', 'No, without sauce, please.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0008', 'FB_CONFIRM_ORDER', 'Oui, avec du riz.', 'Yes, with rice.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0009', 'FB_CONFIRM_ORDER', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0010', 'FB_CONFIRM_ORDER', 'Pouvez-vous confirmer la cuisson, s’il vous plaît ?', 'Could you confirm the cooking level, please?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0011', 'FB_CONFIRM_ORDER', 'Je note : saignant / à point / bien cuit.', 'Noted: rare / medium / well done.', 'Information', 'B1', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0012', 'FB_CONFIRM_ORDER', 'Je vérifie aussi les demandes spéciales pour éviter toute erreur.', 'I will also double-check special requests to avoid any mistakes.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0013', 'FB_CONFIRM_ORDER', 'Je veux être sûr(e) : sans gluten, c’est bien noté ?', 'I want to be sure: gluten-free, is it noted?', 'Vérification', 'B1', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0014', 'FB_CONFIRM_ORDER', 'Oui, c’est clairement indiqué, et je le confirme à la cuisine.', 'Yes, it is clearly marked, and I will confirm with the kitchen.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_CONFIRM_ORDER_0015', 'FB_CONFIRM_ORDER', 'Merci, c’est important pour moi.', 'Thank you, it is important to me.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_CONFIRM_ORDER_0016', 'FB_CONFIRM_ORDER', 'Très bien, je m’en occupe.', 'Certainly, I will take care of it.', 'Service', 'B1', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0001', 'FB_SPECIAL_REQUEST', 'Avez-vous une demande particulière ?', 'Do you have any special request?', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0002', 'FB_SPECIAL_REQUEST', 'Nous pouvons adapter l’accompagnement.', 'We can adjust the side dish.', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0003', 'FB_SPECIAL_REQUEST', 'Souhaitez-vous la sauce à part ?', 'Would you like the sauce on the side?', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0004', 'FB_SPECIAL_REQUEST', 'Je vérifie avec la cuisine.', 'I will check with the kitchen.', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0005', 'FB_SPECIAL_REQUEST', 'Très bien, je reviens vers vous.', 'Alright, I will get back to you.', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0006', 'FB_SPECIAL_REQUEST', 'Sans sel, s’il vous plaît.', 'No salt, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0007', 'FB_SPECIAL_REQUEST', 'Je suis enceinte, je préfère bien cuit.', 'I am pregnant, I prefer it well done.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0008', 'FB_SPECIAL_REQUEST', 'Peut-on remplacer les frites par une salade ?', 'Can we replace fries with a salad?', 'Service', 'A2', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0009', 'FB_SPECIAL_REQUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0010', 'FB_SPECIAL_REQUEST', 'Pas de problème. Je confirme la substitution avec la cuisine.', 'No problem. I will confirm the substitution with the kitchen.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0011', 'FB_SPECIAL_REQUEST', 'Selon la disponibilité, nous pouvons aussi proposer {side} en alternative.', 'Depending on availability, we can also offer {side} as an alternative.', 'Service', 'B1', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0012', 'FB_SPECIAL_REQUEST', 'Pour être certain(e), y a-t-il un ingrédient à éviter absolument ?', 'To be sure, is there any ingredient to avoid completely?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0013', 'FB_SPECIAL_REQUEST', 'Oui, pas de noix.', 'Yes, no nuts.', 'Vérification', 'B1', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0014', 'FB_SPECIAL_REQUEST', 'Bien noté. Je le marque comme priorité sécurité alimentaire.', 'Noted. I will mark it as a food-safety priority.', 'Sécurité', 'B1', 'STAFF', null),
('RST_FB_SPECIAL_REQUEST_0015', 'FB_SPECIAL_REQUEST', 'Merci, c’est rassurant.', 'Thank you, that’s reassuring.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_SPECIAL_REQUEST_0016', 'FB_SPECIAL_REQUEST', 'Je vous confirme dans une minute.', 'I will confirm in one minute.', 'Service', 'A2', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0001', 'FB_ALLERGY_CHECK', 'Avez-vous des allergies alimentaires ?', 'Do you have any food allergies?', 'Sécurité', 'A2', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0002', 'FB_ALLERGY_CHECK', 'Je prends cela très au sérieux.', 'I take that very seriously.', 'Sécurité', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0003', 'FB_ALLERGY_CHECK', 'Pouvez-vous préciser l’allergie, s’il vous plaît ?', 'Could you specify the allergy, please?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0004', 'FB_ALLERGY_CHECK', 'Je vérifie les ingrédients avec la cuisine.', 'I will confirm the ingredients with the kitchen.', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0005', 'FB_ALLERGY_CHECK', 'Nous éviterons toute contamination croisée.', 'We will avoid any cross-contamination.', 'Sécurité', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0006', 'FB_ALLERGY_CHECK', 'Je suis allergique aux arachides.', 'I am allergic to peanuts.', 'Sécurité', 'A2', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0007', 'FB_ALLERGY_CHECK', 'Je suis intolérant(e) au gluten.', 'I am gluten intolerant.', 'Sécurité', 'A2', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0008', 'FB_ALLERGY_CHECK', 'Merci de vérifier, s’il vous plaît.', 'Please check, thank you.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0009', 'FB_ALLERGY_CHECK', 'Est-ce sûr à 100% ?', 'Is it 100% safe?', 'Sécurité', 'B1', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0010', 'FB_ALLERGY_CHECK', 'Je confirme avec le chef avant de valider la commande.', 'I will confirm with the chef before confirming the order.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0011', 'FB_ALLERGY_CHECK', 'Si vous préférez, je peux vous recommander deux options clairement adaptées.', 'If you prefer, I can recommend two clearly suitable options.', 'Information', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0012', 'FB_ALLERGY_CHECK', 'Je note l’allergie sur votre commande et sur le ticket cuisine.', 'I will note the allergy on your order and on the kitchen ticket.', 'Sécurité', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0013', 'FB_ALLERGY_CHECK', 'Merci, c’est essentiel.', 'Thank you, that is essential.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0014', 'FB_ALLERGY_CHECK', 'Je préfère une option simple, sans risque.', 'I prefer a simple option, with no risk.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_ALLERGY_CHECK_0015', 'FB_ALLERGY_CHECK', 'Très bien. Je vous propose {dish} sans {ingredient}, validé par la cuisine.', 'Certainly. I suggest {dish} without {ingredient}, confirmed by the kitchen.', 'Service', 'B1', 'STAFF', null),
('RST_FB_ALLERGY_CHECK_0016', 'FB_ALLERGY_CHECK', 'Je reviens vers vous immédiatement.', 'I will come back to you immediately.', 'Service', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0001', 'FB_UPSELL_DRINKS', 'Souhaitez-vous un apéritif ?', 'Would you like an aperitif?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0002', 'FB_UPSELL_DRINKS', 'Nous avons un cocktail maison.', 'We have a signature cocktail.', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0003', 'FB_UPSELL_DRINKS', 'Préférez-vous eau, jus ou soda ?', 'Would you prefer water, juice, or soda?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0004', 'FB_UPSELL_DRINKS', 'Je peux vous proposer un verre de vin au choix.', 'I can suggest a glass of wine.', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0005', 'FB_UPSELL_DRINKS', 'Très bien.', 'Very well.', 'Service', 'A1', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0006', 'FB_UPSELL_DRINKS', 'Un jus d’orange, s’il vous plaît.', 'An orange juice, please.', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0007', 'FB_UPSELL_DRINKS', 'Un verre de vin, s’il vous plaît.', 'A glass of wine, please.', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0008', 'FB_UPSELL_DRINKS', 'Rien pour l’instant, merci.', 'Nothing for now, thank you.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0009', 'FB_UPSELL_DRINKS', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0010', 'FB_UPSELL_DRINKS', 'Je peux vous proposer une boisson sans alcool très populaire, {drink}.', 'I can recommend a popular non-alcoholic drink, {drink}.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0011', 'FB_UPSELL_DRINKS', 'Si vous le souhaitez, je peux accorder la boisson à votre plat.', 'If you wish, I can pair a drink with your dish.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0012', 'FB_UPSELL_DRINKS', 'Avez-vous un budget maximum par verre ?', 'Do you have a maximum budget per glass?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0013', 'FB_UPSELL_DRINKS', 'Oui, autour de {amount} {currency}.', 'Yes, around {amount} {currency}.', 'Vérification', 'B1', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0014', 'FB_UPSELL_DRINKS', 'Parfait. Je vous propose {drink}, c’est dans ce budget.', 'Perfect. I recommend {drink}; it fits that budget.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DRINKS_0015', 'FB_UPSELL_DRINKS', 'D’accord, on fait comme ça.', 'Alright, let’s do that.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_UPSELL_DRINKS_0016', 'FB_UPSELL_DRINKS', 'Je vous sers ça tout de suite.', 'I will serve that right away.', 'Service', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0001', 'FB_UPSELL_DESSERT', 'Souhaitez-vous un dessert ?', 'Would you like a dessert?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0002', 'FB_UPSELL_DESSERT', 'Nous avons aussi des fruits frais.', 'We also have fresh fruit.', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0003', 'FB_UPSELL_DESSERT', 'Un café ou un thé pour terminer ?', 'A coffee or tea to finish?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0004', 'FB_UPSELL_DESSERT', 'Notre dessert signature est {dessert}.', 'Our signature dessert is {dessert}.', 'Information', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0005', 'FB_UPSELL_DESSERT', 'Je reviens avec la carte des desserts.', 'I will be back with the dessert menu.', 'Service', 'A2', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0006', 'FB_UPSELL_DESSERT', 'Un café, s’il vous plaît.', 'A coffee, please.', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0007', 'FB_UPSELL_DESSERT', 'Je suis rassasié(e), merci.', 'I’m full, thank you.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0008', 'FB_UPSELL_DESSERT', 'Un dessert à partager ?', 'A dessert to share?', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0009', 'FB_UPSELL_DESSERT', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0010', 'FB_UPSELL_DESSERT', 'Je peux vous proposer une option légère : {dessert}.', 'I can suggest a light option: {dessert}.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0011', 'FB_UPSELL_DESSERT', 'Si vous êtes pressé(e), je peux vous recommander un dessert rapide.', 'If you are in a hurry, I can recommend a quick dessert.', 'Service', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0012', 'FB_UPSELL_DESSERT', 'Le café peut être servi en même temps, si vous le souhaitez.', 'Coffee can be served at the same time, if you wish.', 'Service', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0013', 'FB_UPSELL_DESSERT', 'Oui, s’il vous plaît, vite.', 'Yes, please, quickly.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0014', 'FB_UPSELL_DESSERT', 'Très bien, je lance ça immédiatement.', 'Certainly, I will place it right away.', 'Service', 'B1', 'STAFF', null),
('RST_FB_UPSELL_DESSERT_0015', 'FB_UPSELL_DESSERT', 'Parfait, merci.', 'Perfect, thank you.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_UPSELL_DESSERT_0016', 'FB_UPSELL_DESSERT', 'Je vous apporte l’addition quand vous voulez.', 'I can bring the bill whenever you are ready.', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0001', 'FB_WINE_RECOMMENDATION', 'Souhaitez-vous une recommandation de vin ?', 'Would you like a wine recommendation?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0002', 'FB_WINE_RECOMMENDATION', 'Plutôt rouge, blanc ou rosé ?', 'Red, white, or rosé?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0003', 'FB_WINE_RECOMMENDATION', 'Voulez-vous une bouteille ou un verre ?', 'Would you like a bottle or a glass?', 'Vente', 'A2', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0004', 'FB_WINE_RECOMMENDATION', 'Je peux proposer un accord avec votre plat.', 'I can suggest a pairing with your dish.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0005', 'FB_WINE_RECOMMENDATION', 'Je reviens avec deux options.', 'I will come back with two options.', 'Service', 'A2', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0006', 'FB_WINE_RECOMMENDATION', 'Un vin rouge, s’il vous plaît.', 'A red wine, please.', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0007', 'FB_WINE_RECOMMENDATION', 'Un verre seulement.', 'Just a glass.', 'Vente', 'A2', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0008', 'FB_WINE_RECOMMENDATION', 'Quel vin va avec le poisson ?', 'Which wine goes with the fish?', 'Information', 'B1', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0009', 'FB_WINE_RECOMMENDATION', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0010', 'FB_WINE_RECOMMENDATION', 'Pour {dish}, je recommande un blanc sec, {wine}.', 'For {dish}, I recommend a dry white, {wine}.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0011', 'FB_WINE_RECOMMENDATION', 'Si vous préférez quelque chose de plus rond, je peux proposer {wine}.', 'If you prefer something fuller-bodied, I can suggest {wine}.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0012', 'FB_WINE_RECOMMENDATION', 'Avez-vous un budget pour la bouteille ?', 'Do you have a budget for the bottle?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0013', 'FB_WINE_RECOMMENDATION', 'Autour de {amount} {currency}.', 'Around {amount} {currency}.', 'Vérification', 'B1', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0014', 'FB_WINE_RECOMMENDATION', 'Dans ce budget, {wine} est excellent et très apprécié.', 'Within that budget, {wine} is excellent and very popular.', 'Vente', 'B1', 'STAFF', null),
('RST_FB_WINE_RECOMMENDATION_0015', 'FB_WINE_RECOMMENDATION', 'Allons-y avec celui-là.', 'Let’s go with that one.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_WINE_RECOMMENDATION_0016', 'FB_WINE_RECOMMENDATION', 'Très bien, je vous le sers immédiatement.', 'Certainly, I will serve it immediately.', 'Service', 'B1', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0001', 'FB_DELAY_APOLOGY', 'Je suis désolé(e) pour l’attente.', 'I’m sorry for the wait.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0002', 'FB_DELAY_APOLOGY', 'Je vais vérifier avec la cuisine.', 'I will check with the kitchen.', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0003', 'FB_DELAY_APOLOGY', 'Votre plat arrive bientôt.', 'Your dish will be out shortly.', 'Information', 'A2', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0004', 'FB_DELAY_APOLOGY', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0005', 'FB_DELAY_APOLOGY', 'Je reviens vers vous rapidement.', 'I will get back to you shortly.', 'Service', 'A2', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0006', 'FB_DELAY_APOLOGY', 'Ça fait longtemps.', 'It’s taking a long time.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0007', 'FB_DELAY_APOLOGY', 'Nous sommes pressés.', 'We are in a hurry.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0008', 'FB_DELAY_APOLOGY', 'Pouvez-vous accélérer ?', 'Could you speed it up?', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0009', 'FB_DELAY_APOLOGY', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0010', 'FB_DELAY_APOLOGY', 'Je comprends parfaitement. Je prends cela en charge personnellement.', 'I completely understand. I will personally take care of this.', 'Conflit', 'B1', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0011', 'FB_DELAY_APOLOGY', 'Je vous donne une estimation fiable dans une minute.', 'I will give you a reliable time estimate in one minute.', 'Service', 'B1', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0012', 'FB_DELAY_APOLOGY', 'Si besoin, je peux vous proposer une alternative plus rapide.', 'If needed, I can offer a faster alternative.', 'Service', 'B1', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0013', 'FB_DELAY_APOLOGY', 'Oui, proposez une alternative.', 'Yes, suggest an alternative.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0014', 'FB_DELAY_APOLOGY', 'Très bien. Je vous propose {dish}, prêt en moins de {time} minutes.', 'Certainly. I suggest {dish}, ready in under {time} minutes.', 'Service', 'B1', 'STAFF', null),
('RST_FB_DELAY_APOLOGY_0015', 'FB_DELAY_APOLOGY', 'Merci, c’est mieux.', 'Thank you, that’s better.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_DELAY_APOLOGY_0016', 'FB_DELAY_APOLOGY', 'Je vous tiens informé(e) tout de suite.', 'I will update you right away.', 'Service', 'B1', 'STAFF', null),
('RST_FB_WRONG_ORDER_0001', 'FB_WRONG_ORDER', 'Je suis désolé(e), ce n’est pas ce que vous aviez commandé.', 'I’m sorry, this is not what you ordered.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_WRONG_ORDER_0002', 'FB_WRONG_ORDER', 'Je vais corriger cela immédiatement.', 'I will fix this immediately.', 'Service', 'A2', 'STAFF', null),
('RST_FB_WRONG_ORDER_0003', 'FB_WRONG_ORDER', 'Pouvez-vous me rappeler votre commande, s’il vous plaît ?', 'Could you remind me of your order, please?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_WRONG_ORDER_0004', 'FB_WRONG_ORDER', 'Je renvoie ce plat en cuisine.', 'I will send this back to the kitchen.', 'Service', 'A2', 'STAFF', null),
('RST_FB_WRONG_ORDER_0005', 'FB_WRONG_ORDER', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_WRONG_ORDER_0006', 'FB_WRONG_ORDER', 'Ce n’est pas mon plat.', 'This is not my dish.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0007', 'FB_WRONG_ORDER', 'J’avais demandé sans sauce.', 'I asked for no sauce.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0008', 'FB_WRONG_ORDER', 'Je n’ai pas commandé ça.', 'I did not order this.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0009', 'FB_WRONG_ORDER', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0010', 'FB_WRONG_ORDER', 'Je comprends, et je vous présente nos excuses.', 'I understand, and please accept our apologies.', 'Conflit', 'B1', 'STAFF', null),
('RST_FB_WRONG_ORDER_0011', 'FB_WRONG_ORDER', 'Je priorise votre plat pour qu’il arrive au plus vite.', 'I will prioritize your dish so it arrives as quickly as possible.', 'Service', 'B1', 'STAFF', null),
('RST_FB_WRONG_ORDER_0012', 'FB_WRONG_ORDER', 'Souhaitez-vous garder ce plat pendant que nous refaisons le bon ?', 'Would you like to keep this dish while we remake the correct one?', 'Service', 'B1', 'STAFF', null),
('RST_FB_WRONG_ORDER_0013', 'FB_WRONG_ORDER', 'Non, je préfère attendre le bon plat.', 'No, I’d rather wait for the correct dish.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0014', 'FB_WRONG_ORDER', 'Très bien. Je vous propose une boisson offerte pendant l’attente.', 'Certainly. I can offer you a complimentary drink while you wait.', 'Service', 'B1', 'STAFF', null),
('RST_FB_WRONG_ORDER_0015', 'FB_WRONG_ORDER', 'D’accord, merci.', 'Alright, thank you.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_WRONG_ORDER_0016', 'FB_WRONG_ORDER', 'Je reviens vers vous dans {time} minutes avec une mise à jour.', 'I will come back in {time} minutes with an update.', 'Service', 'B1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0001', 'FB_COLD_FOOD_COMPLAINT', 'Je suis désolé(e) d’apprendre cela.', 'I’m sorry to hear that.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0002', 'FB_COLD_FOOD_COMPLAINT', 'Je peux le faire réchauffer ou le remplacer.', 'I can have it reheated or replaced.', 'Service', 'A2', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0003', 'FB_COLD_FOOD_COMPLAINT', 'Je vais prévenir la cuisine.', 'I will inform the kitchen.', 'Service', 'A2', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0004', 'FB_COLD_FOOD_COMPLAINT', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0005', 'FB_COLD_FOOD_COMPLAINT', 'Je reviens tout de suite.', 'I’ll be right back.', 'Service', 'A1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0006', 'FB_COLD_FOOD_COMPLAINT', 'Mon plat est froid.', 'My food is cold.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0007', 'FB_COLD_FOOD_COMPLAINT', 'Je veux que ce soit refait.', 'I want it remade.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0008', 'FB_COLD_FOOD_COMPLAINT', 'C’est vraiment décevant.', 'This is really disappointing.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0009', 'FB_COLD_FOOD_COMPLAINT', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0010', 'FB_COLD_FOOD_COMPLAINT', 'Je comprends parfaitement. Nous allons corriger cela immédiatement.', 'I completely understand. We will fix this immediately.', 'Conflit', 'B1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0011', 'FB_COLD_FOOD_COMPLAINT', 'Préférez-vous un remplacement complet, ou un réchauffage rapide ?', 'Would you prefer a full replacement, or a quick reheat?', 'Service', 'B1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0012', 'FB_COLD_FOOD_COMPLAINT', 'Un remplacement complet.', 'A full replacement.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0013', 'FB_COLD_FOOD_COMPLAINT', 'Très bien. Je priorise votre plat en cuisine et je vous donne un délai clair.', 'Certainly. I will prioritize it in the kitchen and give you a clear time.', 'Service', 'B1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0014', 'FB_COLD_FOOD_COMPLAINT', 'Et un geste commercial ?', 'And a goodwill gesture?', 'Conflit', 'B1', 'CLIENT', null),
('RST_FB_COLD_FOOD_COMPLAINT_0015', 'FB_COLD_FOOD_COMPLAINT', 'Je comprends. Je peux demander à mon responsable un geste adapté après vérification.', 'I understand. I can ask my manager for an appropriate gesture after verification.', 'Paiement', 'B1', 'STAFF', null),
('RST_FB_COLD_FOOD_COMPLAINT_0016', 'FB_COLD_FOOD_COMPLAINT', 'Merci, tenez-moi au courant.', 'Thank you, keep me updated.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0001', 'FB_BILL_REQUEST', 'Souhaitez-vous l’addition ?', 'Would you like the bill?', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_BILL_REQUEST_0002', 'FB_BILL_REQUEST', 'Je vous apporte l’addition tout de suite.', 'I will bring the bill right away.', 'Service', 'A2', 'STAFF', null),
('RST_FB_BILL_REQUEST_0003', 'FB_BILL_REQUEST', 'C’est pour payer par carte ou en espèces ?', 'Will you pay by card or cash?', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_BILL_REQUEST_0004', 'FB_BILL_REQUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'STAFF', null),
('RST_FB_BILL_REQUEST_0005', 'FB_BILL_REQUEST', 'Je reviens avec le terminal.', 'I will be back with the card machine.', 'Service', 'A2', 'STAFF', null),
('RST_FB_BILL_REQUEST_0006', 'FB_BILL_REQUEST', 'L’addition, s’il vous plaît.', 'The bill, please.', 'Clôture', 'A2', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0007', 'FB_BILL_REQUEST', 'Par carte, s’il vous plaît.', 'By card, please.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0008', 'FB_BILL_REQUEST', 'En espèces.', 'In cash.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0009', 'FB_BILL_REQUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0010', 'FB_BILL_REQUEST', 'Souhaitez-vous un reçu ?', 'Would you like a receipt?', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_BILL_REQUEST_0011', 'FB_BILL_REQUEST', 'Je peux vous envoyer le reçu par email si vous préférez.', 'I can email you the receipt if you prefer.', 'Clôture', 'B1', 'STAFF', null),
('RST_FB_BILL_REQUEST_0012', 'FB_BILL_REQUEST', 'Votre société a-t-elle besoin d’une mention particulière ?', 'Does your company need any specific details on the receipt?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_BILL_REQUEST_0013', 'FB_BILL_REQUEST', 'Oui, au nom de {company}.', 'Yes, under the name {company}.', 'Vérification', 'B1', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0014', 'FB_BILL_REQUEST', 'Très bien, je le note et je vous imprime le reçu.', 'Certainly, I will note it and print the receipt.', 'Service', 'B1', 'STAFF', null),
('RST_FB_BILL_REQUEST_0015', 'FB_BILL_REQUEST', 'Parfait, merci.', 'Perfect, thank you.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_BILL_REQUEST_0016', 'FB_BILL_REQUEST', 'Je reviens dans une minute.', 'I will be back in one minute.', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPLIT_BILL_0001', 'FB_SPLIT_BILL', 'Souhaitez-vous séparer l’addition ?', 'Would you like to split the bill?', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_SPLIT_BILL_0002', 'FB_SPLIT_BILL', 'En combien de parts ?', 'Into how many parts?', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_SPLIT_BILL_0003', 'FB_SPLIT_BILL', 'Je peux séparer par plats ou par personnes.', 'I can split by items or by guests.', 'Paiement', 'B1', 'STAFF', null),
('RST_FB_SPLIT_BILL_0004', 'FB_SPLIT_BILL', 'Très bien, je prépare cela.', 'Alright, I will prepare that.', 'Service', 'A2', 'STAFF', null),
('RST_FB_SPLIT_BILL_0005', 'FB_SPLIT_BILL', 'Merci pour votre patience.', 'Thank you for your patience.', 'Conflit', 'A2', 'STAFF', null),
('RST_FB_SPLIT_BILL_0006', 'FB_SPLIT_BILL', 'Deux additions séparées, s’il vous plaît.', 'Two separate bills, please.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0007', 'FB_SPLIT_BILL', 'Une partie sur carte société.', 'One part on the company card.', 'Paiement', 'B1', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0008', 'FB_SPLIT_BILL', 'Je suis pressé(e).', 'I’m in a hurry.', 'Conflit', 'A2', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0009', 'FB_SPLIT_BILL', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0010', 'FB_SPLIT_BILL', 'Je comprends. Je vais faire au plus vite sans erreur.', 'I understand. I will do it as quickly as possible without mistakes.', 'Conflit', 'B1', 'STAFF', null),
('RST_FB_SPLIT_BILL_0011', 'FB_SPLIT_BILL', 'Pouvez-vous me dire précisément quels articles vont sur chaque facture ?', 'Could you tell me exactly which items should go on each bill?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_SPLIT_BILL_0012', 'FB_SPLIT_BILL', 'Les boissons sur la facture 2.', 'Drinks on bill 2.', 'Paiement', 'B1', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0013', 'FB_SPLIT_BILL', 'Très bien. Je vous montre le détail avant paiement.', 'Certainly. I will show you the breakdown before payment.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_SPLIT_BILL_0014', 'FB_SPLIT_BILL', 'Merci, c’est important.', 'Thank you, that matters.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_SPLIT_BILL_0015', 'FB_SPLIT_BILL', 'Je peux aussi faire un split égal si vous préférez.', 'I can also split equally if you prefer.', 'Paiement', 'B1', 'STAFF', null),
('RST_FB_SPLIT_BILL_0016', 'FB_SPLIT_BILL', 'Split égal, oui.', 'Equal split, yes.', 'Paiement', 'B1', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0001', 'FB_PAYMENT_CARD_ISSUE', 'Je suis désolé(e), votre carte a été refusée.', 'I’m sorry, your card was declined.', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0002', 'FB_PAYMENT_CARD_ISSUE', 'Souhaitez-vous essayer une autre carte ?', 'Would you like to try another card?', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0003', 'FB_PAYMENT_CARD_ISSUE', 'Vous pouvez aussi payer en espèces.', 'You can also pay in cash.', 'Paiement', 'A2', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0004', 'FB_PAYMENT_CARD_ISSUE', 'Je relance le paiement.', 'I will run the payment again.', 'Service', 'A2', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0005', 'FB_PAYMENT_CARD_ISSUE', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0006', 'FB_PAYMENT_CARD_ISSUE', 'Ça ne passe pas ?', 'It doesn’t work?', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0007', 'FB_PAYMENT_CARD_ISSUE', 'Essayons une autre carte.', 'Let’s try another card.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0008', 'FB_PAYMENT_CARD_ISSUE', 'Je n’ai pas d’autre carte.', 'I don’t have another card.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0009', 'FB_PAYMENT_CARD_ISSUE', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0010', 'FB_PAYMENT_CARD_ISSUE', 'Je comprends. Selon votre préférence, nous pouvons faire un virement ou un paiement mobile si disponible.', 'I understand. If you prefer, we can do a bank transfer or mobile payment if available.', 'Paiement', 'B1', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0011', 'FB_PAYMENT_CARD_ISSUE', 'Souhaitez-vous que je vous guide sur une solution rapide ?', 'Would you like me to guide you to a quick solution?', 'Service', 'B1', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0012', 'FB_PAYMENT_CARD_ISSUE', 'Oui, rapidement.', 'Yes, quickly.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0013', 'FB_PAYMENT_CARD_ISSUE', 'Très bien. Nous pouvons utiliser {payment_method} ou régler en espèces.', 'Certainly. We can use {payment_method} or settle in cash.', 'Paiement', 'B1', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0014', 'FB_PAYMENT_CARD_ISSUE', 'Je peux aussi appeler mon responsable si vous préférez.', 'I can also call my manager if you prefer.', 'Service', 'B1', 'STAFF', null),
('RST_FB_PAYMENT_CARD_ISSUE_0015', 'FB_PAYMENT_CARD_ISSUE', 'Oui, appelez-le.', 'Yes, call them.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_PAYMENT_CARD_ISSUE_0016', 'FB_PAYMENT_CARD_ISSUE', 'Je m’en occupe immédiatement.', 'I will take care of it immediately.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0001', 'FB_GROUP_RESERVATION', 'Vous avez une réservation de groupe ?', 'Do you have a group reservation?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0002', 'FB_GROUP_RESERVATION', 'Pour combien de personnes ?', 'For how many people?', 'Vérification', 'A2', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0003', 'FB_GROUP_RESERVATION', 'Avez-vous des contraintes de temps ?', 'Do you have any time constraints?', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0004', 'FB_GROUP_RESERVATION', 'Nous pouvons proposer un menu fixe.', 'We can offer a set menu.', 'Service', 'A2', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0005', 'FB_GROUP_RESERVATION', 'Je confirme avec vous l’organisation.', 'I will confirm the organization with you.', 'Service', 'A2', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0006', 'FB_GROUP_RESERVATION', 'Oui, nous sommes {time}.', 'Yes, we are {time}.', 'Vérification', 'A2', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0007', 'FB_GROUP_RESERVATION', 'Nous avons un timing serré.', 'We have a tight schedule.', 'Conflit', 'B1', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0008', 'FB_GROUP_RESERVATION', 'On veut payer ensemble.', 'We want to pay together.', 'Paiement', 'A2', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0009', 'FB_GROUP_RESERVATION', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0010', 'FB_GROUP_RESERVATION', 'Je comprends. Pour gagner du temps, je vous propose un menu fixe et une prise de commande groupée.', 'I understand. To save time, I suggest a set menu and a grouped order.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0011', 'FB_GROUP_RESERVATION', 'Souhaitez-vous que les boissons soient servies dès maintenant ?', 'Would you like drinks served right away?', 'Vente', 'B1', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0012', 'FB_GROUP_RESERVATION', 'Oui, s’il vous plaît.', 'Yes, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0013', 'FB_GROUP_RESERVATION', 'Très bien. Je synchronise avec la cuisine et je vous donne un timing clair.', 'Certainly. I will coordinate with the kitchen and give you a clear timing.', 'Service', 'B1', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0014', 'FB_GROUP_RESERVATION', 'Parfait. Merci pour l’organisation.', 'Perfect. Thank you for organizing.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_GROUP_RESERVATION_0015', 'FB_GROUP_RESERVATION', 'Je reviens vers vous dans {time} minutes.', 'I will be back in {time} minutes.', 'Service', 'A2', 'STAFF', null),
('RST_FB_GROUP_RESERVATION_0016', 'FB_GROUP_RESERVATION', 'Nous avons aussi des options végétariennes pour le groupe.', 'We also have vegetarian options for the group.', 'Information', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0001', 'FB_VIP_TABLE', 'Nous avons une table réservée pour vous.', 'We have a table reserved for you.', 'Accueil', 'A2', 'STAFF', null),
('RST_FB_VIP_TABLE_0002', 'FB_VIP_TABLE', 'Bienvenue, {guest_name}.', 'Welcome, {guest_name}.', 'Accueil', 'A2', 'STAFF', null),
('RST_FB_VIP_TABLE_0003', 'FB_VIP_TABLE', 'Souhaitez-vous un apéritif offert ?', 'Would you like a complimentary aperitif?', 'Service', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0004', 'FB_VIP_TABLE', 'Je m’assure que tout soit parfait.', 'I will make sure everything is perfect.', 'Service', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0005', 'FB_VIP_TABLE', 'Je reviens dans un instant.', 'I will be back shortly.', 'Service', 'A2', 'STAFF', null),
('RST_FB_VIP_TABLE_0006', 'FB_VIP_TABLE', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_VIP_TABLE_0007', 'FB_VIP_TABLE', 'Nous préférons une table discrète.', 'We prefer a discreet table.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_VIP_TABLE_0008', 'FB_VIP_TABLE', 'Bien sûr. Je vous installe dans un espace plus privé.', 'Of course. I will seat you in a more private area.', 'Service', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0009', 'FB_VIP_TABLE', 'Pouvez-vous accélérer le service ?', 'Could you speed up the service?', 'Service', 'B1', 'CLIENT', null),
('RST_FB_VIP_TABLE_0010', 'FB_VIP_TABLE', 'Bien entendu. Je coordonne directement avec la cuisine.', 'Certainly. I will coordinate directly with the kitchen.', 'Service', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0011', 'FB_VIP_TABLE', 'Souhaitez-vous que je prenne la commande immédiatement ?', 'Would you like me to take the order immediately?', 'Service', 'B1', 'STAFF', null),
('RST_FB_VIP_TABLE_0012', 'FB_VIP_TABLE', 'Oui, s’il vous plaît.', 'Yes, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_VIP_TABLE_0013', 'FB_VIP_TABLE', 'Très bien. Que puis-je vous proposer ?', 'Certainly. What may I offer you?', 'Service', 'A2', 'STAFF', null),
('RST_FB_VIP_TABLE_0014', 'FB_VIP_TABLE', 'Un verre d’eau, s’il vous plaît.', 'A glass of water, please.', 'Service', 'A1', 'CLIENT', null),
('RST_FB_VIP_TABLE_0015', 'FB_VIP_TABLE', 'Tout est excellent.', 'Everything is excellent.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_VIP_TABLE_0016', 'FB_VIP_TABLE', 'Merci beaucoup. Votre retour nous fait plaisir.', 'Thank you very much. We truly appreciate your feedback.', 'Clôture', 'B1', 'STAFF', null),
('RST_FB_CHILD_MENU_0001', 'FB_CHILD_MENU', 'Avez-vous besoin d’un menu enfant ?', 'Do you need a kids’ menu?', 'Service', 'A2', 'STAFF', null),
('RST_FB_CHILD_MENU_0002', 'FB_CHILD_MENU', 'Nous avons des plats adaptés aux enfants.', 'We have child-friendly dishes.', 'Information', 'A2', 'STAFF', null),
('RST_FB_CHILD_MENU_0003', 'FB_CHILD_MENU', 'Souhaitez-vous une chaise bébé ?', 'Would you like a high chair?', 'Service', 'A2', 'STAFF', null),
('RST_FB_CHILD_MENU_0004', 'FB_CHILD_MENU', 'Je peux apporter des crayons.', 'I can bring crayons.', 'Service', 'A2', 'STAFF', null),
('RST_FB_CHILD_MENU_0005', 'FB_CHILD_MENU', 'Très bien.', 'Very well.', 'Service', 'A1', 'STAFF', null),
('RST_FB_CHILD_MENU_0006', 'FB_CHILD_MENU', 'Oui, un menu enfant.', 'Yes, a kids’ menu.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_CHILD_MENU_0007', 'FB_CHILD_MENU', 'Une chaise bébé, s’il vous plaît.', 'A high chair, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_CHILD_MENU_0008', 'FB_CHILD_MENU', 'Sans épices pour l’enfant.', 'No spices for the child.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_CHILD_MENU_0009', 'FB_CHILD_MENU', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_CHILD_MENU_0010', 'FB_CHILD_MENU', 'Je comprends. Je note ‘non épicé’ et je le confirme à la cuisine.', 'Understood. I will note ‘not spicy’ and confirm with the kitchen.', 'Vérification', 'B1', 'STAFF', null),
('RST_FB_CHILD_MENU_0011', 'FB_CHILD_MENU', 'Si vous le souhaitez, nous pouvons servir l’enfant en premier.', 'If you wish, we can serve the child first.', 'Service', 'B1', 'STAFF', null),
('RST_FB_CHILD_MENU_0012', 'FB_CHILD_MENU', 'Oui, ce serait bien.', 'Yes, that would be great.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_CHILD_MENU_0013', 'FB_CHILD_MENU', 'Parfait. Je m’en occupe.', 'Perfect. I will take care of it.', 'Service', 'B1', 'STAFF', null),
('RST_FB_CHILD_MENU_0014', 'FB_CHILD_MENU', 'Avez-vous des allergies pour l’enfant ?', 'Does the child have any allergies?', 'Sécurité', 'B1', 'STAFF', null),
('RST_FB_CHILD_MENU_0015', 'FB_CHILD_MENU', 'Non, aucune.', 'No, none.', 'Sécurité', 'A2', 'CLIENT', null),
('RST_FB_CHILD_MENU_0016', 'FB_CHILD_MENU', 'Très bien. Je reviens vers vous.', 'Alright. I will come back to you.', 'Service', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0001', 'FB_FEEDBACK_REQUEST', 'Tout s’est bien passé ?', 'Was everything alright?', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0002', 'FB_FEEDBACK_REQUEST', 'Avez-vous apprécié votre repas ?', 'Did you enjoy your meal?', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0003', 'FB_FEEDBACK_REQUEST', 'Y a-t-il quelque chose que nous pouvons améliorer ?', 'Is there anything we can improve?', 'Clôture', 'B1', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0004', 'FB_FEEDBACK_REQUEST', 'Merci pour votre retour.', 'Thank you for your feedback.', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0005', 'FB_FEEDBACK_REQUEST', 'Nous espérons vous revoir bientôt.', 'We hope to see you again soon.', 'Clôture', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0006', 'FB_FEEDBACK_REQUEST', 'Oui, très bien.', 'Yes, very good.', 'Clôture', 'A2', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0007', 'FB_FEEDBACK_REQUEST', 'Le service était un peu lent.', 'The service was a bit slow.', 'Conflit', 'B1', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0008', 'FB_FEEDBACK_REQUEST', 'Le plat était excellent.', 'The dish was excellent.', 'Clôture', 'B1', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0009', 'FB_FEEDBACK_REQUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0010', 'FB_FEEDBACK_REQUEST', 'Je suis désolé(e) d’apprendre cela. Je vais transmettre immédiatement.', 'I’m sorry to hear that. I will report it immediately.', 'Conflit', 'B1', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0011', 'FB_FEEDBACK_REQUEST', 'Merci de nous aider à améliorer notre service.', 'Thank you for helping us improve our service.', 'Clôture', 'B1', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0012', 'FB_FEEDBACK_REQUEST', 'Souhaitez-vous que je note votre remarque ?', 'Would you like me to note your comment?', 'Service', 'A2', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0013', 'FB_FEEDBACK_REQUEST', 'Oui, s’il vous plaît.', 'Yes, please.', 'Service', 'A2', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0014', 'FB_FEEDBACK_REQUEST', 'Si vous le souhaitez, je peux organiser un suivi par email.', 'If you wish, I can arrange a follow-up by email.', 'Service', 'B1', 'STAFF', null),
('RST_FB_FEEDBACK_REQUEST_0015', 'FB_FEEDBACK_REQUEST', 'Oui, envoyez-moi le lien pour l’avis.', 'Yes, send me the review link.', 'Service', 'B1', 'CLIENT', null),
('RST_FB_FEEDBACK_REQUEST_0016', 'FB_FEEDBACK_REQUEST', 'Bien sûr. Je vous l’envoie immédiatement.', 'Of course. I will send it right away.', 'Service', 'B1', 'STAFF', null)

on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

commit;