begin;
-- 320 phrases (Housekeeping 4 étoiles)
insert into phrases (id, action_id, phrase_fr, phrase_en, phase, niveau, voice_type, audio_url) values
('HK_HK_ROOM_CLEAN_0001', 'HK_ROOM_CLEAN', 'Housekeeping, bonjour. Puis-je entrer ?', 'Housekeeping, good morning. May I come in?', 'Accueil', 'A1', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0002', 'HK_ROOM_CLEAN', 'Je viens pour le service de chambre.', 'I am here for your room service.', 'Information', 'A1', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0003', 'HK_ROOM_CLEAN', 'Souhaitez-vous que je repasse plus tard ?', 'Would you like me to come back later?', 'Service', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0004', 'HK_ROOM_CLEAN', 'À quelle heure vous convient-il ?', 'What time suits you?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0005', 'HK_ROOM_CLEAN', 'Je vais ouvrir les rideaux et aérer la chambre.', 'I will open the curtains and air the room.', 'Service', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0006', 'HK_ROOM_CLEAN', 'Je peux prendre vos serviettes utilisées ?', 'May I collect your used towels?', 'Service', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0007', 'HK_ROOM_CLEAN', 'Je vais faire le lit maintenant.', 'I will make the bed now.', 'Service', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0008', 'HK_ROOM_CLEAN', 'Je reviens dans {time} minutes, d’accord ?', 'I will be back in {time} minutes, is that okay?', 'Information', 'A2', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0009', 'HK_ROOM_CLEAN', 'Oui, vous pouvez entrer.', 'Yes, you may come in.', 'Accueil', 'A1', 'CLIENT', null),
('HK_HK_ROOM_CLEAN_0010', 'HK_ROOM_CLEAN', 'Revenez plus tard, s’il vous plaît.', 'Please come back later.', 'Service', 'A1', 'CLIENT', null),
('HK_HK_ROOM_CLEAN_0011', 'HK_ROOM_CLEAN', 'Pouvez-vous nettoyer la salle de bain aussi ?', 'Could you clean the bathroom as well?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_ROOM_CLEAN_0012', 'HK_ROOM_CLEAN', 'Merci, je serai prêt(e) dans {time} minutes.', 'Thank you, I will be ready in {time} minutes.', 'Information', 'A2', 'CLIENT', null),
('HK_HK_ROOM_CLEAN_0013', 'HK_ROOM_CLEAN', 'Je comprends. Je reprogramme le service à {time} et je le note au système.', 'I understand. I will reschedule the service for {time} and note it in the system.', 'Service', 'B1', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0014', 'HK_ROOM_CLEAN', 'Pour votre confort, je peux effectuer un service rapide maintenant et un service complet plus tard.', 'For your comfort, I can do a quick refresh now and a full service later.', 'Service', 'B1', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0015', 'HK_ROOM_CLEAN', 'Merci pour votre patience. Je vérifie la chambre avant de sortir.', 'Thank you for your patience. I will check the room before I leave.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_ROOM_CLEAN_0016', 'HK_ROOM_CLEAN', 'Tout est terminé. Y a-t-il autre chose que je puisse faire pour vous ?', 'All done. Is there anything else I can do for you?', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0001', 'HK_TURNDOWN', 'Bonsoir, Housekeeping. Puis-je entrer pour le service couverture ?', 'Good evening, Housekeeping. May I come in for turndown service?', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0002', 'HK_TURNDOWN', 'Je vais préparer la chambre pour la nuit.', 'I will prepare the room for the night.', 'Information', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0003', 'HK_TURNDOWN', 'Souhaitez-vous des oreillers supplémentaires ?', 'Would you like extra pillows?', 'Service', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0004', 'HK_TURNDOWN', 'Préférez-vous une lumière tamisée ?', 'Would you prefer dimmed lighting?', 'Service', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0005', 'HK_TURNDOWN', 'Je peux ajuster la climatisation si vous le souhaitez.', 'I can adjust the air conditioning if you wish.', 'Service', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0006', 'HK_TURNDOWN', 'Je vais laisser une bouteille d’eau sur la table de nuit.', 'I will place a bottle of water on the bedside table.', 'Service', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0007', 'HK_TURNDOWN', 'Je ferme les rideaux et je range légèrement la chambre.', 'I will close the curtains and tidy the room lightly.', 'Service', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0008', 'HK_TURNDOWN', 'Le service est terminé. Je vous souhaite une bonne nuit.', 'The service is complete. Have a good night.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_TURNDOWN_0009', 'HK_TURNDOWN', 'Oui, entrez.', 'Yes, come in.', 'Accueil', 'A1', 'CLIENT', null),
('HK_HK_TURNDOWN_0010', 'HK_TURNDOWN', 'Pas ce soir, merci.', 'Not tonight, thank you.', 'Service', 'A1', 'CLIENT', null),
('HK_HK_TURNDOWN_0011', 'HK_TURNDOWN', 'Pouvez-vous apporter une couverture supplémentaire ?', 'Could you bring an extra blanket?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_TURNDOWN_0012', 'HK_TURNDOWN', 'Pouvez-vous baisser la climatisation ?', 'Could you lower the air conditioning?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_TURNDOWN_0013', 'HK_TURNDOWN', 'Bien sûr. Je vous apporte une couverture dans {time} minutes.', 'Of course. I will bring a blanket within {time} minutes.', 'Service', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0014', 'HK_TURNDOWN', 'Je comprends. Je note votre préférence et je ne repasserai pas ce soir.', 'I understand. I will note your preference and will not return tonight.', 'Service', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0015', 'HK_TURNDOWN', 'Souhaitez-vous que je programme un service couverture à une heure précise demain ?', 'Would you like me to schedule turndown at a specific time tomorrow?', 'Information', 'B1', 'STAFF', null),
('HK_HK_TURNDOWN_0016', 'HK_TURNDOWN', 'Merci. N’hésitez pas à appeler si vous avez besoin de quoi que ce soit.', 'Thank you. Please call if you need anything.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0001', 'HK_LINEN_CHANGE', 'Bonjour, je viens pour changer les draps et les serviettes.', 'Good morning, I am here to change the sheets and towels.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0002', 'HK_LINEN_CHANGE', 'Puis-je entrer dans la chambre {room_number} ?', 'May I enter room {room_number}?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0003', 'HK_LINEN_CHANGE', 'Souhaitez-vous des draps supplémentaires ?', 'Would you like extra sheets?', 'Service', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0004', 'HK_LINEN_CHANGE', 'Je remplace les serviettes maintenant.', 'I will replace the towels now.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0005', 'HK_LINEN_CHANGE', 'Préférez-vous des serviettes de bain ou des serviettes visage en plus ?', 'Would you prefer extra bath towels or face towels?', 'Service', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0006', 'HK_LINEN_CHANGE', 'Je peux changer les draps aujourd’hui et repasser demain, si vous préférez.', 'I can change the sheets today and come back tomorrow, if you prefer.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0007', 'HK_LINEN_CHANGE', 'Je récupère le linge sale, s’il vous plaît.', 'I will collect the used linen, please.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0008', 'HK_LINEN_CHANGE', 'C’est terminé. Merci.', 'It is done. Thank you.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0009', 'HK_LINEN_CHANGE', 'Oui, merci. Changez-les.', 'Yes, please. Change them.', 'Service', 'A1', 'CLIENT', null),
('HK_HK_LINEN_CHANGE_0010', 'HK_LINEN_CHANGE', 'Je n’ai pas besoin de changer les draps aujourd’hui.', 'I don''t need the sheets changed today.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LINEN_CHANGE_0011', 'HK_LINEN_CHANGE', 'Pouvez-vous ajouter deux serviettes, s’il vous plaît ?', 'Could you add two towels, please?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LINEN_CHANGE_0012', 'HK_LINEN_CHANGE', 'Où puis-je mettre le linge sale ?', 'Where should I put the used linen?', 'Information', 'A2', 'CLIENT', null),
('HK_HK_LINEN_CHANGE_0013', 'HK_LINEN_CHANGE', 'Je comprends. Je note ''no linen change today'' et je repasse demain.', 'I understand. I will note ''no linen change today'' and come back tomorrow.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0014', 'HK_LINEN_CHANGE', 'Bien sûr. Je vous apporte deux serviettes propres dans {time} minutes.', 'Of course. I will bring two clean towels within {time} minutes.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0015', 'HK_LINEN_CHANGE', 'Pour votre confort, je peux aussi remplacer le tapis de bain.', 'For your comfort, I can also replace the bath mat.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LINEN_CHANGE_0016', 'HK_LINEN_CHANGE', 'Tout est propre et complet. Souhaitez-vous autre chose ?', 'Everything is clean and complete. Would you like anything else?', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0001', 'HK_AMENITIES', 'Bonjour, je viens réassortir les produits de salle de bain.', 'Good morning, I am here to restock the bathroom amenities.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_AMENITIES_0002', 'HK_AMENITIES', 'Je remets du savon, du shampooing et des mouchoirs.', 'I am replacing soap, shampoo and tissues.', 'Service', 'A2', 'STAFF', null),
('HK_HK_AMENITIES_0003', 'HK_AMENITIES', 'Souhaitez-vous des produits supplémentaires ?', 'Would you like extra amenities?', 'Service', 'A2', 'STAFF', null),
('HK_HK_AMENITIES_0004', 'HK_AMENITIES', 'Je peux apporter un kit rasage ou un kit dentaire.', 'I can bring a shaving kit or a dental kit.', 'Service', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0005', 'HK_AMENITIES', 'Préférez-vous des produits sans parfum ?', 'Would you prefer fragrance-free products?', 'Service', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0006', 'HK_AMENITIES', 'Je remplace aussi l’eau et les capsules, si nécessaire.', 'I can also replace water and coffee capsules if needed.', 'Service', 'A2', 'STAFF', null),
('HK_HK_AMENITIES_0007', 'HK_AMENITIES', 'Je reviens avec les articles demandés.', 'I will come back with the requested items.', 'Service', 'A2', 'STAFF', null),
('HK_HK_AMENITIES_0008', 'HK_AMENITIES', 'Voici, avec plaisir.', 'Here you are, with pleasure.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_AMENITIES_0009', 'HK_AMENITIES', 'Pouvez-vous apporter du shampooing, s’il vous plaît ?', 'Could you bring shampoo, please?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_AMENITIES_0010', 'HK_AMENITIES', 'J’ai besoin d’un kit dentaire.', 'I need a dental kit.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_AMENITIES_0011', 'HK_AMENITIES', 'Avez-vous du gel douche en plus ?', 'Do you have extra shower gel?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_AMENITIES_0012', 'HK_AMENITIES', 'Merci, c’est parfait.', 'Thank you, that’s perfect.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_AMENITIES_0013', 'HK_AMENITIES', 'Bien sûr. Je vous apporte cela dans {time} minutes.', 'Of course. I will bring it within {time} minutes.', 'Service', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0014', 'HK_AMENITIES', 'Je note votre préférence pour que ce soit prêt chaque jour.', 'I will note your preference so it is ready every day.', 'Information', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0015', 'HK_AMENITIES', 'Si vous manquez de quoi que ce soit, contactez-nous à tout moment.', 'If you need anything, please contact us anytime.', 'Information', 'B1', 'STAFF', null),
('HK_HK_AMENITIES_0016', 'HK_AMENITIES', 'Merci. Je vous souhaite une excellente journée.', 'Thank you. Have a wonderful day.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0001', 'HK_MINIBAR_CHECK', 'Bonjour, je fais un contrôle minibar rapide.', 'Good morning, I am doing a quick minibar check.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0002', 'HK_MINIBAR_CHECK', 'Je ne facture rien : je signale seulement au desk si nécessaire.', 'I do not charge anything: I only report to the front desk if needed.', 'Information', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0003', 'HK_MINIBAR_CHECK', 'Puis-je vérifier le minibar, s’il vous plaît ?', 'May I check the minibar, please?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0004', 'HK_MINIBAR_CHECK', 'Merci. Cela prendra {time} minute(s).', 'Thank you. It will take {time} minute(s).', 'Information', 'A2', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0005', 'HK_MINIBAR_CHECK', 'Je note les consommations pour la vérification.', 'I am noting the items for verification.', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0006', 'HK_MINIBAR_CHECK', 'Je vais confirmer l’inventaire avec la réception.', 'I will confirm the inventory with the front desk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0007', 'HK_MINIBAR_CHECK', 'Si vous avez une question sur la facture, la réception pourra vous aider.', 'If you have a billing question, the front desk can assist you.', 'Information', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0008', 'HK_MINIBAR_CHECK', 'Merci, c’est terminé.', 'Thank you, it is done.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0009', 'HK_MINIBAR_CHECK', 'Oui, allez-y.', 'Yes, go ahead.', 'Accueil', 'A1', 'CLIENT', null),
('HK_HK_MINIBAR_CHECK_0010', 'HK_MINIBAR_CHECK', 'Pourquoi vous vérifiez le minibar ?', 'Why are you checking the minibar?', 'Vérification', 'A2', 'CLIENT', null),
('HK_HK_MINIBAR_CHECK_0011', 'HK_MINIBAR_CHECK', 'Je n’ai rien consommé.', 'I did not take anything.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_MINIBAR_CHECK_0012', 'HK_MINIBAR_CHECK', 'Je veux que ce soit clair sur ma facture.', 'I want this to be clear on my bill.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_MINIBAR_CHECK_0013', 'HK_MINIBAR_CHECK', 'Je comprends. Je vais transmettre l’information au desk pour éviter toute confusion.', 'I understand. I will share this with the front desk to avoid any confusion.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0014', 'HK_MINIBAR_CHECK', 'Merci. Pour votre confort, je peux faire un inventaire devant vous.', 'Thank you. For your comfort, I can check the items in front of you.', 'Service', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0015', 'HK_MINIBAR_CHECK', 'Je note ''no consumption declared'' et je remonte immédiatement.', 'I will note ''no consumption declared'' and report it immediately.', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_MINIBAR_CHECK_0016', 'HK_MINIBAR_CHECK', 'Merci de votre coopération.', 'Thank you for your cooperation.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_DND_0001', 'HK_DND', 'Bonjour, je vois le panneau ''Do Not Disturb''.', 'Good morning, I see the ''Do Not Disturb'' sign.', 'Information', 'A2', 'STAFF', null),
('HK_HK_DND_0002', 'HK_DND', 'Je repasserai plus tard pour le service.', 'I will come back later for service.', 'Service', 'A2', 'STAFF', null),
('HK_HK_DND_0003', 'HK_DND', 'Souhaitez-vous que nous programmions un horaire ?', 'Would you like us to schedule a time?', 'Service', 'B1', 'STAFF', null),
('HK_HK_DND_0004', 'HK_DND', 'Pour votre sécurité, nous devons confirmer que tout va bien.', 'For your safety, we need to confirm that everything is fine.', 'Information', 'B1', 'STAFF', null),
('HK_HK_DND_0005', 'HK_DND', 'Je peux laisser des serviettes propres devant la porte, si vous préférez.', 'I can leave clean towels outside the door, if you prefer.', 'Service', 'B1', 'STAFF', null),
('HK_HK_DND_0006', 'HK_DND', 'Je note le DND et j’informe la réception.', 'I will note the DND and inform the front desk.', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_DND_0007', 'HK_DND', 'Merci, je ne vous dérange pas.', 'Thank you, I will not disturb you.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_DND_0008', 'HK_DND', 'N’hésitez pas à appeler Housekeeping quand vous serez disponible.', 'Please call Housekeeping when you are available.', 'Information', 'A2', 'STAFF', null),
('HK_HK_DND_0009', 'HK_DND', 'Je ne veux pas de service.', 'I do not want service.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_DND_0010', 'HK_DND', 'Revenez après {time}, s’il vous plaît.', 'Please come back after {time}.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_DND_0011', 'HK_DND', 'Laissez des serviettes devant la porte.', 'Leave towels at the door.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_DND_0012', 'HK_DND', 'Pourquoi vous insistez ?', 'Why are you insisting?', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_DND_0013', 'HK_DND', 'Je comprends. Nous respectons votre intimité.', 'I understand. We respect your privacy.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_DND_0014', 'HK_DND', 'Nous devons juste vérifier votre sécurité, sans entrer, si cela vous convient.', 'We only need to confirm your safety, without entering, if that suits you.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_DND_0015', 'HK_DND', 'Je programme le service à {time} et je confirme à la réception.', 'I will schedule the service at {time} and confirm with the front desk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_DND_0016', 'HK_DND', 'Merci. Je vous souhaite une bonne journée.', 'Thank you. Have a good day.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0001', 'HK_LATE_SERVICE', 'Bonsoir, Housekeeping. Comment puis-je vous aider ?', 'Good evening, Housekeeping. How can I help you?', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_LATE_SERVICE_0002', 'HK_LATE_SERVICE', 'Je peux vous apporter des serviettes ou des oreillers.', 'I can bring towels or pillows.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LATE_SERVICE_0003', 'HK_LATE_SERVICE', 'De combien d’articles avez-vous besoin ?', 'How many items do you need?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_LATE_SERVICE_0004', 'HK_LATE_SERVICE', 'Je vous les apporte dans {time} minutes.', 'I will bring them within {time} minutes.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LATE_SERVICE_0005', 'HK_LATE_SERVICE', 'Merci de patienter, je suis en route.', 'Thank you for waiting, I am on my way.', 'Information', 'A2', 'STAFF', null),
('HK_HK_LATE_SERVICE_0006', 'HK_LATE_SERVICE', 'Si c’est urgent, je peux prioriser votre demande.', 'If it is urgent, I can prioritize your request.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0007', 'HK_LATE_SERVICE', 'Je confirme : {qty} serviettes et {qty} oreillers, c’est bien cela ?', 'To confirm: {qty} towels and {qty} pillows, is that correct?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0008', 'HK_LATE_SERVICE', 'Voici, avec plaisir.', 'Here you are, with pleasure.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0009', 'HK_LATE_SERVICE', 'Pouvez-vous apporter des serviettes, s’il vous plaît ?', 'Could you bring towels, please?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LATE_SERVICE_0010', 'HK_LATE_SERVICE', 'J’ai besoin d’un oreiller de plus.', 'I need an extra pillow.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LATE_SERVICE_0011', 'HK_LATE_SERVICE', 'C’est assez urgent.', 'It is quite urgent.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_LATE_SERVICE_0012', 'HK_LATE_SERVICE', 'Je suis fatigué(e), pouvez-vous faire vite ?', 'I am tired, could you be quick?', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_LATE_SERVICE_0013', 'HK_LATE_SERVICE', 'Je comprends. Je m’en occupe immédiatement.', 'I understand. I will handle it immediately.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0014', 'HK_LATE_SERVICE', 'Merci. Je vous appelle si j’ai un retard.', 'Thank you. I will call you if there is any delay.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0015', 'HK_LATE_SERVICE', 'Souhaitez-vous que je passe en mode silencieux pour ne pas vous réveiller ?', 'Would you like me to be quiet so I do not wake you?', 'Service', 'B1', 'STAFF', null),
('HK_HK_LATE_SERVICE_0016', 'HK_LATE_SERVICE', 'Bonne nuit.', 'Good night.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_LOST_FOUND_0001', 'HK_LOST_FOUND', 'Bonjour, je vous écoute. Quel objet manque-t-il ?', 'Good morning, I am listening. Which item is missing?', 'Accueil', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0002', 'HK_LOST_FOUND', 'Pouvez-vous décrire l’objet, s’il vous plaît ?', 'Could you describe the item, please?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_LOST_FOUND_0003', 'HK_LOST_FOUND', 'Où l’avez-vous vu pour la dernière fois ?', 'Where did you last see it?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_LOST_FOUND_0004', 'HK_LOST_FOUND', 'Je vais vérifier avec l’équipe et le desk.', 'I will check with the team and the front desk.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LOST_FOUND_0005', 'HK_LOST_FOUND', 'Nous avons une procédure Lost & Found.', 'We have a Lost & Found procedure.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0006', 'HK_LOST_FOUND', 'Je vais enregistrer la déclaration et demander une recherche.', 'I will log the report and request a search.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0007', 'HK_LOST_FOUND', 'Si nous retrouvons l’objet, la réception vous contactera.', 'If we find the item, the front desk will contact you.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0008', 'HK_LOST_FOUND', 'Merci. Je vous tiens informé(e).', 'Thank you. I will keep you updated.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0009', 'HK_LOST_FOUND', 'J’ai perdu mon chargeur.', 'I lost my charger.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_LOST_FOUND_0010', 'HK_LOST_FOUND', 'Je pense que je l’ai laissé dans la chambre.', 'I think I left it in the room.', 'Vérification', 'A2', 'CLIENT', null),
('HK_HK_LOST_FOUND_0011', 'HK_LOST_FOUND', 'C’est urgent, j’en ai besoin aujourd’hui.', 'It’s urgent, I need it today.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_LOST_FOUND_0012', 'HK_LOST_FOUND', 'Pouvez-vous vérifier immédiatement ?', 'Can you check immediately?', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_LOST_FOUND_0013', 'HK_LOST_FOUND', 'Je comprends. Je lance la recherche tout de suite et je reviens vers vous dans {time} minutes.', 'I understand. I will start the search right away and get back to you within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0014', 'HK_LOST_FOUND', 'Pour des raisons de sécurité, toute remise d’objet se fait via la réception.', 'For security reasons, all item returns are handled via the front desk.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0015', 'HK_LOST_FOUND', 'Avez-vous un numéro de téléphone pour le suivi ?', 'Do you have a phone number for follow-up?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_LOST_FOUND_0016', 'HK_LOST_FOUND', 'Merci pour votre patience.', 'Thank you for your patience.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0001', 'HK_DAMAGE_REPORT', 'Je dois signaler un dégât dans la chambre {room_number}.', 'I need to report damage in room {room_number}.', 'Information', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0002', 'HK_DAMAGE_REPORT', 'L’objet concerné est {item}.', 'The item concerned is {item}.', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0003', 'HK_DAMAGE_REPORT', 'Je prends une photo pour le dossier.', 'I am taking a photo for the record.', 'Service', 'A2', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0004', 'HK_DAMAGE_REPORT', 'Je préviens la réception et la maintenance.', 'I will inform the front desk and maintenance.', 'Service', 'A2', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0005', 'HK_DAMAGE_REPORT', 'Pouvez-vous confirmer si la chambre est occupée ?', 'Could you confirm if the room is occupied?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0006', 'HK_DAMAGE_REPORT', 'Nous allons sécuriser la zone pour éviter tout risque.', 'We will secure the area to avoid any risk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0007', 'HK_DAMAGE_REPORT', 'Je reste factuel(le) et je note l’heure.', 'I will remain factual and note the time.', 'Information', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0008', 'HK_DAMAGE_REPORT', 'Merci, je vous tiens au courant.', 'Thank you, I will keep you informed.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0009', 'HK_DAMAGE_REPORT', 'Qu’est-ce qui s’est passé ?', 'What happened?', 'Vérification', 'B1', 'CLIENT', null),
('HK_HK_DAMAGE_REPORT_0010', 'HK_DAMAGE_REPORT', 'Je n’ai rien cassé.', 'I did not break anything.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_DAMAGE_REPORT_0011', 'HK_DAMAGE_REPORT', 'Le miroir est fissuré.', 'The mirror is cracked.', 'Information', 'A2', 'CLIENT', null),
('HK_HK_DAMAGE_REPORT_0012', 'HK_DAMAGE_REPORT', 'Pouvez-vous le réparer rapidement ?', 'Can you fix it quickly?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_DAMAGE_REPORT_0013', 'HK_DAMAGE_REPORT', 'Je comprends. Je transmets immédiatement à la maintenance pour intervention prioritaire.', 'I understand. I will inform maintenance immediately for priority intervention.', 'Service', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0014', 'HK_DAMAGE_REPORT', 'Pour votre sécurité, nous pouvons intervenir pendant votre absence si vous l’autorisez.', 'For your safety, we can intervene while you are out if you authorize it.', 'Service', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0015', 'HK_DAMAGE_REPORT', 'Je vous remercie. La réception reviendra vers vous pour la suite.', 'Thank you. The front desk will follow up with you.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_DAMAGE_REPORT_0016', 'HK_DAMAGE_REPORT', 'Je note votre demande et je reviens vers vous.', 'I will note your request and get back to you.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0001', 'HK_MAINT_REQUEST', 'Bonjour, je suis désolé(e) pour le problème.', 'I’m sorry about the issue.', 'Conflit', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0002', 'HK_MAINT_REQUEST', 'Pouvez-vous me dire ce qui ne fonctionne pas ?', 'Could you tell me what is not working?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0003', 'HK_MAINT_REQUEST', 'Est-ce une urgence (fuite, électricité) ?', 'Is it an emergency (leak, electricity)?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0004', 'HK_MAINT_REQUEST', 'Je contacte la maintenance tout de suite.', 'I am contacting maintenance right away.', 'Service', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0005', 'HK_MAINT_REQUEST', 'Nous pouvons couper l’eau/l’électricité si nécessaire.', 'We can turn off the water/electricity if needed.', 'Service', 'B1', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0006', 'HK_MAINT_REQUEST', 'Un technicien peut intervenir dans {time} minutes.', 'A technician can attend within {time} minutes.', 'Information', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0007', 'HK_MAINT_REQUEST', 'Puis-je entrer pour vérifier rapidement ?', 'May I come in to check quickly?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0008', 'HK_MAINT_REQUEST', 'Merci, je vous tiens informé(e).', 'Thank you, I will keep you updated.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0009', 'HK_MAINT_REQUEST', 'La climatisation ne fonctionne pas.', 'The air conditioning is not working.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_MAINT_REQUEST_0010', 'HK_MAINT_REQUEST', 'Il y a une fuite dans la salle de bain.', 'There is a leak in the bathroom.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_MAINT_REQUEST_0011', 'HK_MAINT_REQUEST', 'C’est dangereux.', 'It’s dangerous.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_MAINT_REQUEST_0012', 'HK_MAINT_REQUEST', 'Je veux une solution maintenant.', 'I want a solution now.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_MAINT_REQUEST_0013', 'HK_MAINT_REQUEST', 'Je comprends. Je fais intervenir la maintenance en priorité et je reviens vers vous dans {time} minutes.', 'I understand. I will prioritize maintenance and update you within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0014', 'HK_MAINT_REQUEST', 'Si nécessaire, la réception pourra proposer un changement de chambre.', 'If needed, the front desk can arrange a room change.', 'Service', 'B1', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0015', 'HK_MAINT_REQUEST', 'Pour votre sécurité, merci de ne pas utiliser {item} pour l’instant.', 'For your safety, please do not use {item} for now.', 'Information', 'B1', 'STAFF', null),
('HK_HK_MAINT_REQUEST_0016', 'HK_MAINT_REQUEST', 'Merci pour votre patience.', 'Thank you for your patience.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0001', 'HK_STAIN_COMPLAINT', 'Je suis vraiment désolé(e) d’entendre cela.', 'I’m truly sorry to hear that.', 'Conflit', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0002', 'HK_STAIN_COMPLAINT', 'Pouvez-vous me montrer la tache, s’il vous plaît ?', 'Could you show me the stain, please?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0003', 'HK_STAIN_COMPLAINT', 'Je remplace l’article immédiatement.', 'I will replace the item immediately.', 'Service', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0004', 'HK_STAIN_COMPLAINT', 'Je vous apporte des draps/serviettes propres.', 'I will bring clean sheets/towels.', 'Service', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0005', 'HK_STAIN_COMPLAINT', 'Je vais faire retirer cet article pour traitement.', 'I will have this item taken for treatment.', 'Service', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0006', 'HK_STAIN_COMPLAINT', 'Je vais aussi contrôler le reste du linge.', 'I will also check the rest of the linen.', 'Service', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0007', 'HK_STAIN_COMPLAINT', 'Merci de votre patience.', 'Thank you for your patience.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0008', 'HK_STAIN_COMPLAINT', 'Tout est remplacé. Est-ce acceptable ?', 'Everything has been replaced. Is that acceptable?', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0009', 'HK_STAIN_COMPLAINT', 'Il y a une tache sur le drap.', 'There is a stain on the sheet.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_STAIN_COMPLAINT_0010', 'HK_STAIN_COMPLAINT', 'Ces serviettes ne sont pas propres.', 'These towels are not clean.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_STAIN_COMPLAINT_0011', 'HK_STAIN_COMPLAINT', 'Je suis très déçu(e).', 'I’m very disappointed.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_STAIN_COMPLAINT_0012', 'HK_STAIN_COMPLAINT', 'Je veux un remplacement tout de suite.', 'I want a replacement right away.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_STAIN_COMPLAINT_0013', 'HK_STAIN_COMPLAINT', 'Je comprends. Je remplace immédiatement et je fais vérifier la chambre par un superviseur.', 'I understand. I will replace it immediately and have a supervisor recheck the room.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0014', 'HK_STAIN_COMPLAINT', 'Je note l’incident et j’en informe la réception.', 'I will log the incident and inform the front desk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0015', 'HK_STAIN_COMPLAINT', 'Je reviens dans {time} minutes avec des articles neufs.', 'I will be back within {time} minutes with new items.', 'Information', 'A2', 'STAFF', null),
('HK_HK_STAIN_COMPLAINT_0016', 'HK_STAIN_COMPLAINT', 'Veuillez accepter nos excuses pour ce désagrément.', 'Please accept our apologies for the inconvenience.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0001', 'HK_ODOR_SMELL', 'Je suis désolé(e) pour l’odeur.', 'I’m sorry about the smell.', 'Conflit', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0002', 'HK_ODOR_SMELL', 'Pouvez-vous me dire d’où vient l’odeur ?', 'Could you tell me where the smell is coming from?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0003', 'HK_ODOR_SMELL', 'Je vais vérifier la ventilation et la salle de bain.', 'I will check the ventilation and bathroom.', 'Service', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0004', 'HK_ODOR_SMELL', 'Je peux désodoriser la chambre maintenant.', 'I can deodorize the room now.', 'Service', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0005', 'HK_ODOR_SMELL', 'Si l’odeur persiste, la réception pourra proposer une autre chambre.', 'If the smell persists, the front desk can arrange another room.', 'Information', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0006', 'HK_ODOR_SMELL', 'Je reviens vers vous dans {time} minutes avec une solution.', 'I will get back to you within {time} minutes with a solution.', 'Information', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0007', 'HK_ODOR_SMELL', 'Merci de patienter.', 'Thank you for waiting.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0008', 'HK_ODOR_SMELL', 'Est-ce mieux maintenant ?', 'Is it better now?', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0009', 'HK_ODOR_SMELL', 'Il y a une odeur de fumée.', 'There is a smell of smoke.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_ODOR_SMELL_0010', 'HK_ODOR_SMELL', 'Ça sent le moisi.', 'It smells musty.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_ODOR_SMELL_0011', 'HK_ODOR_SMELL', 'C’est très désagréable.', 'It’s very unpleasant.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_ODOR_SMELL_0012', 'HK_ODOR_SMELL', 'Je veux changer de chambre.', 'I want to change rooms.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_ODOR_SMELL_0013', 'HK_ODOR_SMELL', 'Je comprends. Je traite la chambre immédiatement et je contacte la réception pour une option de changement si besoin.', 'I understand. I will treat the room immediately and contact the front desk for a room change option if needed.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0014', 'HK_ODOR_SMELL', 'Pour agir vite, puis-je entrer maintenant ?', 'To act quickly, may I enter now?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_ODOR_SMELL_0015', 'HK_ODOR_SMELL', 'Je vais demander à la maintenance de vérifier le filtre.', 'I will ask maintenance to check the filter.', 'Service', 'B1', 'STAFF', null),
('HK_HK_ODOR_SMELL_0016', 'HK_ODOR_SMELL', 'Merci. Je vous tiens informé(e).', 'Thank you. I will keep you updated.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0001', 'HK_BATHROOM_ISSUE', 'Je suis vraiment désolé(e) pour ce problème de salle de bain.', 'I’m truly sorry about this bathroom issue.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0002', 'HK_BATHROOM_ISSUE', 'Pouvez-vous me préciser ce qui ne va pas ?', 'Could you tell me what is wrong?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0003', 'HK_BATHROOM_ISSUE', 'Je vais corriger cela immédiatement.', 'I will fix this immediately.', 'Service', 'A2', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0004', 'HK_BATHROOM_ISSUE', 'Je vais refaire un nettoyage complet de la salle de bain.', 'I will redo a full bathroom cleaning.', 'Service', 'A2', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0005', 'HK_BATHROOM_ISSUE', 'Je vais contrôler les produits et les accessoires.', 'I will check the amenities and accessories.', 'Service', 'A2', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0006', 'HK_BATHROOM_ISSUE', 'Si nécessaire, je demande une inspection superviseur.', 'If needed, I will request a supervisor inspection.', 'Service', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0007', 'HK_BATHROOM_ISSUE', 'Merci de patienter, s’il vous plaît.', 'Thank you for waiting, please.', 'Information', 'A2', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0008', 'HK_BATHROOM_ISSUE', 'Je vous remercie. Est-ce acceptable maintenant ?', 'Thank you. Is it acceptable now?', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0009', 'HK_BATHROOM_ISSUE', 'Il y a des cheveux dans la douche.', 'There are hairs in the shower.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_BATHROOM_ISSUE_0010', 'HK_BATHROOM_ISSUE', 'La salle de bain n’est pas propre.', 'The bathroom is not clean.', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_BATHROOM_ISSUE_0011', 'HK_BATHROOM_ISSUE', 'C’est inacceptable.', 'This is unacceptable.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_BATHROOM_ISSUE_0012', 'HK_BATHROOM_ISSUE', 'Je veux que ce soit réglé tout de suite.', 'I want this fixed right away.', 'Conflit', 'B1', 'CLIENT', null),
('HK_HK_BATHROOM_ISSUE_0013', 'HK_BATHROOM_ISSUE', 'Je comprends. Je prends en charge personnellement et je finis dans {time} minutes.', 'I understand. I will take care of it personally and finish within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0014', 'HK_BATHROOM_ISSUE', 'Pour votre confort, je peux vous apporter des serviettes neuves pendant le nettoyage.', 'For your comfort, I can bring fresh towels while we clean.', 'Service', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0015', 'HK_BATHROOM_ISSUE', 'Je note l’incident et je le remonte au desk.', 'I will log the incident and report it to the front desk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_BATHROOM_ISSUE_0016', 'HK_BATHROOM_ISSUE', 'Veuillez accepter nos excuses.', 'Please accept our apologies.', 'Conflit', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0001', 'HK_PUBLIC_AREAS', 'Bonjour, excusez-moi, je nettoie le couloir.', 'Good morning, excuse me, I am cleaning the corridor.', 'Information', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0002', 'HK_PUBLIC_AREAS', 'Attention, sol mouillé.', 'Caution, wet floor.', 'Information', 'A1', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0003', 'HK_PUBLIC_AREAS', 'Pouvez-vous passer de l’autre côté, s’il vous plaît ?', 'Could you pass on the other side, please?', 'Service', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0004', 'HK_PUBLIC_AREAS', 'Je termine dans {time} minutes.', 'I will be finished in {time} minutes.', 'Information', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0005', 'HK_PUBLIC_AREAS', 'Merci de votre compréhension.', 'Thank you for your understanding.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0006', 'HK_PUBLIC_AREAS', 'Je nettoie l’ascenseur après votre passage.', 'I will clean the elevator after you pass.', 'Service', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0007', 'HK_PUBLIC_AREAS', 'Je vais vider les poubelles et essuyer les surfaces.', 'I will empty the bins and wipe the surfaces.', 'Service', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0008', 'HK_PUBLIC_AREAS', 'Tout est propre.', 'Everything is clean.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0009', 'HK_PUBLIC_AREAS', 'Pardon.', 'Sorry.', 'Accueil', 'A1', 'CLIENT', null),
('HK_HK_PUBLIC_AREAS_0010', 'HK_PUBLIC_AREAS', 'Puis-je passer ?', 'May I pass?', 'Vérification', 'A1', 'CLIENT', null),
('HK_HK_PUBLIC_AREAS_0011', 'HK_PUBLIC_AREAS', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_PUBLIC_AREAS_0012', 'HK_PUBLIC_AREAS', 'Le sol est glissant.', 'The floor is slippery.', 'Information', 'A2', 'CLIENT', null),
('HK_HK_PUBLIC_AREAS_0013', 'HK_PUBLIC_AREAS', 'Merci de me l’indiquer. Je sécurise la zone immédiatement.', 'Thank you for letting me know. I will secure the area immediately.', 'Service', 'B1', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0014', 'HK_PUBLIC_AREAS', 'Pour votre sécurité, je vais ajouter un panneau supplémentaire.', 'For your safety, I will add an extra warning sign.', 'Service', 'B1', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0015', 'HK_PUBLIC_AREAS', 'Je peux interrompre un instant pour vous laisser passer.', 'I can pause for a moment to let you pass.', 'Service', 'B1', 'STAFF', null),
('HK_HK_PUBLIC_AREAS_0016', 'HK_PUBLIC_AREAS', 'Bonne journée.', 'Have a nice day.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0001', 'HK_LAUNDRY_GUEST', 'Bonjour, je peux vous aider avec la blanchisserie.', 'Good morning, I can help you with laundry service.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0002', 'HK_LAUNDRY_GUEST', 'Avez-vous rempli le formulaire de blanchisserie ?', 'Have you filled in the laundry form?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0003', 'HK_LAUNDRY_GUEST', 'Souhaitez-vous un service express ?', 'Would you like express service?', 'Service', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0004', 'HK_LAUNDRY_GUEST', 'Le délai standard est {time} heures.', 'The standard turnaround is {time} hours.', 'Information', 'A2', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0005', 'HK_LAUNDRY_GUEST', 'Le service express est prêt en {time} heures.', 'Express service is ready in {time} hours.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0006', 'HK_LAUNDRY_GUEST', 'Je récupère le sac et je le transmet au laundry.', 'I will collect the bag and send it to laundry.', 'Service', 'A2', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0007', 'HK_LAUNDRY_GUEST', 'Voulez-vous que je vérifie les poches avant ?', 'Would you like me to check the pockets first?', 'Service', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0008', 'HK_LAUNDRY_GUEST', 'Merci. Vous recevrez vos vêtements dans votre chambre.', 'Thank you. You will receive your clothes in your room.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0009', 'HK_LAUNDRY_GUEST', 'Je voudrais faire laver ces vêtements.', 'I would like these clothes washed.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LAUNDRY_GUEST_0010', 'HK_LAUNDRY_GUEST', 'C’est possible en express ?', 'Is express possible?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_LAUNDRY_GUEST_0011', 'HK_LAUNDRY_GUEST', 'À quelle heure ce sera prêt ?', 'What time will it be ready?', 'Information', 'A2', 'CLIENT', null),
('HK_HK_LAUNDRY_GUEST_0012', 'HK_LAUNDRY_GUEST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_LAUNDRY_GUEST_0013', 'HK_LAUNDRY_GUEST', 'Bien sûr. Je note express et je confirme le délai exact avec le laundry.', 'Of course. I will note express and confirm the exact time with laundry.', 'Service', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0014', 'HK_LAUNDRY_GUEST', 'Pour éviter tout incident, merci d’indiquer les pièces sur le formulaire.', 'To avoid any issue, please list the items on the form.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0015', 'HK_LAUNDRY_GUEST', 'Si un article nécessite un traitement spécial, je vous contacte avant.', 'If an item needs special treatment, I will contact you first.', 'Information', 'B1', 'STAFF', null),
('HK_HK_LAUNDRY_GUEST_0016', 'HK_LAUNDRY_GUEST', 'Merci pour votre confiance.', 'Thank you for your trust.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0001', 'HK_EXTRA_BED', 'Bonjour, je viens installer un lit supplémentaire.', 'Good morning, I am here to set up an extra bed.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_EXTRA_BED_0002', 'HK_EXTRA_BED', 'Où souhaitez-vous le placer ?', 'Where would you like it placed?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_EXTRA_BED_0003', 'HK_EXTRA_BED', 'Cela prendra {time} minutes.', 'This will take {time} minutes.', 'Information', 'A2', 'STAFF', null),
('HK_HK_EXTRA_BED_0004', 'HK_EXTRA_BED', 'Je vais préparer la literie et les oreillers.', 'I will prepare the bedding and pillows.', 'Service', 'A2', 'STAFF', null),
('HK_HK_EXTRA_BED_0005', 'HK_EXTRA_BED', 'Je peux aussi apporter une couverture supplémentaire.', 'I can also bring an extra blanket.', 'Service', 'A2', 'STAFF', null),
('HK_HK_EXTRA_BED_0006', 'HK_EXTRA_BED', 'Je vérifie que le passage reste sécurisé.', 'I will make sure the walkway remains safe.', 'Service', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0007', 'HK_EXTRA_BED', 'Le lit est prêt. Voulez-vous tester le confort ?', 'The bed is ready. Would you like to check the comfort?', 'Service', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0008', 'HK_EXTRA_BED', 'Merci. Je reste disponible.', 'Thank you. I remain available.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0009', 'HK_EXTRA_BED', 'Pouvez-vous ajouter un lit, s’il vous plaît ?', 'Could you add an extra bed, please?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_EXTRA_BED_0010', 'HK_EXTRA_BED', 'Mettez-le près de la fenêtre.', 'Put it near the window.', 'Vérification', 'A2', 'CLIENT', null),
('HK_HK_EXTRA_BED_0011', 'HK_EXTRA_BED', 'À quelle heure pouvez-vous venir ?', 'What time can you come?', 'Information', 'A2', 'CLIENT', null),
('HK_HK_EXTRA_BED_0012', 'HK_EXTRA_BED', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_EXTRA_BED_0013', 'HK_EXTRA_BED', 'Je comprends. Je confirme l’installation à {time}.', 'I understand. I will confirm the setup at {time}.', 'Service', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0014', 'HK_EXTRA_BED', 'Pour votre confort, je peux ajouter une lampe de chevet.', 'For your comfort, I can add a bedside lamp.', 'Service', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0015', 'HK_EXTRA_BED', 'Je vous appelle avant d’arriver pour éviter de vous déranger.', 'I will call before coming up so I don’t disturb you.', 'Information', 'B1', 'STAFF', null),
('HK_HK_EXTRA_BED_0016', 'HK_EXTRA_BED', 'Bonne journée.', 'Have a nice day.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_BABY_COT_0001', 'HK_BABY_COT', 'Bonjour, je viens installer un lit bébé.', 'Good morning, I am here to set up a baby cot.', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_BABY_COT_0002', 'HK_BABY_COT', 'Pour la sécurité, je le place loin des rideaux.', 'For safety, I will place it away from the curtains.', 'Information', 'B1', 'STAFF', null),
('HK_HK_BABY_COT_0003', 'HK_BABY_COT', 'Souhaitez-vous aussi une baignoire bébé ?', 'Would you also like a baby bath?', 'Service', 'B1', 'STAFF', null),
('HK_HK_BABY_COT_0004', 'HK_BABY_COT', 'Avez-vous besoin de draps supplémentaires ?', 'Do you need extra sheets?', 'Service', 'A2', 'STAFF', null),
('HK_HK_BABY_COT_0005', 'HK_BABY_COT', 'Cela prendra {time} minutes.', 'This will take {time} minutes.', 'Information', 'A2', 'STAFF', null),
('HK_HK_BABY_COT_0006', 'HK_BABY_COT', 'Je vérifie que tout est stable.', 'I will make sure everything is stable.', 'Service', 'A2', 'STAFF', null),
('HK_HK_BABY_COT_0007', 'HK_BABY_COT', 'Le lit bébé est prêt.', 'The baby cot is ready.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_BABY_COT_0008', 'HK_BABY_COT', 'Bonne journée.', 'Have a nice day.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_BABY_COT_0009', 'HK_BABY_COT', 'Nous avons besoin d’un lit bébé.', 'We need a baby cot.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_BABY_COT_0010', 'HK_BABY_COT', 'Est-ce sécurisé ?', 'Is it safe?', 'Information', 'A2', 'CLIENT', null),
('HK_HK_BABY_COT_0011', 'HK_BABY_COT', 'Pouvez-vous venir rapidement ?', 'Can you come quickly?', 'Conflit', 'A2', 'CLIENT', null),
('HK_HK_BABY_COT_0012', 'HK_BABY_COT', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_BABY_COT_0013', 'HK_BABY_COT', 'Oui, c’est sécurisé. Je le monte selon le standard et je vérifie la stabilité.', 'Yes, it is safe. I will set it up to standard and check stability.', 'Information', 'B1', 'STAFF', null),
('HK_HK_BABY_COT_0014', 'HK_BABY_COT', 'Je comprends. Je priorise votre demande et j’arrive dans {time} minutes.', 'I understand. I will prioritize your request and arrive within {time} minutes.', 'Conflit', 'B1', 'STAFF', null),
('HK_HK_BABY_COT_0015', 'HK_BABY_COT', 'Souhaitez-vous que je montre comment plier le lit bébé ?', 'Would you like me to show you how to fold the cot?', 'Service', 'B1', 'STAFF', null),
('HK_HK_BABY_COT_0016', 'HK_BABY_COT', 'N’hésitez pas à appeler si vous avez besoin d’aide.', 'Please call if you need any help.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0001', 'HK_VIP_SETUP', 'Je prépare la chambre VIP selon la checklist.', 'I am preparing the VIP room according to the checklist.', 'Information', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0002', 'HK_VIP_SETUP', 'Je vérifie les amenities premium et la lettre de bienvenue.', 'I am checking the premium amenities and welcome letter.', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0003', 'HK_VIP_SETUP', 'Je contrôle la propreté et les détails (miroirs, poussière).', 'I am checking cleanliness and details (mirrors, dust).', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0004', 'HK_VIP_SETUP', 'Je place les fruits et la bouteille selon les instructions.', 'I will place the fruit and bottle as instructed.', 'Service', 'A2', 'STAFF', null),
('HK_HK_VIP_SETUP_0005', 'HK_VIP_SETUP', 'Je vérifie l’odeur de la chambre et la température.', 'I will check the room scent and temperature.', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0006', 'HK_VIP_SETUP', 'Tout est conforme. Je valide avec le superviseur.', 'Everything is compliant. I will validate with the supervisor.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0007', 'HK_VIP_SETUP', 'Je peux ajuster les oreillers selon la préférence VIP.', 'I can adjust pillows to the VIP preference.', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0008', 'HK_VIP_SETUP', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_VIP_SETUP_0009', 'HK_VIP_SETUP', 'Y a-t-il une attention spéciale dans la chambre ?', 'Is there a special amenity in the room?', 'Information', 'B1', 'CLIENT', null),
('HK_HK_VIP_SETUP_0010', 'HK_VIP_SETUP', 'Pouvez-vous ajouter une bouteille d’eau en plus ?', 'Could you add an extra bottle of water?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_VIP_SETUP_0011', 'HK_VIP_SETUP', 'Je préfère des oreillers fermes.', 'I prefer firm pillows.', 'Service', 'B1', 'CLIENT', null),
('HK_HK_VIP_SETUP_0012', 'HK_VIP_SETUP', 'Merci beaucoup.', 'Thank you very much.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_VIP_SETUP_0013', 'HK_VIP_SETUP', 'Bien sûr. Je note votre préférence et j’ajuste immédiatement.', 'Of course. I will note your preference and adjust right away.', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0014', 'HK_VIP_SETUP', 'Je m’assure que tout est parfait avant votre arrivée.', 'I will make sure everything is perfect before your arrival.', 'Information', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0015', 'HK_VIP_SETUP', 'Je confirme au desk que la chambre est prête.', 'I will confirm to the front desk that the room is ready.', 'Service', 'B1', 'STAFF', null),
('HK_HK_VIP_SETUP_0016', 'HK_VIP_SETUP', 'Bonne soirée.', 'Have a nice evening.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_SUPPLIES_0001', 'HK_SUPPLIES', 'Bonjour, Housekeeping. Que vous faut-il ?', 'Good morning, Housekeeping. What do you need?', 'Accueil', 'A2', 'STAFF', null),
('HK_HK_SUPPLIES_0002', 'HK_SUPPLIES', 'Je peux apporter de l’eau, du papier ou des capsules.', 'I can bring water, tissues, or coffee capsules.', 'Service', 'A2', 'STAFF', null),
('HK_HK_SUPPLIES_0003', 'HK_SUPPLIES', 'Combien en souhaitez-vous ?', 'How many would you like?', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_SUPPLIES_0004', 'HK_SUPPLIES', 'Je vous apporte cela dans {time} minutes.', 'I will bring that within {time} minutes.', 'Service', 'A2', 'STAFF', null),
('HK_HK_SUPPLIES_0005', 'HK_SUPPLIES', 'Je confirme : {qty} bouteilles d’eau, c’est bien ça ?', 'To confirm: {qty} bottles of water, is that correct?', 'Vérification', 'B1', 'STAFF', null),
('HK_HK_SUPPLIES_0006', 'HK_SUPPLIES', 'Je note votre préférence pour un réassort quotidien.', 'I will note your preference for daily restocking.', 'Information', 'B1', 'STAFF', null),
('HK_HK_SUPPLIES_0007', 'HK_SUPPLIES', 'Voici, avec plaisir.', 'Here you are, with pleasure.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_SUPPLIES_0008', 'HK_SUPPLIES', 'Bonne journée.', 'Have a nice day.', 'Clôture', 'A1', 'STAFF', null),
('HK_HK_SUPPLIES_0009', 'HK_SUPPLIES', 'Pouvez-vous apporter de l’eau, s’il vous plaît ?', 'Could you bring water, please?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_SUPPLIES_0010', 'HK_SUPPLIES', 'Il me manque du papier toilette.', 'I am missing toilet paper.', 'Service', 'A2', 'CLIENT', null),
('HK_HK_SUPPLIES_0011', 'HK_SUPPLIES', 'Avez-vous des capsules de café ?', 'Do you have coffee capsules?', 'Service', 'A2', 'CLIENT', null),
('HK_HK_SUPPLIES_0012', 'HK_SUPPLIES', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_SUPPLIES_0013', 'HK_SUPPLIES', 'Je comprends. Je vous apporte cela rapidement.', 'I understand. I will bring it quickly.', 'Service', 'B1', 'STAFF', null),
('HK_HK_SUPPLIES_0014', 'HK_SUPPLIES', 'Si vous préférez, je peux le déposer devant la porte.', 'If you prefer, I can leave it at the door.', 'Service', 'B1', 'STAFF', null),
('HK_HK_SUPPLIES_0015', 'HK_SUPPLIES', 'Je vous appelle à l’arrivée.', 'I will call you upon arrival.', 'Information', 'B1', 'STAFF', null),
('HK_HK_SUPPLIES_0016', 'HK_SUPPLIES', 'Merci pour votre patience.', 'Thank you for your patience.', 'Clôture', 'B1', 'STAFF', null),
('HK_HK_CHECKLIST_0001', 'HK_CHECKLIST', 'Je fais le contrôle qualité de la chambre.', 'I am doing the room quality check.', 'Information', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0002', 'HK_CHECKLIST', 'Je vérifie la salle de bain, le lit et les surfaces.', 'I am checking the bathroom, bed, and surfaces.', 'Service', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0003', 'HK_CHECKLIST', 'Je vérifie les lumières et la télécommande.', 'I am checking the lights and remote control.', 'Service', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0004', 'HK_CHECKLIST', 'Je vérifie les odeurs et la climatisation.', 'I am checking odors and the air conditioning.', 'Service', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0005', 'HK_CHECKLIST', 'Je complète la checklist et je signe.', 'I complete the checklist and sign it.', 'Vérification', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0006', 'HK_CHECKLIST', 'Je signale toute anomalie à la maintenance.', 'I report any issue to maintenance.', 'Service', 'B1', 'STAFF', null),
('HK_HK_CHECKLIST_0007', 'HK_CHECKLIST', 'La chambre est conforme et prête.', 'The room is compliant and ready.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0008', 'HK_CHECKLIST', 'Je confirme au desk.', 'I confirm with the front desk.', 'Service', 'B1', 'STAFF', null),
('HK_HK_CHECKLIST_0009', 'HK_CHECKLIST', 'La chambre est prête ?', 'Is the room ready?', 'Vérification', 'A2', 'CLIENT', null),
('HK_HK_CHECKLIST_0010', 'HK_CHECKLIST', 'Est-ce que tout est propre ?', 'Is everything clean?', 'Vérification', 'A2', 'CLIENT', null),
('HK_HK_CHECKLIST_0011', 'HK_CHECKLIST', 'Je veux une chambre parfaite.', 'I want a perfect room.', 'Information', 'B1', 'CLIENT', null),
('HK_HK_CHECKLIST_0012', 'HK_CHECKLIST', 'Merci.', 'Thank you.', 'Clôture', 'A1', 'CLIENT', null),
('HK_HK_CHECKLIST_0013', 'HK_CHECKLIST', 'Oui, la chambre est prête et contrôlée.', 'Yes, the room is ready and checked.', 'Clôture', 'A2', 'STAFF', null),
('HK_HK_CHECKLIST_0014', 'HK_CHECKLIST', 'Je comprends. Je fais un second contrôle pour être certain(e).', 'I understand. I will do a second check to be sure.', 'Service', 'B1', 'STAFF', null),
('HK_HK_CHECKLIST_0015', 'HK_CHECKLIST', 'Si vous remarquez quoi que ce soit, dites-le-nous et nous corrigerons immédiatement.', 'If you notice anything, tell us and we will correct it immediately.', 'Service', 'B1', 'STAFF', null),
('HK_HK_CHECKLIST_0016', 'HK_CHECKLIST', 'Bonne journée.', 'Have a nice day.', 'Clôture', 'A1', 'STAFF', null)
on conflict (id) do update set
  action_id = excluded.action_id,
  phrase_fr = excluded.phrase_fr,
  phrase_en = excluded.phrase_en,
  phase = excluded.phase,
  niveau = excluded.niveau,
  voice_type = excluded.voice_type,
  audio_url = excluded.audio_url;

commit;